#!/usr/bin/env python3
import json
import sys
from pathlib import Path

filepath = Path("/home/pipe/Documents/proyectos/cartas_natales/datos/casas_signos.json")
data = json.loads(filepath.read_text("utf-8"))

entries = {
    "casa_4_aries": (
        "Casa 4 en Aries\n\n"
        "Quienes tienen la Casa 4 en Aries provienen de un hogar donde la independencia fue aprendida antes que la ternura, donde la supervivencia emocional requeria afirmarse a si mismos porque nadie mas lo haria por ellos. La atmosfera familiar pudo haber sido competitiva, impulsiva o incluso belica, y en ese crisol se forjo una identidad que asocia la seguridad con la capacidad de defenderse y de abrir su propio camino. El hogar de origen no fue necesariamente un refugio sino un campo de entrenamiento donde aprendieron a pelear por su espacio y a no esperar que nadie los protegiera.\n\n"
        "La imagen que estas personas proyectan en su vida privada es de autosuficiencia y fortaleza. Parecen no necesitar de nadie, y su hogar refleja esa independencia: un espacio que les pertenece y donde nadie dicta las reglas. Sin embargo, detras de esa fachada de fortaleza se esconde una profunda necesidad de pertenencia que rara vez admiten, porque reconocerla les parece una forma de debilidad que contradice todo lo que aprendieron en la infancia. El conflicto interno es constante: desean la cercania y la seguridad del hogar, pero temen que esa misma cercania los atrape o los debilite.\n\n"
        "La sombra de esta posicion se manifiesta en la impaciencia con las dinamicas familiares, en la tendencia a huir del hogar cuando surgen conflictos en lugar de enfrentarlos con madurez, y en la dificultad para comprometerse con los espacios y las personas que podrian ofrecerles la estabilidad que en el fondo anhelan. La ira que aprendieron a usar como escudo en la infancia puede convertirse en un obstaculo para crear la paz domestica que genuinamente desean.\n\n"
        "En su expresion mas elevada, quienes tienen esta posicion rompen ciclos transgeneracionales de violencia o abandono con un coraje que pocos poseen. Llevan la iniciativa y la valentia a su vida familiar, y son capaces de establecer dinamicas nuevas y saludables donde antes habia patrones destructivos. Su mayor crecimiento ocurre cuando aprenden que la verdadera fortaleza incluye la capacidad de quedarse, de construir y de proteger, y que el hogar no es un campo de batalla sino un santuario que merece ser defendido con la misma pasion con la que defienden su individualidad."
    ),
    "casa_4_tauro": (
        "Casa 4 en Tauro\n\n"
        "Quienes tienen la Casa 4 en Tauro llevan grabada en el alma la necesidad de un hogar solido, estable y profundamente sensorial. La familia de origen probablemente les proporciono una base material segura, o la ausencia de ella les enseno el valor incalculable de tener un lugar al cual pertenecer. Para ellos, el hogar no es solo un espacio fisico sino una extension de su propio ser, un ancla que los sostiene en medio de las tormentas. La conexion con la tierra y las tradiciones familiares es parte fundamental de su identidad.\n\n"
        "La imagen que proyectan en el ambito domestico es de solidez y permanencia. Su hogar es acogedor, bien cuidado, con objetos que transmiten continuidad. Sin embargo, detras de esa estabilidad se esconde una resistencia al cambio que puede volverse rigidez. Pueden aferrarse a propiedades o tradiciones incluso cuando ya no les sirven, porque soltarlos les parece una traicion a sus raices y una amenaza a su seguridad emocional.\n\n"
        "El conflicto interno radica en la tension entre el apego a lo conocido y la necesidad de evolucionar. Su amor por la estabilidad puede impedir cambios necesarios, y la posesividad puede manifestarse en relaciones donde el amor se confunde con la propiedad. El miedo a perder la seguridad las mantiene en situaciones insalubres porque lo conocido, aunque doloroso, les resulta menos amenazante que lo desconocido.\n\n"
        "En su mejor expresion, los nativos de Casa 4 en Tauro crean hogares que son refugios de paz, belleza y confort. Su conexion con la tierra les da una base solida, y su capacidad de construir algo perdurable enriquece a quienes comparten su espacio. La sombra a trabajar es la posesividad y la resistencia al cambio, aprendiendo que la verdadera seguridad no esta en aferrarse a lo material sino en adaptarse sin perder la esencia."
    ),
    "casa_4_geminis": (
        "Casa 4 en Geminis\n\n"
        "Quienes tienen la Casa 4 en Geminis crecieron en un hogar donde la palabra era el principal vehículo de conexión, donde las conversaciones fluian sin cesar y el intercambio intelectual ocupaba el centro de la vida familiar. La familia pudo haber sido ruidosa, llena de debates, o un espacio donde la comunicacion reemplazaba a la expresion emocional directa. Estos nativos aprendieron que el hogar es un lugar donde se habla y se intercambian ideas, pero no necesariamente donde se siente en profundidad.\n\n"
        "La imagen que proyectan en su vida privada es de curiosidad intelectual y adaptabilidad. Su hogar esta lleno de libros y tecnologia, y mantienen una relacion versatil con el espacio, reorganizandolo con frecuencia. Sin embargo, detras de esa actividad constante se esconde una dificultad para encontrar la tranquilidad emocional que el hogar deberia proporcionar. La mente no descansa, y esa inquietud interfiere con la conexion profunda que anhelan pero rara vez se permiten experimentar.\n\n"
        "El conflicto central es la tendencia a intelectualizar las emociones y mantenerse en la superficie de las relaciones familiares. Tienen una relacion ambivalente con las tradiciones, sintiendose atraidos y repelidos a la vez. Su necesidad de estimulo mental las lleva a evitar la intimidad que requiere silencio y profundidad. La sombra se manifiesta en la dispersion de las raices: saber mucho de la historia familiar pero no sentirla, hablar de las emociones pero no habitarlas.\n\n"
        "En su expresion mas elevada, estas personas mantienen una relacion curiosa con su historia familiar que las convierte en las cronistas del clan. Investigan sus raices, documentan la historia y mantienen viva la comunicacion entre generaciones. Su crecimiento ocurre cuando aprenden a hacer silencio mental para escuchar no solo las palabras sino las emociones que subyacen, y cuando descubren que el hogar no es solo un lugar para pensar sino tambien para sentir y simplemente estar."
    ),
    "casa_4_cancer": (
        "Casa 4 en Cancer\n\n"
        "Quienes tienen la Casa 4 en Cancer llevan el hogar tatuado en el alma: Cancer rige naturalmente esta casa, y la posicion es la mas potente de todas. Estas personas estan tejidas con los hilos de su historia familiar de una manera que trasciende lo biologico. Su sentido de pertenencia es una necesidad tan basica como el oxigeno, y su bienestar emocional depende de la calidad de sus raices. La familia de origen, con sus luces y sombras, es el espejo donde todavia se miran para saber quienes son.\n\n"
        "La imagen que proyectan en el ambito domestico es de proteccion y cuidado inagotable. Su hogar es un espacio acogedor donde todos son bienvenidos, y ellas son el corazon emocional de la familia. Sin embargo, detras de esa fachada se esconde una dependencia emocional paralizante. Separarse del hogar de origen, establecer limites con la familia y construir una identidad propia fuera del clan son los desafios mas profundos de esta posicion.\n\n"
        "El conflicto surge de la confusion entre cuidar y fundirse con el otro. Su empatia es tan poderosa que absorben las emociones familiares como una esponja, perdiendo la distincion entre lo propio y lo ajeno. Las lealtades familiares, incluso las que las limitan, son vividas como mandatos incuestionables. La sombra se manifiesta en el victimismo, la manipulacion emocional inconsciente y la repeticion de patrones disfuncionales por miedo a romper la pertenencia.\n\n"
        "En su expresion mas elevada, los nativos de Casa 4 en Cancer son guardianes de la memoria familiar con una capacidad de nutrir que trasciende generaciones. Crean hogares donde todos se sienten acogidos, y su intuicion emocional las convierte en el pegamento que mantiene unida a la familia. El crecimiento ocurre cuando aprenden a nutrirse a si mismas con la misma dedicacion, y cuando descubren que el verdadero hogar no es un lugar ni una sangre, sino la capacidad de llevar la seguridad emocional dentro de si a donde quiera que vayan."
    ),
    "casa_4_leo": (
        "Casa 4 en Leo\n\n"
        "Quienes tienen la Casa 4 en Leo crecieron en un hogar donde la individualidad y la expresion creativa ocupaban un lugar central, o donde una figura dominante acaparaba la atencion dejando poco espacio para el brillo ajeno. En ambos casos, aprendieron que el hogar es un escenario y que la pertenencia se negocia a traves del reconocimiento. La familia de origen les enseno que el amor esta condicionado a la capacidad de brillar, de destacar, de ser especial, y esa creencia queda grabada en lo mas profundo de su psique.\n\n"
        "La imagen que proyectan en su vida privada es de calidez y generosidad teatral. Su casa suele ser el punto de reunion familiar, el lugar de las celebraciones y la fiesta. Sin embargo, detras de esa fachada radiante se esconde una necesidad profunda de ser el centro de atencion incluso en el ambito privado, y una dificultad para compartir el protagonismo emocional con los demas miembros de la familia.\n\n"
        "El conflicto interno es la lucha entre el deseo de ser reconocido y la necesidad de pertenecer sin condiciones. Pueden tener conflictos de autoridad con figuras parentales y rivalidades fraternales por la atencion. La sombra se manifiesta en el egocentrismo domestico, en la necesidad de controlar la escena familiar y en la dificultad para celebrar el brillo ajeno. El hogar puede volverse un campo de batalla por la atencion en lugar de un refugio de amor incondicional.\n\n"
        "En su expresion mas elevada, estas personas llenan su hogar de calidez y creatividad, transformandolo en un lugar magnetico donde todos quieren estar. Su generosidad es genuina y su capacidad de celebrar la vida enriquece a toda la familia. El crecimiento ocurre cuando aprenden que su valor no depende del aplauso ajeno, y que la verdadera realeza del hogar no es la que recibe mas atencion sino la que mas amor ofrece sin esperar nada a cambio."
    ),
    "casa_4_virgo": (
        "Casa 4 en Virgo\n\n"
        "Quienes tienen la Casa 4 en Virgo crecieron en un hogar donde el orden, la eficiencia y el servicio eran valores fundamentales, con una atmosfera de critica constante que moldeo su psique desde la infancia. La familia les transmitio que el amor se demuestra a traves de la utilidad, y que el hogar debe funcionar como un mecanismo de relojeria donde todo tiene su lugar. Esta herencia deja una marca de ansiedad que pocos comprenden desde fuera, pero que las acompania en cada aspecto de su vida domestica.\n\n"
        "La imagen que proyectan en el ambito domestico es de eficiencia y dedicacion. Su hogar esta impecablemente organizado, y ellas son el pilar practico del espacio familiar. Sin embargo, detras de esa fachada se esconde una autocrítica que las mantiene en insatisfaccion permanente. El perfeccionismo que aplican al hogar es una proyeccion de la exigencia interna: nunca esta suficientemente limpio, nunca hacen lo suficiente, nunca merecen realmente descansar.\n\n"
        "El conflicto interno es la confusion entre el orden y el amor. Pueden volverse tan rigidas con las rutinas que la calidez se congela y el hogar se vuelve un lugar de tension en lugar de refugio. La critica interiorizada se proyecta hacia los demas, creando un circulo de exigencia y decepcion que reproduce las dinamicas de la infancia. La sombra se manifiesta en la rigidez domestica, la ansiedad por el desorden y la incapacidad de relajarse en su propio espacio.\n\n"
        "En su mejor expresion, los nativos de Casa 4 en Virgo crean hogares que son modelos de organizacion y funcionalidad. Su atencion al detalle y su capacidad de mantener el hogar optimo benefician a todos los que comparten su espacio. El crecimiento ocurre cuando aprenden a aceptar la imperfeccion, cuando descubren que el amor no se demuestra solo con utilidad, y cuando se permiten ser cuidadas y no solo cuidadoras."
    ),
    "casa_4_libra": (
        "Casa 4 en Libra\n\n"
        "Quienes tienen la Casa 4 en Libra crecieron en un hogar donde la armonia y la estetica eran valores centrales, pero donde probablemente se evitaban los conflictos a toda costa, sacrificando la verdad en el altar de la paz superficial. La familia pudo haber sido diplomatica y socialmente consciente, pero detras de la cordialidad se escondian resentimientos no expresados y decisiones no tomadas. Estos nativos aprendieron que el hogar es un lugar donde se mantienen las apariencias y la belleza compensa la falta de autenticidad.\n\n"
        "La imagen que proyectan en su vida privada es de equilibrio y buen gusto. Su hogar es esteticamente armonioso, y las relaciones parecen fluir con suavidad. Sin embargo, detras de esa fachada se esconde una profunda dificultad para enfrentar los conflictos familiares y para expresar necesidades propias cuando amenazan la paz. La indecision se intensifica en el terreno domestico, donde el miedo a romper el equilibrio las paraliza.\n\n"
        "El conflicto interno es la tension entre la armonia y la autenticidad. Pueden sacrificar sus necesidades, opiniones y limites para mantener la paz, acumulando resentimientos que emergen de manera pasivo-agresiva o en estallidos desproporcionados. La sombra se manifiesta en la dependencia emocional de la pareja o la familia para sentirse completas, en la idealizacion de la infancia y en la evasion de conversaciones dificiles.\n\n"
        "En su expresion mas elevada, estas personas crean hogares que son obras de arte de la convivencia, donde la belleza enmarca relaciones autenticas y equilibradas. Su talento diplomatico las convierte en mediadoras naturales. El crecimiento ocurre cuando aprenden que la verdadera armonia no es ausencia de conflicto sino la capacidad de atravesar tormentas juntos, y cuando descubren que pueden estar solas en su hogar sin sentirse incompletas."
    ),
    "casa_4_escorpio": (
        "Casa 4 en Escorpio\n\n"
        "Quienes tienen la Casa 4 en Escorpio provienen de un hogar marcado por la intensidad emocional, los secretos familiares y las dinamicas de poder, con crisis profundas que dejaron cicatrices imborrables. La familia de origen pudo haber atravesado perdidas traumaticas, traiciones o transformaciones radicales que moldearon a estos nativos desde la infancia. Aprendieron que el hogar no es un lugar seguro sino un campo de fuerzas donde hay que leer las corrientes subterraneas para sobrevivir, y que el amor y el peligro pueden coexistir.\n\n"
        "La imagen que proyectan en el ambito domestico es de control y misterio. Su hogar es un espacio privado al que pocos acceden, y mantienen una reserva sobre su vida familiar que otros interpretan como secretismo. Sin embargo, detras de ese control se esconde una profunda desconfianza hacia la seguridad que el hogar deberia proporcionar. Llevan una carga emocional heredada que pesa como un legado invisible, acompanandolas a donde vayan.\n\n"
        "El conflicto interno es la lucha entre el control y la vulnerabilidad. Pueden repetir patrones de manipulacion y secretismo heredados incluso cuando juran no hacerlo. La desconfianza hacia la familia puede envenenar las relaciones domesticas y crear el aislamiento que temen. La sombra se manifiesta en la reproduccion de las dinamicas toxicas que juraron no repetir, en el control emocional y en la dificultad para perdonar las heridas del pasado.\n\n"
        "En su expresion mas elevada, los nativos de Casa 4 en Escorpio tienen una capacidad extraordinaria de sanar heridas familiares profundas y transformar las dinamicas toxicas en autenticidad y regeneracion. Su hogar se convierte en un espacio de curacion para toda la familia, donde los secretos se revelan sin culpa y el poder se comparte. El crecimiento ocurre cuando aprenden a confiar en el hogar que han construido y descubren que la verdadera intimidad no requiere control sino rendicion consciente."
    ),
    "casa_4_sagitario": (
        "Casa 4 en Sagitario\n\n"
        "Quienes tienen la Casa 4 en Sagitario crecieron en un hogar donde los valores filosoficos, la exploracion y la libertad de pensamiento eran fundamentales, valorando mas la experiencia del mundo que la permanencia en casa. La familia pudo haber viajado frecuentemente o tener una perspectiva multicultural. Estos nativos aprendieron que el hogar no es un destino sino un punto de partida, y que pertenecer no significa quedarse sino tener siempre un lugar al cual regresar.\n\n"
        "La imagen que proyectan en su vida privada es de apertura y generosidad. Su hogar es un espacio donde todos son bienvenidos, un centro de intercambio cultural donde las conversaciones atraviesan fronteras. Sin embargo, detras de esa expansion se esconde una dificultad para echar raices verdaderas. El amor por la libertad puede volverse evasion de la intimidad domestica, y la busqueda de horizontes lejanos puede ocultar el miedo a comprometerse con la estabilidad que en el fondo anhelan.\n\n"
        "El conflicto interno es la tension entre la exploracion y la pertenencia. Pueden sentirse atrapados por las responsabilidades domesticas y tener conflictos con las tradiciones familiares restrictivas. La sombra se manifiesta en la evasion de las responsabilidades familiares, la impaciencia con la rutina y la tendencia a idealizar cualquier lugar que no sea el hogar actual, creyendo que la felicidad esta siempre en el proximo destino.\n\n"
        "En su expresion mas elevada, estas personas llevan la expansion a su vida domestica de una manera que enriquece a toda la familia. Su hogar es un centro de intercambio cultural y su optimismo transforma el espacio en un lugar donde todo parece posible. El crecimiento ocurre cuando aprenden que la verdadera libertad incluye comprometerse sin sentirse atrapados, y que las raices mas profundas no limitan el vuelo sino que permiten remontar mas alto."
    ),
    "casa_4_capricornio": (
        "Casa 4 en Capricornio\n\n"
        "Quienes tienen la Casa 4 en Capricornio crecieron en un hogar donde la responsabilidad, la disciplina y la estructura eran valores incuestionables, con una figura parental autoritaria o expectativas elevadas que llegaron demasiado temprano. La familia les enseno que el hogar no es un lugar de descanso sino de deber, que la seguridad se gana con esfuerzo y que las emociones se administran con prudencia. Estos nativos aprendieron a ser adultos antes de tiempo, cargando con responsabilidades que no les correspondian.\n\n"
        "La imagen que proyectan en el ambito domestico es de seriedad y control. Su hogar es ordenado, funcional y tradicional, reflejando su necesidad de mantener las apariencias. Sin embargo, detras de esa responsabilidad ejemplar se esconde una profunda soledad emocional. Mostrar vulnerabilidad, pedir ayuda o descansar sin culpa son sus mayores desafios, porque aprendieron que su valor depende de lo que hacen, no de lo que son.\n\n"
        "El conflicto interno es la repeticion de patrones de frialdad heredados y la confusion entre amor y responsabilidad. Cargan con obligaciones que exceden lo razonable, sintiendo que sin ellas la estructura se derrumbara. La rigidez emocional aprendida como supervivencia se vuelve una prision que les impide la calidez y la intimidad. La sombra se manifiesta en la incapacidad de relajarse, el aislamiento afectivo y la reproduccion de las mismas dinamicas de exigencia que sufrieron.\n\n"
        "En su expresion mas elevada, los nativos de Casa 4 en Capricornio construyen hogares que son pilares de solidez, donde la tradicion se honra sin repetir sus aspectos limitantes. Su sentido del deber las convierte en el soporte familiar. El crecimiento ocurre cuando aprenden a permitirse la vulnerabilidad, cuando descubren que mostrar emociones es fortaleza, y cuando se dan permiso para ser cuidadas y no solo cuidadoras responsables."
    ),
    "casa_4_acuario": (
        "Casa 4 en Acuario\n\n"
        "Quienes tienen la Casa 4 en Acuario crecieron en un hogar poco convencional, donde la individualidad era valorada por encima de la pertenencia o donde habia una atmosfera de frialdad emocional que los llevo a refugiarse en su mundo interior. La familia pudo haber sido original o progresista, pero tambien emocionalmente distante, dejando la sensacion de no encajar en ningun lado. Aprendieron que el hogar no es necesariamente un lugar de calidez sino un espacio donde se respeta la diferencia, a costa de la intimidad.\n\n"
        "La imagen que proyectan en su vida privada es de originalidad e independencia. Su hogar refleja su personalidad unica, con espacios diseñados para la libertad individual. Sin embargo, detras de esa autosuficiencia se esconde una profunda necesidad de pertenencia que rara vez admiten. La dificultad para conectar emocionalmente con la familia de origen es una herida que intentan sanar creando sus propias tribus y definiciones de hogar.\n\n"
        "El conflicto interno es la tension entre la independencia y la conexion. Pueden sentirse atrapados por las expectativas familiares y rebelarse, pero esa rebelion las deja sin apoyo emocional. La distancia afectiva las protege de la vulnerabilidad pero las aisla de la intimidad que anhelan. La sombra se manifiesta en la desconexion emocional, la rebelion contra toda estructura familiar y la dificultad para comprometerse con un hogar estable.\n\n"
        "En su expresion mas elevada, estas personas crean hogares donde cada miembro puede ser autenticamente quien es. Su originalidad transforma el hogar en un laboratorio de nuevas formas de convivencia. El crecimiento ocurre cuando aprenden que la independencia no excluye la intimidad, y que pertenecer a una familia no significa perderse a si mismas sino encontrar un lugar donde su singularidad es celebrada."
    ),
    "casa_4_piscis": (
        "Casa 4 en Piscis\n\n"
        "Quienes tienen la Casa 4 en Piscis provienen de un hogar donde los limites eran difusos, donde la realidad y la fantasia se mezclaban y la sensibilidad espiritual era mas valorada que la eficiencia practica. La familia pudo haber sido artisticamente inclinada o caotica, con fronteras entre miembros tan permeables que resultaba dificil saber donde terminaba uno y empezaba el otro. Estos nativos aprendieron a absorber el estado emocional del hogar como una esponja, y esa porosidad se convirtio en su forma de relacionarse con el mundo.\n\n"
        "La imagen que proyectan en el ambito domestico es de compasion y apertura espiritual. Su hogar tiene una cualidad etérea, con espacios dedicados al arte o la meditacion, y ellas son el alma sensible de la familia. Sin embargo, detras de esa creatividad se esconde una profunda confusion acerca de sus raices. La idealizacion de la familia de origen, el sentimiento de no pertenecer y la tendencia a cargar con los dolores ajenos como propios son los desafios invisibles que enfrentan en silencio.\n\n"
        "El conflicto interno es la lucha por establecer un hogar solido cuando la tendencia natural es hacia la disolucion de los limites. La sensibilidad que las hace artisticamente dotadas es la misma que las hace vulnerables a la sobrecarga emocional. Pueden tener dificultades con las rutinas, el orden material y la proteccion contra dinamicas toxicas. La sombra se manifiesta en el escapismo a traves de la fantasia, las adicciones o la evasion de responsabilidades, y en perderse en el sufrimiento ajeno para evitar el propio.\n\n"
        "En su expresion mas elevada, los nativos de Casa 4 en Piscis crean hogares que son santuarios de paz, creatividad y conexion espiritual. Su compasion es tan profunda que pueden sanar heridas familiares con su presencia. El crecimiento ocurre cuando aprenden a establecer limites sin perder sensibilidad, cuando descubren que cuidar de si mismas no es egoismo sino la condicion para cuidar genuinamente, y cuando construyen un hogar interior tan solido que ningun externo puede perturbarlo."
    ),
}

for key, value in entries.items():
    data[key] = value

filepath.write_text(json.dumps(data, ensure_ascii=False, indent=2), "utf-8")

print("=== Character counts for casa_4_* entries ===")
for key in sorted(entries.keys()):
    length = len(entries[key])
    status = "OK" if length >= 1800 else "SHORT"
    print(f"{key}: {length} chars {status}")

min_len = min(len(v) for v in entries.values())
max_len = max(len(v) for v in entries.values())
print(f"\nMin: {min_len} chars")
print(f"Max: {max_len} chars")
all_ok = all(len(v) >= 1800 for v in entries.values())
print(f"\nAll >= 1800: {all_ok}")
sys.exit(0 if all_ok else 1)
