#!/usr/bin/env python3
import json
import re

with open("datos/planetas_signos.json", "r", encoding="utf-8") as f:
    raw = f.read()

data = json.loads(raw)

entries = {
    "mercurio_en_aries": (
        "La mente de Mercurio en Aries es como una chispa que salta antes de que la mecha se consuma por completo: "
        "rápida, impaciente, siempre un paso adelante de sí misma. Esta persona piensa a la velocidad del rayo, "
        "procesa la información con una urgencia que no admite demoras y responde antes de que el interlocutor "
        "termine de formular la pregunta. La imagen que proyecta es la de alguien mentalmente ágil, audaz, que "
        "no teme decir lo que piensa y que a menudo interrumpe no por mala educación sino porque su cabeza ya "
        "llegó a la conclusión mientras los demás aún están contemplando el problema. Sin embargo, dentro de "
        "ese torbellino intelectual habita un conflicto silencioso: la prisa por comprenderlo todo puede impedirle "
        "comprender algo realmente. La mente mercurial en Aries ataca cada idea como si fuera un enemigo al que "
        "hay que derrotar, y esa beligerancia cognitiva, aunque efectiva en tormentas de ideas o debates encendidos, "
        "le juega malas pasadas cuando la situación requiere matices, pausas o la simple humildad de no saber. "
        "Cuando logra canalizar esa electricidad mental hacia su expresión más positiva, se convierte en un pionero "
        "del pensamiento: alguien capaz de abrir caminos donde otros ven callejones sin salida, de lanzar hipótesis "
        "atrevidas sin miedo al ridículo y de contagiar su entusiasmo intelectual a quienes lo rodean. Aprende "
        "haciendo, equivocándose sobre la marcha y corrigiendo el rumbo sin dramas. Su palabra es directa, "
        "honesta, a veces cortante, pero nunca tediosa. La sombra de esta posición, no obstante, acecha en la "
        "impulsividad verbal: puede herir sin querer, prometer sin pensar y arrepentirse cuando ya es tarde. "
        "Mercurio en Aries necesita recordar que no todas las batallas se ganan atacando primero; algunas se "
        "ganan escuchando."
    ),
    "mercurio_en_tauro": (
        "Mercurio en Tauro piensa como un árbol que hunde sus raíces antes de estirar sus ramas: despacio, "
        "con método, con una paciencia que el mundo moderno ya no sabe nombrar. Esta persona no responde "
        "al estímulo inmediato; mastica las ideas, las paladea, las sopesa como quien examina una piedra "
        "preciosa a contraluz antes de decidir si vale la pena tallarla. La imagen que proyecta es la de una "
        "mente sólida, fiable, que no se deja arrastrar por modas intelectuales ni por la presión de tener que "
        "opinar al instante. Donde otros ven urgencia, ella ve proceso. Pero hay un conflicto interno que "
        "la habita como un rumor subterráneo: la misma lentitud que le permite comprender con hondura también "
        "puede convertirse en rigidez. La mente tauro se aferra a lo que ya conoce, desconfía de lo nuevo por "
        "el simple hecho de ser nuevo, y a menudo descarta una idea brillante solo porque no encaja en el "
        "mapa mental que ya construyó. Ese conservadurismo del pensamiento es su mayor fortaleza y su mayor "
        "prisión. En su expresión más luminosa, Mercurio en Tauro produce ideas que perduran: no ocurrencias "
        "pasajeras sino filosofías prácticas, sistemas bien armados, opiniones que resisten el paso del tiempo "
        "porque fueron forjadas a golpe de reflexión sostenida. Aprende mejor cuando puede conectar el "
        "conocimiento nuevo con experiencias sensoriales concretas, cuando toca, huele, ve. Su palabra es "
        "pausada, grave, y cuando habla los demás suelen escuchar porque intuyen que detrás de esa lentitud "
        "hay sustancia. La sombra de Mercurio en Tauro es el dogmatismo terco: la incapacidad de soltar una "
        "idea aunque la evidencia la desmienta, la pereza mental disfrazada de prudencia. Mercurio en Tauro "
        "aprende a flexibilizarse cuando comprende que la verdad, como la tierra, también necesita ser "
        "removida para seguir siendo fértil."
    ),
    "mercurio_en_geminis": (
        "Mercurio en Géminis no piensa: brinca. La mente geminiana es una mariposa eléctrica que va de flor "
        "en flor sin posarse nunca del todo, bebiendo aquí un dato, allá una historia, más allá una teoría "
        "que acaso olvide mañana. Esta persona habla con las manos, con los ojos, con la respiración; su "
        "pensamiento es tan veloz que a veces las palabras intentan alcanzarlo y llegan tarde, atropellándose "
        "unas a otras en una cascada que el interlocutor apenas logra seguir. La imagen que proyecta es la de "
        "alguien intelectualmente brillante, versátil, capaz de conversar sobre cualquier tema con una soltura "
        "que fascina y desarma. Pero en ese torbellino de conexiones hay un conflicto subterráneo: la mente "
        "geminiana se aburre con facilidad. Necesita estímulo constante, cambio, novedad, y esa necesidad "
        "puede convertirla en una coleccionista de saberes superficiales que nunca profundiza en nada. Sabe "
        "un poco de todo y mucho de nada, y esa conciencia, en sus momentos de honestidad, la inquieta. "
        "Además, la dualidad de Géminis la lleva a sostener opiniones contradictorias sin sentir la menor "
        "contradicción, lo que a los ojos ajenos puede parecer hipocresía cuando en realidad es simple "
        "versatilidad. Cuando Mercurio en Géminis encuentra su expresión positiva, es el mejor conversador "
        "del zodíaco: alguien que sabe preguntar, que escucha con genuina curiosidad y que tiende puentes "
        "entre ideas que nadie más supo conectar. Su aprendizaje es por ósmosis, por inmersión, por "
        "contaminación feliz con todo lo que lee, oye y ve. Escribe con soltura, habla con carisma y tiene "
        "el don de hacer accesible lo complejo. La sombra, sin embargo, es la dispersión: la mente que nunca "
        "se compromete con una idea el tiempo suficiente para darle forma sustancial. La información le "
        "sienta bien pero el conocimiento profundo le exige una quietud que aún no ha aprendido a cultivar."
    ),
    "mercurio_en_cancer": (
        "Mercurio en Cáncer piensa con el corazón. No es que esta persona no pueda ser lógica o analítica; "
        "es que para ella toda información llega filtrada por una capa de sentir, de intuición, de memoria "
        "emocional que colorea cada dato con un tinte personal e intransferible. La imagen que proyecta es "
        "la de alguien que habla con suavidad, que elige las palabras con cuidado y que parece saber "
        "exactamente qué necesita escuchar su interlocutor en cada momento. Posee una inteligencia "
        "empática que capta lo no dicho, que lee entre líneas y que registra los estados de ánimo ajenos "
        "como si fueran propios. Pero dentro de esa sensibilidad cognitiva late un conflicto íntimo: la "
        "mente canceriana tiende a confundir lo que siente con lo que es. Sus pensamientos se enredan con "
        "sus emociones hasta volverse indistinguibles, y entonces la objetividad se desvanece arrastrada "
        "por la marea de la subjetividad. Le cuesta separar la crítica a una idea de la crítica a su persona, "
        "porque para ella las ideas son extensiones de sí misma, pequeñas criaturas que ha gestado en su "
        "interior y que no puede soltar sin sentir que pierde algo de sí. En su versión más luminosa, "
        "Mercurio en Cáncer posee una memoria prodigiosa para todo lo que tiene relieve emocional: "
        "recuerda fechas, gestos, palabras dichas en un tono determinado, y usa ese archivo afectivo para "
        "cuidar de quienes ama. Su comunicación está al servicio de la protección: habla para crear "
        "refugio. Aprende mejor cuando el conocimiento nuevo resuena con su historia personal, cuando "
        "puede tocarlo emocionalmente antes de entenderlo racionalmente. La sombra de esta posición es "
        "la manipulación inconsciente: usa su inteligencia emocional para obtener cuidado o atención, "
        "o se calla lo que piensa por miedo a romper la armonía. Mercurio en Cáncer necesita aprender "
        "que el pensamiento también puede ser un océano tranquilo, no solo una corriente de afectos "
        "revueltos."
    ),
    "mercurio_en_leo": (
        "Mercurio en Leo piensa como quien actúa: con la certeza de que alguien lo está mirando. La mente "
        "leonina no concibe la idea modesta; todo pensamiento, por pequeño que sea, debe ser expresado "
        "con el brío de un monólogo shakespeariano. Esta persona no solo comunica: se exhibe. Habla con "
        "la espina dorsal erguida, con gestos amplios, con una voz que llena los espacios vacíos y que "
        "convierte cualquier anécdota en una epopeya. La imagen que proyecta es la de alguien magnético, "
        "seguro de sí mismo, que defiende sus opiniones con una convicción que a veces raya en la "
        "teatralidad y que siempre, siempre, logra que lo escuchen. Pero el conflicto que habita en el "
        "centro de ese brillo es la necesidad de aprobación. Mercurio en Leo no solo quiere comunicar "
        "una idea: quiere que esa idea sea aplaudida. Y esa dependencia del reconocimiento ajeno puede "
        "tergiversar su pensamiento, llevándolo a decir lo que causa efecto en lugar de lo que realmente "
        "piensa, o a aferrarse a una postura absurda solo porque ya la defendió en público. El orgullo "
        "intelectual es su talón de Aquiles: admitir que se equivocó le cuesta más que sostener un error. "
        "En su expresión más generosa, Mercurio en Leo es un comunicador nato que inspira, entusiasma y "
        "moviliza. Tiene el don de tomar una idea compleja y convertirla en un relato que cualquiera "
        "puede recordar, porque habla desde el corazón y con un sentido del espectáculo que atrapa la "
        "atención. Aprende mejor cuando el conocimiento está investido de pasión: leer le aburre si no "
        "puede sentir que ese saber lo engrandece o le sirve para brillar. Escribe con fuego, enseña "
        "con carisma, debate con estilo. La sombra de Mercurio en Leo es la arrogancia dogmática: "
        "la incapacidad de escuchar realmente porque está demasiado ocupado preparando su siguiente "
        "intervención brillante. Mercurio en Leo crece cuando descubre que la verdadera grandeza "
        "intelectual no está en tener siempre la razón, sino en tener la humildad de buscarla."
    ),
    "mercurio_en_virgo": (
        "Mercurio en Virgo no piensa: disecciona. La mente virginiana es un quirófano donde cada idea "
        "es examinada con bisturí, separada en sus componentes más minúsculos, clasificada, etiquetada "
        "y archivada en el estante que le corresponde. Esta persona nota lo que nadie más nota: la "
        "contradicción en un argumento, el dato que no cuadra, la palabra mal empleada, el error "
        "imperceptible que arruina la perfección del conjunto. La imagen que proyecta es la de alguien "
        "preciso, meticuloso, dueño de una inteligencia analítica que desmenuza la realidad con la "
        "frialdad de un entomólogo. Sin embargo, en el centro de esa maquinaria de precisión habita un "
        "conflicto silencioso: la mente virginiana jamás se da por satisfecha. Siempre hay un detalle que "
        "podría ser mejor, una formulación más exacta, un conocimiento que aún no domina. Esa "
        "insatisfacción perpetua, ese ruido interno de autocrítica constante, convierte el aprendizaje en "
        "un campo minado donde cada error se vive como una falla moral. Mercurio en Virgo puede saber "
        "muchísimo y seguir sintiéndose insuficiente porque su vara de medir es la perfección imposible. "
        "En su versión más luminosa, esta posición produce mentes lúcidas, ordenadas, capaces de "
        "sintetizar información caótica en sistemas útiles. Mercurio en Virgo organiza, planifica, "
        "corrige y mejora todo lo que toca con una dedicación que raya en el arte. Su comunicación es "
        "clara, honesta, sin adornos innecesarios: dice exactamente lo que quiere decir y espera que los "
        "demás hagan lo mismo. Aprende mejor cuando puede descomponer el conocimiento en pasos, cuando "
        "hay un método claro y cuando el resultado sirve para algo práctico. La sombra de Mercurio en "
        "Virgo es la hipercrítica paralizante: el hábito de encontrar defectos en todo, incluido en sí "
        "mismo, hasta el punto de no atreverse a compartir una idea por miedo a que no sea perfecta. "
        "Mercurio en Virgo se reconcilia consigo mismo cuando entiende que la claridad no exige "
        "perfección, y que una comunicación sincera vale más que una impecable pero vacía."
    ),
    "mercurio_en_libra": (
        "Mercurio en Libra no piensa: sopesa. La mente libriana es una balanza que no descansa hasta "
        "encontrar el punto exacto donde todos los argumentos encajan en armonía. Esta persona detesta "
        "la confrontación intelectual porque la percibe como una ruptura del equilibrio, y prefiere "
        "dialogar, negociar, pulir las aristas de una discusión hasta redondearlas. La imagen que "
        "proyecta es la de alguien encantador, diplomático, dueño de una conversación fluida y "
        "agradable que hace sentir a los demás escuchados y valorados. Mercurio en Libra ve todos los "
        "ángulos de una cuestión con una claridad que a menudo sorprende, porque su mente está "
        "entrenada para la justicia, para el matiz, para evitar la trampa del fanatismo. Pero en el "
        "centro de ese equilibrio hay un conflicto que la consume: la indecisión. Ver todos los lados "
        "de un asunto puede impedirle tomar partido, y entonces la mente libriana se congela en la "
        "parálisis del análisis. No sabe qué prefiere porque prefiere todo por igual, no sabe qué "
        "opinar porque todas las opiniones le parecen defendibles. Esa búsqueda de la opinión perfecta "
        "y justa termina a menudo en la ausencia de opinión, o en la delegación de la decisión a otros "
        "para no cargar con la responsabilidad del error. En su expresión más elevada, Mercurio en Libra "
        "es un mediador nato, alguien capaz de traducir posturas enfrentadas en un lenguaje común. Su "
        "comunicación está al servicio de la paz y la cooperación: busca el acuerdo no por pereza "
        "intelectual sino por genuina convicción de que la verdad suele estar en el punto medio. "
        "Aprende mejor en contexto de intercambio, de diálogo, de discusión respetuosa; la lectura "
        "solitaria le parece insuficiente si no puede contrastarla con alguien. Escribe con elegancia, "
        "habla con medida, piensa con cortesía. La sombra de Mercurio en Libra es la complacencia "
        "excesiva: decir lo que el otro quiere oír para mantener la armonía, o evadir los temas "
        "incómodos disfrazando la omisión de prudencia. Mercurio en Libra madura cuando comprende "
        "que la verdadera diplomacia no consiste en evitar el conflicto, sino en atravesarlo con "
        "honestidad y respeto."
    ),
    "mercurio_en_escorpio": (
        "Mercurio en Escorpio no piensa: indaga. La mente escorpiana es un taladro que perfora la "
        "superficie de las cosas hasta alcanzar lo que nadie quiere mostrar. Esta persona no se "
        "conforma con la respuesta obvia; sospecha de ella, la interroga, la desmonta pieza por pieza "
        "hasta que la verdad oculta emerge, a veces incómoda, a veces devastadora. La imagen que "
        "proyecta es la de alguien intenso, magnético, cuya mirada parece atravesar las palabras y "
        "llegar directamente a las intenciones. Habla con una densidad que no admite la frivolidad: "
        "cuando Mercurio en Escorpio dice algo, vale la pena escucharlo, porque seguramente ha "
        "removido tierra antes de hablar. Pero el conflicto interno de esta posición es feroz: la mente "
        "escorpiana tiende a la fijación. Cuando una idea, una duda o un secreto se clava en su "
        "conciencia, no puede soltarlo. Rumia, da vueltas, escarba obsesivamente hasta que la "
        "respuesta aparece, y ese proceso puede consumirla durante días, semanas, años. Además, la "
        "desconfianza natural de Escorpio tiñe su comunicación: mide cada palabra porque sabe que las "
        "palabras también son armas, y prefiere el silencio a la exposición innecesaria. En su "
        "expresión más luminosa, Mercurio en Escorpio posee una inteligencia estratégica y una "
        "capacidad de concentración sobrehumana. No hay enigma que resista su perseverancia ni "
        "proyecto de investigación que no termine dominando. Su comunicación es poderosa porque "
        "toca fibras que otros evitan; habla de la muerte, del deseo, del poder, de la sombra, con "
        "una naturalidad que desconcierta y atrae. Aprende mejor cuando el conocimiento tiene hondura, "
        "cuando implica revelación, cuando puede sentir que está accediendo a una verdad secreta que "
        "pocos conocen. La sombra de Mercurio en Escorpio es la manipulación: usar el conocimiento "
        "de las debilidades ajenas como ventaja, o guardar información como forma de control. "
        "Mercurio en Escorpio se sana cuando descubre que la verdad más poderosa no es la que se "
        "usa contra otros, sino la que nos libera a nosotros mismos."
    ),
    "mercurio_en_sagitario": (
        "Mercurio en Sagitario piensa como unarquero que dispara hacia el horizonte: siempre más allá, "
        "siempre más lejos, siempre en busca de la próxima verdad que amplíe su mapa del mundo. Esta "
        "persona no se interesa por los detalles minuciosos ni por las discusiones bizantinas; lo suyo "
        "son las grandes ideas, los sistemas filosóficos, las preguntas que no tienen respuesta única y "
        "los viajes mentales que expanden la conciencia. La imagen que proyecta es la de alguien "
        "entusiasta, optimista, que habla con una convicción contagiosa y que tiene una respuesta para "
        "todo, aunque a veces esa respuesta sea más brillante que verdadera. Pero el conflicto que late "
        "en el centro de esa exuberancia intelectual es la impaciencia: la mente sagitariana salta de "
        "una idea a otra sin terminarse ninguna, persiguiendo la próxima revelación con el mismo "
        "entusiasmo con que abandonó la anterior. Le cuesta quedarse el tiempo necesario para que una "
        "idea madure porque la madurez le sabe a tedio. Además, su franqueza puede ser brutal: dice lo "
        "que piensa en el momento en que lo piensa, sin filtrar, sin medir las consecuencias, y a menudo "
        "descubre demasiado tarde que la verdad sin delicadeza es una forma de crueldad. En su expresión "
        "más positiva, Mercurio en Sagitario es un filósofo natural, un profesor que inspira, un "
        "conversador que eleva el ánimo de cualquier reunión con su perspectiva amplia y su fe en la "
        "capacidad humana de comprenderlo todo. Aprende viajando, explorando, leyendo sin rumbo fijo, "
        "confiando en que el universo le proporcionará exactamente el conocimiento que necesita en el "
        "momento justo. Su palabra es libre, sincera, generosa. La sombra de Mercurio en Sagitario es "
        "la dogmática disfrazada de apertura: proclama la libertad de pensamiento pero se aferra a sus "
        "propias certezas con la rigidez de quien confunde fe con conocimiento. Mercurio en Sagitario "
        "crece cuando aprende que la verdad no está solo en el horizonte, sino también en el camino "
        "que recorre para llegar hasta él."
    ),
    "mercurio_en_capricornio": (
        "Mercurio en Capricornio no piensa: construye. La mente capricorniana es un arquitecto que "
        "diseña estructuras conceptuales con la misma paciencia con que otros levantan edificios: "
        "ladrillo a ladrillo, asegurándose de que cada Idea apoye a la siguiente, de que el conjunto "
        "sea sólido, útil, defendible. Esta persona no habla por hablar; cuando abre la boca es porque "
        "tiene algo que decir, y lo que dice suele estar respaldado por horas de reflexión, por datos "
        "contrastados, por una autoridad que no necesita ser declarada porque se nota en el peso de "
        "sus palabras. La imagen que proyecta es la de alguien serio, competente, dueño de una "
        "inteligencia práctica que sabe separar el grano de la paja con una eficiencia casi ofensiva. "
        "Pero el conflicto que habita bajo esa coraza de solvencia es el miedo al error. Mercurio en "
        "Capricornio no se permite el lujo de probar ideas en público antes de tenerlas maduras, "
        "porque para él equivocarse es humillante, una muestra de incompetencia que empaña la imagen "
        "de solidez que tanto le ha costado construir. Esa autocensura preventiva limita su creatividad "
        "y lo condena a un pensamiento que avanza con pasos seguros pero lentos, siempre por el camino "
        "conocido. En su expresión más luminosa, Mercurio en Capricornio es un estratega nato, alguien "
        "capaz de planificar a largo plazo con una claridad pasmosa y de comunicar ideas complejas con "
        "una economía de palabras que impone respeto. Su aprendizaje es metódico, acumulativo, y rara "
        "vez olvida lo que ha aprendido porque cada conocimiento nuevo se integra en una estructura "
        "que ya tenía preparada para recibirlo. Escribe con concisión, habla con autoridad, piensa "
        "con responsabilidad. La sombra de Mercurio en Capricornio es el pesimismo intelectual: la "
        "tendencia a ver primero los obstáculos, a descartar ideas por impracticables antes de "
        "explorarlas, y a comunicarse con una sequedad que los demás interpretan como frialdad. "
        "Mercurio en Capricornio se completa cuando descubre que la verdadera inteligencia no solo "
        "construye muros, sino también puentes."
    ),
    "mercurio_en_acuario": (
        "Mercurio en Acuario piensa como un circuito que nunca se cierra: cada idea conecta con otra, "
        "y esa con otra, en una red que se expande sin centro fijo. La mente acuariana es radicalmente "
        "original, no porque intente serlo sino porque no sabe pensar de otra manera. Esta persona "
        "mira la realidad desde un ángulo que nadie más está mirando, y llega a conclusiones que "
        "parecen extraídas de otro siglo porque, a menudo, lo están. La imagen que proyecta es la de "
        "alguien brillante, excéntrico, dueño de una inteligencia que fascina tanto como desconcierta. "
        "Habla de tecnología, de utopías, de ciencia y de futuros posibles con una naturalidad que "
        "hace que todo lo demás parezca trivial. Pero el conflicto que recorre su pensamiento como "
        "una corriente subterránea es el desapego emocional: Mercurio en Acuario puede analizar las "
        "situaciones más humanas con una frialdad que hiere, no porque quiera herir sino porque "
        "concibe las ideas como objetos independientes de las personas que las sostienen. Le cuesta "
        "entender por qué alguien se ofende ante una crítica lógica si la crítica es cierta, y esa "
        "ceguera emocional le juega malas pasadas en las relaciones cercanas. Además, su amor por la "
        "controversia lo lleva a defender posturas incómodas solo por el placer de sacudir el árbol "
        "de las certezas establecidas. En su expresión más positiva, Mercurio en Acuario es un genio "
        "visionario: alguien que ve patrones donde otros ven caos, que inventa soluciones que nadie "
        "pidió pero que todos terminan necesitando, y que comunica sus ideas con una claridad "
        "revolucionaria que sacude conciencias. Aprende mejor cuando el conocimiento desafía lo "
        "establecido, cuando puede discutirlo en grupo, cuando siente que está participando en la "
        "construcción de un futuro mejor. Escribe con estilo propio, habla con convicción, piensa "
        "sin ataduras. La sombra de Mercurio en Acuario es la desconexión: la tendencia a "
        "intelectualizar la vida hasta perder de vista que las ideas existen para servir a las "
        "personas, no al revés. Mercurio en Acuario se humaniza cuando recuerda que la mente más "
        "brillante es inútil si no puede tender un puente hacia el corazón de los demás."
    ),
    "mercurio_en_piscis": (
        "Mercurio en Piscis no piensa: sueña. La mente pisciana es un océano donde las ideas flotan "
        "como medusas: luminosas, esquivas, imposibles de atrapar del todo. Esta persona no procesa "
        "la información de manera lineal sino en imágenes, en símbolos, en corazonadas que llegan sin "
        "aviso y se disuelven si intenta fijarlas con demasiada fuerza. La imagen que proyecta es la "
        "de alguien sensible, poético, dueño de una imaginación desbordante que convierte cualquier "
        "conversación en un viaje por territorios inesperados. Habla con suavidad, con metáforas, con "
        "una cualidad hipnótica que atrapa a quien lo escucha. Pero el conflicto que habita en las "
        "profundidades de esa mente es la confusión: Mercurio en Piscis tiene dificultad para separar "
        "lo que imagina de lo que realmente ocurre, lo que siente de lo que piensa, lo que le contaron "
        "de lo que inventó. Esa permeabilidad de los límites lo convierte en un receptor exquisito de "
        "las corrientes emocionales ajenas, pero también en alguien que a menudo no sabe qué piensa "
        "realmente porque hay demasiadas voces sonando al mismo tiempo dentro de su cabeza. En su "
        "expresión más luminosa, Mercurio en Piscis produce una inteligencia que no es analítica sino "
        "sintética: capta la totalidad de un fenómeno sin necesidad de descomponerlo, intuye "
        "respuestas sin saber cómo llegó a ellas y crea arte, poesía, música, con una fluidez que "
        "parece canalizar algo más grande que su propia inteligencia. Aprende mejor cuando puede "
        "sumergirse en el conocimiento sin presiones, cuando se le permite divagar, cuando la "
        "creatividad es parte del método. Su comunicación, en el mejor de los casos, toca el alma "
        "porque no viene solo de la cabeza sino de un lugar más profundo. La sombra de Mercurio en "
        "Piscis es la evasión: usar la imaginación para escapar de la realidad en lugar de "
        "transformarla, refugiarse en la vaguedad cuando la claridad exige un compromiso que no está "
        "dispuesto a asumir, y confundir la profundidad espiritual con la simple falta de estructura. "
        "Mercurio en Piscis se realiza cuando aprende que el océano también tiene corrientes que "
        "llevan a algún sitio, y que la imaginación más poderosa es la que construye mundos, no la "
        "que solo los sueña."
    ),
}

for key, new_text in entries.items():
    pattern = r'("' + re.escape(key) + r'"\s*:\s*").*?(",\s*)'
    replacement = r'\1' + new_text + r'\2'
    raw = re.sub(pattern, replacement, raw, count=1, flags=re.DOTALL)

with open("datos/planetas_signos.json", "w", encoding="utf-8") as f:
    f.write(raw)

import json
data2 = json.loads(raw)
print("=== Character counts for mercurio entries ===")
for key in sorted(entries.keys()):
    if key in data2:
        print(f"{key}: {len(data2[key])} chars")
