#!/usr/bin/env python3

import json
import re

SIGNS = ["aries", "tauro", "geminis", "cancer", "leo", "virgo", "libra", "escorpio", "sagitario", "capricornio", "acuario", "piscis"]

entries = {}

# --- CASA 11 EN ARIES ---
entries["casa_11_aries"] = """Casa 11 en Aries

Quienes tienen la Casa 11 en Aries abordan las amistades y los grupos con la misma energia impulsiva y pionera que caracteriza a este signo de fuego. No esperan a que otros tomen la iniciativa: son ellos quienes organizan la reunion, quienes proponen el plan y quienes movilizan al grupo hacia una meta comun. En el ambito de las amistades, estas personas buscan companeros que esten a su altura, que puedan seguir su ritmo y que no tengan miedo de enfrentar desafios. Su circulo social tiende a estar compuesto por personas independientes, emprendedoras y con iniciativa propia. Los grupos y organizaciones donde participan suelen ser aquellos donde pueden liderar, donde hay espacio para la competencia saludable y donde las metas se persiguen con determinacion.

La imagen que proyectan en el ambito social es la de lideres naturales que no temen tomar la iniciativa. En los grupos, son quienes rompen el hielo, quienes proponen el primer paso y quienes inyectan entusiasmo en los proyectos colectivos. Sin embargo, detras de esta fachada de seguridad hay una impaciencia que puede manifestarse como competencia excesiva. La necesidad de ser los primeros, de destacar incluso dentro del grupo, puede generar tensiones con aquellos que prefieren un enfoque mas colaborativo.

El conflicto interno de esta posicion es la dificultad para equilibrar la individualidad con la pertenencia al grupo. Los nativos de Casa 11 en Aries quieren ser parte del colectivo pero al mismo tiempo necesitan destacar y afirmar su independencia. Esta tension puede llevarlos a actuar de manera impulsiva dentro de los grupos, a tomar decisiones sin consultar o a imponer su vision sin considerar las necesidades del conjunto. La leccion mas importante que deben aprender es que el verdadero liderazgo no consiste en imponer sino en inspirar, y que la fuerza del grupo reside en la diversidad de sus miembros.

En su expresion mas positiva, quienes tienen esta posicion son los fundadores de proyectos colectivos, los iniciadores de movimientos y quienes tienen el coraje de perseguir sus suenos con determinacion. Su capacidad de movilizar a otros y de tomar la iniciativa en causas grupales es un don que, bien canalizado, puede generar cambios significativos en su comunidad. La sombra a trabajar es el egoismo en las amistades y la tendencia a competir con aquellos que deberian ser aliados, confundiendo la afirmacion personal con la necesidad de estar siempre por encima de los demas."""

# --- CASA 11 EN TAURO ---
entries["casa_11_tauro"] = """Casa 11 en Tauro

Quienes tienen la Casa 11 en Tauro construyen sus amistades con la misma paciencia y lealtad con que la tierra construye sus montanas. Para ellos, la amistad no es un juego superficial sino un compromiso solido que perdura a traves del tiempo. No hacen amigos con facilidad ni rapidez, pero cuando alguien logra entrar en su circulo de confianza, encuentra un companero leal, constante y generoso que estara presente en las buenas y en las malas. En los grupos, los nativos de esta posicion son la fuerza estabilizadora que mantiene la cohesion cuando otros van y vienen. Valoran la tradicion dentro de los grupos y prefieren pertenecer a circulos consolidados donde las relaciones tienen historia y profundidad.

La imagen que proyectan en el ambito social es de solidez y confiabilidad. Son aquellos amigos que siempre responden, que no desaparecen cuando las cosas se complican y que ofrecen un hombro estable en momentos de crisis. Sin embargo, detras de esta fachada de estabilidad hay una resistencia al cambio que puede manifestarse como posesividad con las amistades. La necesidad de mantener el grupo intacto, de aferrarse a relaciones que ya no funcionan, puede generar estancamiento y dificultad para abrir espacio a nuevas personas en su vida social.

El conflicto interno de esta posicion es la tension entre el apego a lo conocido y la necesidad de evolucion social. Los nativos de Casa 11 en Tauro pueden aferrarse a amistades toxicas o a grupos que ya no representan sus intereses simplemente por la dificultad de soltar lo familiar. Su deseo de estabilidad social puede convertirse en rigidez, y su lealtad incondicional puede ser malinterpretada como control o dependencia. La leccion mas importante que deben aprender es que la verdadera amistad no necesita posesividad, y que abrir espacio a nuevas personas no significa traicionar a las antiguas.

En su expresion mas positiva, quienes tienen esta posicion son el pilar de sus grupos de amistad, quienes sostienen las relaciones con su lealtad inquebrantable y su presencia constante. Su capacidad de construir vinculos duraderos y de mantener viva la llama de las amistades a traves de los anos es un don valioso en un mundo donde las conexiones suelen ser efimeras. La sombra a trabajar es la posesividad con las amistades y la resistencia a integrar nuevas personas en su circulo social, que puede limitar su crecimiento y mantenerlos atrapados en dinamicas que ya no les sirven."""

# --- CASA 11 EN GEMINIS ---
entries["casa_11_geminis"] = """Casa 11 en Geminis

Quienes tienen la Casa 11 en Geminis navegan el mundo de las amistades y los grupos con la versatilidad y la curiosidad intelectual que caracteriza a este signo de aire. Su circulo social es amplio, diverso y cambiante, compuesto por personas de todos los ambitos y con los intereses mas variados. No les resulta dificil entablar conversacion con desconocidos, y su capacidad de adaptacion les permite sentirse comodos en cualquier grupo, desde circulos academicos hasta comunidades artisticas o colectivos activistas. Para ellos, la amistad es ante todo un intercambio de ideas, una oportunidad de aprender algo nuevo y de compartir informacion que enriquece mutualmente.

La imagen que proyectan en el ambito social es de personas sociables, ingeniosas y entretenidas. Son quienes animan las conversaciones grupales, quienes conectan a personas de diferentes circulos y quienes traen noticias frescas a cada reunion. Sin embargo, detras de esta fachada de facilidad social hay una dispersion que puede manifestarse como superficialidad en las relaciones. La tendencia a tener muchos conocidos pero pocos amigos verdaderos, a cambiar de grupo constantemente sin establecer raices profundas, puede generar una sensacion de vacio en medio de una vida social activa.

El conflicto interno de esta posicion es la dificultad para comprometerse con un grupo o con una amistad de manera profunda y sostenida. Los nativos de Casa 11 en Geminis pueden aburrirse facilmente de las dinamicas grupales repetitivas, sentirse atraidos por nuevos circulos constantemente y tener problemas para mantener el interes en proyectos colectivos a largo plazo. Su mente inquieta busca estimulo constante, y esta busqueda puede impedirles experimentar la satisfaccion que viene de la pertenencia prolongada. La leccion mas importante que deben aprender es que la profundidad en las relaciones requiere tiempo y consistencia.

En su expresion mas positiva, quienes tienen esta posicion son el nexo de conexion entre diferentes grupos y comunidades. Su capacidad de comunicar, de tender puentes y de integrar perspectivas diversas las convierte en agentes de union dentro del tejido social. Son quienes facilitan el intercambio de ideas y quienes mantienen viva la comunicacion dentro de los colectivos. La sombra a trabajar es la inconsistencia en las amistades y la tendencia a priorizar la cantidad sobre la calidad en sus vinculos sociales, confundiendo la sociabilidad con la verdadera conexion humana."""

# --- CASA 11 EN CANCER ---
entries["casa_11_cancer"] = """Casa 11 en Cancer

Quienes tienen la Casa 11 en Cancer llevan la sensibilidad emocional y la necesidad de proteccion al ambito de las amistades, los grupos y los suenos colectivos. Para ellos, los amigos son una extension de la familia, y los grupos que integran se convierten en circulos donde buscan pertenencia, cuidado y contencion emocional. No les interesa la amistad superficial ni los grupos puramente funcionales: necesitan sentir que hay un vinculo genuino, que hay cuidado mutuo y que pueden contar con los demas en momentos de vulnerabilidad. Los proyectos colectivos que los convocan suelen tener un componente humano o de proteccion: grupos de apoyo, comunidades de cuidado, organizaciones que trabajan por el bienestar de otros.

La imagen que proyectan en el ambito social es de personas cálidas, receptivas y maternales que cuidan de quienes las rodean. Son quienes recuerdan los cumpleanos, quienes ofrecen su casa para las reuniones y quienes se preocupan genuinamente cuando alguien del grupo esta pasando por un mal momento. Sin embargo, detras de esta fachada de cuidado hay una dependencia emocional que puede manifestarse como posesividad con los amigos. La necesidad de sentirse necesitados, de ser el centro afectivo del grupo, puede generar dinamicas de codependencia que agotan a quienes las rodean.

El conflicto interno de esta posicion es la dificultad para separar las necesidades emocionales personales de las dinamicas del grupo. Los nativos de Casa 11 en Cancer pueden llevar sus inseguridades al ambito grupal, buscando en las amistades la seguridad emocional que no encuentran en si mismos. Su sensibilidad los hace vulnerables a sentirse excluidos o rechazados, y pueden reaccionar con retraimiento o con aferramiento cuando perciben amenazas a su pertenencia. La leccion mas importante que deben aprender es que las amistades saludables se basan en la interdependencia, no en la dependencia, y que su valor no depende de cuan necesitados sean por los demas.

En su expresion mas positiva, quienes tienen esta posicion son el corazon emocional de sus grupos de amistad. Crean espacios seguros donde todos pueden ser vulnerables, y su capacidad de cuidar y nutrir los vinculos fortalece la cohesion del grupo. Su intuicion emocional les permite detectar cuando alguien necesita apoyo, y su generosidad afectiva crea lazos profundos que perduran. La sombra a trabajar es la tendencia a usar las amistades como sustituto de la seguridad emocional que deberian encontrar dentro de si mismos, y la manipulacion emocional sutil que puede surgir del miedo a ser abandonados."""

# --- CASA 11 EN LEO ---
entries["casa_11_leo"] = """Casa 11 en Leo

Quienes tienen la Casa 11 en Leo llevan su brillo y su generosidad al ambito de las amistades, los grupos y los proyectos colectivos. Para ellos, los amigos son una audiencia que celebra sus logros y una comunidad a la que pueden inspirar con su entusiasmo y su creatividad. En los grupos, los nativos de esta posicion tienden a ocupar el centro de atencion de manera natural, no por egocentrismo sino porque su presencia ilumina cualquier reunion. Les gusta organizar actividades grupales, celebrar los logros del colectivo y asegurarse de que todos se diviertan y se sientan incluidos. Los proyectos que los apasionan son aquellos donde pueden expresar su creatividad y recibir reconocimiento por su contribucion.

La imagen que proyectan en el ambito social es de lideres carismaticos que infunden entusiasmo y vitalidad a cualquier grupo. Son quienes motivan a los demas, quienes celebran cada avance con generosidad y quienes transforman cualquier reunion en una fiesta. Sin embargo, detras de esta fachada de generosidad hay una necesidad de validacion que puede manifestarse como egocentrismo dentro del grupo. La necesidad de ser reconocidos, de ocupar un lugar especial en el circulo, puede generar conflictos cuando otros tambien buscan atencion o cuando el grupo no les proporciona el reconocimiento que esperan.

El conflicto interno de esta posicion es la tension entre el deseo de brillar y la necesidad de integrarse como uno mas dentro del colectivo. Los nativos de Casa 11 en Leo quieren ser parte del grupo pero al mismo tiempo necesitan destacar, y esta contradiccion puede generar dinamicas complejas. Pueden sentirse heridos cuando no reciben la atencion que esperan, o pueden retirarse de grupos donde sienten que su luz no es apreciada. La leccion mas importante que deben aprender es que el verdadero liderazgo no consiste en ser el centro sino en servir al colectivo desde el corazon, y que el reconocimiento genuino llega cuando no se busca obsesivamente.

En su expresion mas positiva, quienes tienen esta posicion son el corazon creativo de los grupos y las organizaciones. Su capacidad de inspirar, de elevar el animo colectivo y de celebrar los logros compartidos es un don que enriquece cualquier comunidad. Son quienes recuerdan que los proyectos tambien son espacios de alegria y expresion. La sombra a trabajar es la necesidad excesiva de reconocimiento que puede nublar su juicio y generar conflictos en los grupos, y la tendencia a retirar su energia cuando no se sienten suficientemente apreciados, debilitando asi los mismos vinculos que dicen valorar."""

# --- CASA 11 EN VIRGO ---
entries["casa_11_virgo"] = """Casa 11 en Virgo

Quienes tienen la Casa 11 en Virgo abordan las amistades, los grupos y los proyectos colectivos con un sentido de servicio, analisis y busqueda de mejora continua. Para ellos, las amistades no son solo espacios de ocio sino relaciones donde pueden ser utiles, donde pueden contribuir al bienestar del otro y donde el intercambio tiene un proposito concreto. En los grupos, los nativos de esta posicion son quienes se encargan de la logistica, quienes aseguran que todo funcione correctamente y quienes ofrecen habilidades practicas que mantienen el colectivo operativo. Prefieren grupos organizados, con estructuras claras y metas definidas, y se sienten frustrados en ambientes caoticos o desorganizados.

La imagen que proyectan en el ambito social es de personas responsables, eficientes y serviciales que siempre estan dispuestas a ayudar. Son quienes llegan temprano a las reuniones para preparar el espacio, quienes llevan las cuentas del grupo y quienes se aseguran de que nadie olvide los compromisos adquiridos. Sin embargo, detras de esta fachada de utilidad hay una critica interna que puede manifestarse como juicio hacia los miembros del grupo que no cumplen con sus estandares. Su tendencia a senalar fallos, a corregir y a optimizar constantemente puede resultar agotadora para quienes prefieren un ambiente grupal mas relajado.

El conflicto interno de esta posicion es la dificultad para relajarse dentro de las dinamicas grupales y aceptar la imperfeccion de los demas. Los nativos de Casa 11 en Virgo pueden volverse tan exigentes con sus amigos y con los grupos que integran que terminan alejando a las personas. Su critica, aunque bien intencionada, puede percibirse como desaprobacion, y su deseo de mejorar puede interpretarse como falta de aceptacion. La leccion mas importante que deben aprender es que las amistades y los grupos no necesitan ser perfectos para ser valiosos, y que la calidez de la conexion humana es mas importante que la eficiencia operativa.

En su expresion mas positiva, quienes tienen esta posicion son el soporte practico de los grupos y las organizaciones. Su capacidad de organizar, planificar y ejecutar tareas con precision es invaluable para cualquier proyecto colectivo. Son quienes transforman las visiones en realidades concretas, quienes se aseguran de que los detalles no se pasen por alto y quienes mantienen el grupo funcionando con eficiencia. La sombra a trabajar es la tendencia a juzgar a los amigos y companeros de grupo por no cumplir con sus estandares, y la dificultad para valorar las contribuciones que no se ajustan a su definicion de utilidad."""

# --- CASA 11 EN LIBRA ---
entries["casa_11_libra"] = """Casa 11 en Libra

Quienes tienen la Casa 11 en Libra buscan la armonia, el equilibrio y la belleza en sus amistades, en los grupos que integran y en los ideales que persiguen. Para ellos, las relaciones de amistad deben ser equilibradas, justas y esteticamente placenteras. Tienden a rodearse de personas con buen gusto, con sensibilidad social y con capacidad de mantener relaciones armoniosas. En los grupos, los nativos de esta posicion son los diplomaticos, quienes buscan consenso, quienes suavizan las tensiones y quienes aseguran que todos tengan voz. Los proyectos colectivos que los convocan suelen estar relacionados con la justicia social, la estetica, el arte o la mediacion de conflictos.

La imagen que proyectan en el ambito social es de personas encantadoras, diplomaticas y socialmente habilidosas que saben moverse con gracia en cualquier circulo. Son quienes presentan a las personas adecuadas, quienes equilibran las dinamicas del grupo y quienes crean un ambiente agradable donde todos se sienten bienvenidos. Sin embargo, detras de esta fachada de armonia hay una indecision que puede manifestarse como incapacidad para tomar partido en conflictos grupales. Su deseo de agradar a todos puede llevarlos a evitar posiciones firmes, incluso cuando la situacion requiere claridad y compromiso.

El conflicto interno de esta posicion es la tension entre el deseo de armonia y la necesidad de autenticidad en las relaciones grupales. Los nativos de Casa 11 en Libra pueden sacrificar sus propias opiniones y necesidades en pos de mantener la paz dentro del grupo, acumulando resentimiento que tarde o temprano emerge. Su aversion al conflicto puede impedirles abordar problemas reales que afectan la salud del colectivo. La leccion mas importante que deben aprender es que la verdadera armonia no es la ausencia de conflicto sino la capacidad de atravesarlo con respeto y honestidad.

En su expresion mas positiva, quienes tienen esta posicion son los constructores de puentes dentro de los grupos y las comunidades. Su capacidad de ver multiples perspectivas, de encontrar puntos de encuentro y de facilitar la comunicacion entre personas diversas es invaluable para cualquier colectivo. Son quienes recuerdan al grupo la importancia de la justicia, la equidad y la belleza en los proyectos compartidos. La sombra a trabajar es la tendencia a la superficialidad en las relaciones grupales por evitar roces, y la dependencia de la validacion social que puede llevarlos a comprometer sus principios para mantener la aceptacion del grupo."""

# --- CASA 11 EN ESCORPIO ---
entries["casa_11_escorpio"] = """Casa 11 en Escorpio

Quienes tienen la Casa 11 en Escorpio llevan la intensidad, la profundidad y la pasion al ambito de las amistades, los grupos y los proyectos colectivos. Para ellos, las amistades no pueden ser superficiales: buscan conexiones que transformen, vinculos que desafien y relaciones que penetren mas alla de las apariencias. En los grupos, los nativos de esta posicion son una presencia poderosa que puede resultar intimidante. No participan en grupos por entretenimiento: necesitan sentir que la causa es significativa, que hay profundidad en los vinculos y que el grupo esta comprometido con una transformacion genuina. Los proyectos que los convocan suelen estar relacionados con temas tabu, crisis sociales, investigacion profunda o procesos de regeneracion colectiva.

La imagen que proyectan en el ambito social es de personas intensas, magneticas y misteriosas que no revelan todo de si mismas. En los grupos, son quienes hacen las preguntas incomodas, quienes senalan lo que otros prefieren ignorar y quienes llevan al colectivo a enfrentar sus sombras. Sin embargo, detras de esta fachada de poder hay una desconfianza que puede manifestarse como control dentro del grupo. Su miedo a la traicion y su necesidad de conocer las verdades ocultas pueden llevarlos a manipular informacion o a establecer alianzas estrategicas que fraccionan el colectivo.

El conflicto interno de esta posicion es la tension entre el deseo de pertenencia y la desconfianza hacia el grupo. Los nativos de Casa 11 en Escorpio anhelan conexiones profundas y significativas, pero al mismo tiempo temen ser traicionados o manipulados. Esta desconfianza puede llevarlos a probar la lealtad de los demas, a guardar secretos que podrian compartirse y a mantener un control rigido sobre la informacion dentro del grupo. La leccion mas importante que deben aprender es que la confianza es un riesgo necesario para la verdadera conexion, y que el poder compartido es mas fuerte que el poder acumulado.

En su expresion mas positiva, quienes tienen esta posicion son los agentes de transformacion dentro de los grupos y las comunidades. Su capacidad de ver mas alla de las apariencias, de enfrentar las verdades incomodas y de catalizar cambios profundos es un don que puede llevar al colectivo a niveles de autenticidad y poder que otros grupos no alcanzan. Son quienes sostienen al grupo en momentos de crisis y quienes tienen el coraje de iniciar las conversaciones que nadie mas quiere tener. La sombra a trabajar es la tendencia al control y al secretismo dentro de los grupos, y la dificultad para confiar genuinamente en los demas, que puede socavar la misma comunidad que buscan construir."""

# --- CASA 11 EN SAGITARIO ---
entries["casa_11_sagitario"] = """Casa 11 en Sagitario

Quienes tienen la Casa 11 en Sagitario llevan su optimismo, su amor por la libertad y su busqueda de significado al ambito de las amistades, los grupos y los proyectos colectivos. Para ellos, los amigos son companeros de aventura, personas con quienes explorar el mundo, debatir ideas y expandir horizontes. No les interesan las amistades que los limitan ni los grupos que imponen dogmas. Buscan circulos sociales donde haya libertad de expresion, donde se valore la diversidad de perspectivas y donde el horizonte sea siempre mas amplio que el presente. Los proyectos colectivos que los apasionan suelen tener una dimension internacional, educativa, filosofica o de exploracion.

La imagen que proyectan en el ambito social es de personas entusiastas, inspiradoras y generosas que contagian su amor por la vida a quienes las rodean. Son quienes proponen viajes grupales, quienes organizan eventos culturales y quienes motivan al grupo a mirar mas alla de las limitaciones inmediatas. Sin embargo, detras de esta fachada de optimismo hay una impaciencia que puede manifestarse como falta de compromiso con los grupos. Su amor por la libertad puede llevarlos a evitar las responsabilidades que implica la pertenencia sostenida, y su entusiasmo inicial por un proyecto puede apagarse cuando la rutina y los detalles concretos reclaman atencion.

El conflicto interno de esta posicion es la tension entre el deseo de pertenencia y la necesidad de independencia. Los nativos de Casa 11 en Sagitario quieren ser parte de algo mas grande que ellos mismos, pero al mismo tiempo temen que el grupo los atrape, que las expectativas colectivas limiten su libertad de exploracion. Esta contradiccion puede llevarlos a participar en multiples grupos sin comprometerse profundamente con ninguno, o a abandonar proyectos justo cuando mas se necesita su presencia. La leccion mas importante que deben aprender es que la verdadera libertad incluye la capacidad de comprometerse sin sentirse atrapado, y que la pertenencia a un grupo no limita el crecimiento sino que lo potencia.

En su expresion mas positiva, quienes tienen esta posicion son la inspiracion y la vision de futuro dentro de los grupos y las organizaciones. Su capacidad de ver las posibilidades, de elevar la mirada del colectivo hacia horizontes mas amplios y de infundir esperanza en los proyectos compartidos es un don invaluable. Son quienes recuerdan al grupo que hay un proposito mas alla de las tareas inmediatas. La sombra a trabajar es la evasion del compromiso grupal y la tendencia a abandonar proyectos cuando pierden el entusiasmo inicial, dejando a otros la responsabilidad de sostener lo que ellos ayudaron a iniciar."""

# --- CASA 11 EN CAPRICORNIO ---
entries["casa_11_capricornio"] = """Casa 11 en Capricornio

Quienes tienen la Casa 11 en Capricornio abordan las amistades, los grupos y los proyectos colectivos con seriedad, responsabilidad y una vision estrategica a largo plazo. Para ellos, las amistades no son solo espacios de ocio sino relaciones que deben tener solidez, proposito y madurez. No se rodean de muchas personas, pero las pocas amistades que cultivan son profundas, leales y duraderas. En los grupos, los nativos de esta posicion son quienes asumen responsabilidades, quienes aseguran la continuidad del proyecto y quienes mantienen el rumbo cuando otros pierden el foco. Prefieren grupos organizados, con jerarquias claras y metas alcanzables, y aportan disciplina y estructura a los proyectos colectivos.

La imagen que proyectan en el ambito social es de personas serias, confiables y maduras que inspiran respeto en los grupos. Son quienes terminan ocupando posiciones de liderazgo natural porque los demas reconocen su capacidad de gestion y su compromiso con las metas del colectivo. Sin embargo, detras de esta fachada de responsabilidad hay una rigidez que puede manifestarse como autoritarismo en los grupos. Su sentido del deber puede volverse exigencia, y su enfoque en los resultados puede descuidar el aspecto humano y emocional de las relaciones grupales.

El conflicto interno de esta posicion es la tension entre la ambicion personal y el servicio al colectivo. Los nativos de Casa 11 en Capricornio pueden usar los grupos y las redes sociales como trampolin para sus metas individuales, priorizando su avance personal sobre el bienestar del colectivo. Su tendencia a tomar el control, a imponer estructuras y a medir el exito del grupo en terminos de logros externos puede generar conflictos con quienes valoran procesos mas horizontales o ludicos. La leccion mas importante que deben aprender es que el verdadero liderazgo sirve al grupo, no se sirve del grupo, y que el exito colectivo no se mide solo en metas alcanzadas sino en la calidad de los vinculos construidos.

En su expresion mas positiva, quienes tienen esta posicion son la columna vertebral de los grupos y las organizaciones. Su capacidad de planificar a largo plazo, de mantener la disciplina y de asegurar que los proyectos lleguen a buen puerto es invaluable para cualquier colectivo. Son quienes construyen instituciones solidas y quienes garantizan que el trabajo del grupo tenga un impacto duradero. La sombra a trabajar es la tendencia a priorizar la ambicion personal sobre el bienestar del grupo, y la rigidez que puede sofocar la creatividad y la espontaneidad que los proyectos colectivos tambien necesitan."""

# --- CASA 11 EN ACUARIO ---
entries["casa_11_acuario"] = """Casa 11 en Acuario

Quienes tienen la Casa 11 en Acuario son los nativos mas naturales de esta casa, ya que Acuario rige por afinidad el ambito de las amistades, los grupos, los ideales colectivos y la proyeccion social. La Casa 11 es el territorio del cielo donde las aspiraciones individuales se encuentran con las necesidades de la comunidad, y quienes tienen esta posicion en Acuario viven esta interseccion con una intensidad particular. Para ellos, las amistades no son vinculos personales en el sentido tradicional sino conexiones basadas en ideales compartidos, en intereses intelectuales comunes y en una vision compartida del futuro. Su circulo social es diverso, incluyente y a menudo poco convencional, compuesto por personas que quizas no encajan en los moldes tradicionales pero que comparten su compromiso con causas progresistas.

La imagen que proyectan en el ambito social es de personas originales, idealistas y comprometidas con el bien comun. En los grupos, son quienes proponen las ideas mas innovadoras, quienes cuestionan las estructuras establecidas y quienes abogan por la inclusion y la diversidad. Sin embargo, detras de esta fachada de compromiso colectivo hay una desconexion emocional que puede manifestarse como distancia en las relaciones personales. Su tendencia a priorizar el ideal sobre la persona, la causa sobre el vinculo individual, puede dejar a quienes los rodean sintiendose mas como parte de un proyecto que como amigos valorados por si mismos.

El conflicto interno de esta posicion es la tension entre la pertenencia al colectivo y la necesidad de individualidad. Los nativos de Casa 11 en Acuario quieren cambiar el mundo, pertenecer a movimientos y conectar con personas afines, pero al mismo tiempo necesitan preservar su libertad individual y su originalidad a toda costa. Esta contradiccion puede llevarlos a participar en grupos desde una posicion de distancia, como observadores mas que como miembros plenos, o a abandonar colectivos cuando sienten que su individualidad se ve comprometida. La leccion mas importante que deben aprender es que la verdadera conexion grupal no anula la individualidad sino que la potencia, y que el compromiso emocional con las personas es tan importante como el compromiso ideologico con las causas.

En su expresion mas positiva, quienes tienen esta posicion son los visionarios y los agentes de cambio dentro de los grupos y las comunidades. Su capacidad de imaginar un futuro mejor, de organizar colectivos en torno a ideales elevados y de conectar a personas diversas en pos de un bien comun es verdaderamente extraordinaria. Son quienes construyen redes, quienes siembran las semillas del cambio social y quienes recuerdan al mundo que otro futuro es posible. La sombra a trabajar es la frialdad emocional en las relaciones grupales y la tendencia a idealizar tanto las causas que pierden de vista a las personas concretas que las sostienen."""

# --- CASA 11 EN PISCIS ---
entries["casa_11_piscis"] = """Casa 11 en Piscis

Quienes tienen la Casa 11 en Piscis llevan su sensibilidad, su compasion y su conexion con lo trascendente al ambito de las amistades, los grupos y los suenos colectivos. Para ellos, las amistades son conexiones del alma, vinculos que trascienden lo racional y que se sienten en un nivel sutil de comprension mutua. No eligen a sus amigos basandose en intereses logicos o metas compartidas sino en una resonancia intuitiva, en una sensacion de reconocimiento que va mas alla de las palabras. En los grupos, los nativos de esta posicion son la presencia compasiva que percibe cuando alguien necesita apoyo, que ofrece consuelo sin juzgar y que mantiene la cohesion del grupo a traves de la empatia. Los proyectos que los convocan suelen tener un componente humanitario, artistico o espiritual.

La imagen que proyectan en el ambito social es de personas compasivas, comprensivas y espiritualmente sintonizadas que irradian una calma que invita a la confianza. En los grupos, son quienes disipan las tensiones con su presencia, quienes ofrecen una perspectiva mas alla del conflicto inmediato y quienes conectan al colectivo con un sentido de proposito trascendente. Sin embargo, detras de esta fachada de compasion hay una evasion que puede manifestarse como falta de limites en las relaciones grupales. Su tendencia a absorber las emociones del grupo, a disolverse en el colectivo y a sacrificar su propia identidad por mantener la paz puede llevarlas al agotamiento y a la perdida de si mismas dentro de la dinamica grupal.

El conflicto interno de esta posicion es la dificultad para mantener la individualidad dentro del grupo y para establecer limites saludables en las amistades. Los nativos de Casa 11 en Piscis pueden perderse en las necesidades del colectivo, confundir la compasion con el autosacrificio y tener dificultades para distinguir sus propios suenos de los suenos del grupo. Su porosidad emocional las hace vulnerables a ser influenciadas por las corrientes del colectivo, y pueden terminar viviendo las aspiraciones de otros en lugar de las propias. La leccion mas importante que deben aprender es que la verdadera compasion incluye la compasion por uno mismo, y que pertenecer a un grupo no significa disolverse en el.

En su expresion mas positiva, quienes tienen esta posicion son el alma espiritual de los grupos y las comunidades. Su capacidad de conectar con lo trascendente, de percibir las necesidades emocionales del colectivo y de ofrecer una vision compasiva del futuro es un don que eleva cualquier proyecto grupal. Son quienes recuerdan al grupo que hay dimensiones de la experiencia humana que van mas alla de lo material y lo racional. La sombra a trabajar es la tendencia al escapismo dentro de los grupos, la idealizacion de las amistades y la dificultad para establecer limites que protejan su propia energia en el contexto de las dinamicas colectivas."""


with open("/home/pipe/Documents/proyectos/cartas_natales/datos/casas_signos.json", "r") as f:
    data = json.load(f)

# Replace existing entries (they're currently one-liners)
for key, text in entries.items():
    data[key] = text

with open("/home/pipe/Documents/proyectos/cartas_natales/datos/casas_signos.json", "w") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("=== Character counts for each entry ===")
for key in sorted(entries.keys()):
    count = len(entries[key])
    status = "OK" if count >= 1800 else "SHORT"
    print(f"{key}: {count} chars [{status}]")

print("\nDone!")
