#!/usr/bin/env python3
import json
import os

SIGNS = ["aries", "tauro", "geminis", "cancer", "leo", "virgo", "libra", "escorpio", "sagitario", "capricornio", "acuario", "piscis"]

entries = {
    "casa_8_aries": (
        'Casa 8 en Aries\n'
        '\n'
        'Quienes tienen la Casa 8 en Aries se enfrentan a la transformacion con la misma energia impulsiva con la que un guerrero entra en batalla. '
        'No esperan a que la crisis llegue: la anticipan, la provocan incluso, como si prefirieran controlar el momento del impacto a ser sorprendidos por el. '
        'Los recursos compartidos son un campo de lucha donde afirman su independencia; prefieren generar lo suyo a depender de herencias o del dinero de otros, '
        'y cualquier forma de dependencia economica les resulta personalmente ofensiva. La intimidad sexual la viven con la misma intensidad directa: '
        'como una conquista, un encuentro de voluntades donde el deseo se afirma sin rodeos ni estrategias de seduccion elaboradas.\n'
        '\n'
        'La imagen que proyectan en el terreno de lo compartido es la de personas audaces que no temen enfrentar las crisis de frente. '
        'Los demas perciben en ellas una valentia que intimida, una capacidad de cortar lo que ya no sirve sin mirar atras. '
        'Sin embargo, esta fachada de fortaleza oculta una relacion tormentosa con la vulnerabilidad: '
        'entregarse en la intimidad les exige bajar las defensas, y bajar las defensas les parece una rendicion.\n'
        '\n'
        'El conflicto central de esta posicion es la lucha entre el impulso de controlar la transformacion y la necesidad de rendirse al proceso. '
        'Quienes tienen la Casa 8 en Aries quieren que la crisis se resuelva ya, en sus propios terminos, y se frustran cuando la transformacion exige paciencia. '
        'Su tendencia a forzar los procesos de cierre, a empujar los cambios antes de que esten maduros, '
        'genera un patron de rupturas abruptas y reinicios que pueden volverse ciclicos. '
        'En el ambito financiero compartido, esta impaciencia las lleva a veces a tomar decisiones precipitadas sobre herencias, inversiones conjuntas o acuerdos economicos, '
        'actuando primero y lamentando despues. Su mayor desafio es aprender que la verdadera transformacion requiere tanto de la valentia para iniciar como de la sabiduria para esperar.\n'
        '\n'
        'En su mejor expresion, los nativos con esta posicion tienen una capacidad de regeneracion que asombra: '
        'pueden perderlo todo y reconstruirse desde cero con un coraje que inspira a quienes los rodean. '
        'Su energia para enfrentar las crisis es contagiosa, y su disposicion a cortar los lazos que ya no suman las convierte en personas que no se aferran al pasado. '
        'En la intimidad, su franqueza y su pasion crean encuentros sexuales de una autenticidad poderosa, '
        'donde el deseo se expresa sin mascaras ni juegos. La sombra a trabajar es la impaciencia transformadora y la tendencia a romper antes de intentar reparar.\n'
        '\n'
        'Sombra: la impaciencia en los procesos de crisis y la tendencia a forzar cierres antes de tiempo.'
    ),
    "casa_8_tauro": (
        'Casa 8 en Tauro\n'
        '\n'
        'Quienes tienen la Casa 8 en Tauro se relacionan con la transformacion y los recursos compartidos desde la resistencia y la tenacidad. '
        'Tauro busca la estabilidad, la permanencia, y la Casa 8 es el territorio de la perdida, del cambio inevitable y de lo que se disuelve: '
        'la tension entre estas dos fuerzas define toda su experiencia en esta area de la vida. '
        'Para estas personas, compartir recursos financieros con otros no es un acto sencillo: necesitan sentir que la base material es segura antes de abrirse a la fusion economica, '
        'y cualquier situacion que implique dependencia de bienes ajenos les genera una ansiedad profunda. '
        'La herencia, las inversiones conjuntas o los acuerdos financieros con la pareja son territorios donde su necesidad de control choca con la realidad de que el dinero compartido implica confianza.\n'
        '\n'
        'La imagen que proyectan en el terreno de lo compartido es la de personas estables y confiables, '
        'anclas en medio de las tormentas financieras o emocionales de quienes las rodean. '
        'Los demas perciben en ellas una solidez que invita a la confianza, una capacidad de sostener los procesos de crisis con una paciencia que otros no tienen. '
        'Sin embargo, esta fachada de estabilidad oculta un miedo paralizante a la perdida: '
        'detras de cada decision economica compartida hay un calculo inconsciente de cuanto podrian perder.\n'
        '\n'
        'El conflicto central de esta posicion es la dificultad para soltar. '
        'Quienes tienen la Casa 8 en Tauro se aferran a las relaciones, a los bienes materiales y a las estructuras conocidas incluso cuando estas ya se han agotado, '
        'porque el vacio que deja la transformacion les parece insoportable. '
        'En el ambito sexual, la posesividad puede convertirse en un obstaculo: aman con intensidad sensorial pero tambien con un sentido de pertenencia que sofoca. '
        'Su sensualidad es profunda y su conexion con el placer fisico es un camino hacia lo sagrado, '
        'pero la confusión entre amar y poseer puede generar dinamicas de control en la intimidad que terminan por asfixiar el deseo. '
        'Aprender a soltar sin sentir que pierden su identidad es el aprendizaje central de esta posicion: '
        'la verdadera seguridad no esta en retener sino en confiar en la propia capacidad de reconstruir.\n'
        '\n'
        'En su mejor expresion, los nativos con esta posicion tienen una capacidad de transformacion lenta pero profunda, '
        'como la tierra que se moldea a lo largo de eras geologicas. '
        'Una vez que aceptan el cambio, lo integran de manera permanente, y nada ni nadie puede hacerlos volver atras. '
        'Su lealtad en las finanzas compartidas es absoluta, y su capacidad de construir riqueza conjunta con otros es notable '
        'cuando logran equilibrar su necesidad de seguridad con la confianza necesaria para compartir. '
        'En la intimidad, su conexion sensorial y su paciencia las convierte en amantes dedicados y profundamente presentes. '
        'La sombra a trabajar es la posesividad y el miedo a la perdida, que les impide fluir con los ciclos naturales de la vida.\n'
        '\n'
        'Sombra: la posesividad material y emocional, y la resistencia a soltar lo que ya no sirve.'
    ),
    "casa_8_geminis": (
        'Casa 8 en Geminis\n'
        '\n'
        'Quienes tienen la Casa 8 en Geminis abordar la transformacion, la sexualidad y los recursos compartidos desde la mente curiosa y la multiplicidad. '
        'Para ellos, la crisis no es un abismo sino un rompecabezas que resolver, un enigma que descifrar con palabras y conversaciones. '
        'Tienden a intelectualizar los procesos psicologicos profundos, a hablar sobre la muerte, el sexo y el dinero con una facilidad que desconcierta, '
        'como si estos temas tabu fueran simples datos que analizar desde una distancia segura. '
        'Los recursos compartidos los gestionan con versatilidad, a menudo diversificando inversiones y buscando informacion constante, '
        'pero su tendencia a cambiar de opinion puede generar inestabilidad en los acuerdos financieros con otros.\n'
        '\n'
        'La imagen que proyectan en la Casa 8 es la de personas que hablan con soltura de los temas prohibidos, '
        'que desmenuzan la psicologia del sexo y la muerte con una inteligencia que fascina. '
        'Los demas pueden sentirse atraidos por su capacidad de poner palabras a lo que otros apenas se atreven a pensar. '
        'Sin embargo, esta fachada de comprension intelectual oculta una evasion de la experiencia profunda: '
        'hablar de la transformacion no es lo mismo que transformarse, y analizar la intimidad no es lo mismo que entregarse a ella.\n'
        '\n'
        'El conflicto central de esta posicion es la separacion entre la mente y la experiencia vivencial. '
        'Quienes tienen la Casa 8 en Geminis pueden hablar horas sobre psicologia, sexo y dinamicas de poder, '
        'pero cuando llega el momento de entregarse a la experiencia transformadora, la mente interfiere, '
        'analiza, distrae, convierte la vivencia en teoria. '
        'En el ambito sexual, esta tendencia se manifiesta como una curiosidad que cambia constantemente de objeto de deseo, '
        'como si la intimidad fuera un libro que se lee una vez y luego se reemplaza por otro. '
        'En las finanzas compartidas, su habilidad para ver multiples opciones puede volverse indecision, '
        'y su tendencia a la dispersion puede generar acuerdos incompletos o mal comunicados. '
        'Su mayor desafio es aprender a callar la mente para poder sentir, a dejar de analizar para poder transformarse.\n'
        '\n'
        'En su mejor expresion, los nativos con esta posicion son puentes entre el conocimiento y la experiencia. '
        'Tienen el don de investigar los misterios de la vida y de compartir sus descubrimientos con una claridad que ilumina a otros. '
        'Su flexibilidad mental les permite adaptarse a las crisis con una rapidez envidiable, '
        'encontrando soluciones innovadoras donde otros solo ven callejones sin salida. '
        'En la intimidad, su capacidad de comunicar deseos y fantasias abre posibilidades de exploracion sexual que enriquecen la vida compartida. '
        'La sombra a trabajar es la evasion intelectual de la profundidad emocional, '
        'usando la mente como escudo contra la experiencia transformadora genuina.\n'
        '\n'
        'Sombra: la intelectualizacion de la experiencia profunda y la evasion de la entrega emocional genuina.'
    ),
    "casa_8_cancer": (
        'Casa 8 en Cancer\n'
        '\n'
        'Quienes tienen la Casa 8 en Cancer se relacionan con la transformacion, la sexualidad y los recursos compartidos desde un lugar profundamente emocional. '
        'Cancer es el signo de la proteccion y la seguridad, y la Casa 8 es el territorio de la crisis y la disolucion: '
        'esta combinacion crea una relacion intensamente compleja con todo lo que implica compartir, perder y renacer. '
        'Para ellos, compartir recursos economicos con otros no es solo una transaccion: es un acto cargado de significado emocional, '
        'un intercambio donde el dinero se convierte en simbolo de cuidado, de compromiso o de deuda afectiva. '
        'Las herencias y los bienes familiares tienen un peso emocional que trasciende su valor material, '
        'y las decisiones financieras compartidas estan influidas por lealtades invisibles que vienen de generaciones anteriores.\n'
        '\n'
        'La imagen que proyectan en el terreno de lo compartido es la de personas que cuidan los recursos con la misma dedicacion con que cuidarian a un ser querido. '
        'Los demas perciben en ellas una conexion emocional con el dinero que puede resultar conmovedora o agobiante. '
        'Su generosidad con quienes aman es innegable, pero detras de esa generosidad hay una necesidad de control que se disfraza de cuidado. '
        'En la intimidad, su sensualidad esta impregnada de emocion: el sexo no es solo placer fisico sino un lenguaje de entrega y proteccion.\n'
        '\n'
        'El conflicto central de esta posicion es la fluctuacion emocional alrededor de los temas de la Casa 8. '
        'Quienes tienen la Casa 8 en Cancer pueden pasar de la generosidad mas absoluta al resentimiento mas profundo '
        'cuando sienten que su confianza ha sido traicionada o que su cuidado no ha sido correspondido. '
        'Su sensibilidad las hace especialmente vulnerables en las dinamicas de poder economico dentro de las relaciones, '
        'y su tendencia a usar el dinero como expresion de amor puede generar dependencias poco saludables. '
        'En el ambito sexual, la necesidad de sentirse seguros emocionalmente para entregarse puede crear bloqueos: '
        'si no se sienten protegidos, la intimidad se cierra como una concha que se niega a abrirse. '
        'El miedo a la perdida las persigue en cada crisis, y la ansiedad de separacion puede nublar su juicio en momentos de transicion.\n'
        '\n'
        'En su mejor expresion, los nativos con esta posicion tienen una capacidad de nutrir los procesos de transformacion de otros que es profundamente sanadora. '
        'Crean espacios seguros donde las crisis pueden vivirse sin juicio, donde la vulnerabilidad es recibida con brazos abiertos. '
        'Su conexion intuitiva con las corrientes emocionales las convierte en guardianas de los secretos familiares y en sanadoras de heridas heredadas. '
        'En la intimidad, su entrega emocional y su ternura crean encuentros sexuales de una profundidad que trasciende lo puramente fisico. '
        'La sombra a trabajar es la tendencia a usar el dinero y el sexo como herramientas de control emocional.\n'
        '\n'
        'Sombra: el uso del dinero y la sexualidad como herramientas de control emocional y dependencia.'
    ),
    "casa_8_leo": (
        'Casa 8 en Leo\n'
        '\n'
        'Quienes tienen la Casa 8 en Leo se enfrentan a la transformacion y los recursos compartidos con la majestuosidad de quien convierte incluso la crisis en un espectaculo. '
        'Para ellos, el drama de la vida y la muerte es un escenario donde brillar, donde demostrar su fortaleza y su capacidad de renacer con mas fuerza que antes. '
        'Los recursos compartidos no son solo dinero: son una extension de su poder personal, un medio para expresar su generosidad '
        'y para asegurarse de que su estatus sea reconocido incluso en el terreno de lo que otros poseen o heredan. '
        'La intimidad sexual la viven con pasion teatral, como un encuentro donde el deseo se convierte en una afirmacion de su propia vitalidad y poder de atraccion, '
        'y donde necesitan ser admirados y celebrados incluso en los momentos mas privados.\n'
        '\n'
        'La imagen que proyectan en la Casa 8 es la de personas que enfrentan las crisis con una valentia que inspira, '
        'que transforman las tragedias en historias de superacion y que emergen de cada catastrofe mas brillantes que antes. '
        'Los demas las ven como lideres naturales en momentos de crisis, como quienes toman el control cuando todo parece desmoronarse. '
        'Sin embargo, detras de esta fachada de fortaleza hay una necesidad profunda de que su poder transformador sea reconocido, '
        'y una vulnerabilidad oculta: el miedo a no ser lo suficientemente especiales incluso en el terreno de la muerte y el renacimiento.\n'
        '\n'
        'El conflicto central de esta posicion es el orgullo en el corazon de la vulnerabilidad. '
        'Quienes tienen la Casa 8 en Leo quieren controlar su propia transformacion y dirigir el espectaculo de su renacimiento, '
        'pero la verdadera crisis no se controla ni se dirige: simplemente ocurre. '
        'Su necesidad de mantener la dignidad en los procesos de perdida puede impedirles pedir ayuda cuando la necesitan, '
        'y su temor a ser vistos en un momento de debilidad las lleva a veces a aislarse justo cuando mas apoyo requieren. '
        'En el ambito de los recursos compartidos, su generosidad puede ser espectacular, pero tambien puede esconder una expectativa de reciprocidad '
        'que, cuando no se cumple, genera resentimiento. En la intimidad, su pasion es ardiente '
        'pero su necesidad de ser el centro de atencion puede crear desequilibrios en la entrega sexual.\n'
        '\n'
        'En su mejor expresion, los nativos con esta posicion tienen un don para la regeneracion creativa: '
        'convierten las crisis en obras de arte, las perdidas en historias que inspiran y las muertes simbolicas en renacimientos gloriosos. '
        'Su generosidad con los recursos compartidos es legendaria cuando se sienten valorados, '
        'y su capacidad de celebrar la vida incluso en los momentos mas oscuros es un regalo para quienes las rodean. '
        'En la intimidad, su calidez y su pasion crean encuentros donde el amor y el deseo se celebran con una intensidad que pocos pueden igualar. '
        'La sombra a trabajar es la necesidad de reconocimiento en los procesos de crisis, '
        'que puede impedirles rendirse a la transformacion genuina que ocurre en el silencio y la humildad.\n'
        '\n'
        'Sombra: la necesidad de ser admirados incluso en la crisis, y el orgullo que impide pedir ayuda cuando mas se necesita.'
    ),
    "casa_8_virgo": (
        'Casa 8 en Virgo\n'
        '\n'
        'Quienes tienen la Casa 8 en Virgo se relacionan con la transformacion, la sexualidad y los recursos compartidos desde un lugar de analisis, '
        'servicio y busqueda de pureza. Virgo busca la perfeccion en los detalles, y la Casa 8 es el territorio de lo caotico, '
        'de lo que se descompone y se regenera: esta tension entre el orden y el caos atraviesa toda su experiencia en estas areas. '
        'Para ellos, los recursos compartidos son un area que requiere gestion meticulosa, '
        'y tienden a analizar cada clausula de un acuerdo financiero, cada implicacion de una herencia, cada detalle de una inversion conjunta. '
        'La intimidad sexual la viven con un enfoque en el servicio y en la tecnica, '
        'buscando complacer y perfeccionar el encuentro, pero a veces a costa de la espontaneidad y la entrega genuina.\n'
        '\n'
        'La imagen que proyectan en la Casa 8 es la de personas responsables y meticulosas que se ocupan de los detalles '
        'que otros prefieren ignorar en los procesos de crisis. '
        'Los demas confian en su capacidad para gestionar los aspectos practicos de la transformacion: '
        'los papeles de una herencia, la logistica de una separacion, la organizacion de los recursos compartidos. '
        'Sin embargo, detras de esta fachada de eficiencia hay una ansiedad constante por no estar haciendo lo suficiente, '
        'por no estar gestionando los recursos de manera optima, por no estar a la altura de las exigencias de la crisis.\n'
        '\n'
        'El conflicto central de esta posicion es la tendencia a controlar mediante el analisis lo que solo puede vivirse. '
        'Quienes tienen la Casa 8 en Virgo quieren entender la transformacion antes de entregarse a ella, '
        'quieren tener un plan para la crisis, un protocolo para la perdida, un sistema para la intimidad. '
        'Pero la Casa 8 no se rige por protocolos: la crisis llega cuando llega, la transformacion ocurre en sus propios terminos, '
        'y el intento de controlarlo todo genera una ansiedad que paraliza justo cuando mas se necesita fluir. '
        'En el ambito sexual, la tendencia a analizar el desempeno, a preocuparse por complacer perfectamente, '
        'puede robar la espontaneidad y la conexion genuina del encuentro. '
        'En las finanzas compartidas, su perfeccionismo puede llevarlas a posponer decisiones importantes '
        'porque nunca tienen toda la informacion que consideran necesaria.\n'
        '\n'
        'En su mejor expresion, los nativos con esta posicion son administradores excepcionales de los recursos compartidos. '
        'Su atencion al detalle y su capacidad de planificacion las convierte en gestoras de herencias, '
        'herencias y acuerdos financieros que funcionan con precision milimetrica. '
        'En la intimidad, su dedicacion al placer de la pareja y su deseo genuino de servir crean encuentros donde el otro se siente profundamente cuidado. '
        'Su capacidad de analizar las crisis sin perderse en el panico las convierte en presencias estabilizadoras en momentos de caos colectivo. '
        'La sombra a trabajar es la ansiedad perfeccionista que impide la entrega total a los procesos transformadores.\n'
        '\n'
        'Sombra: la ansiedad perfeccionista en los procesos de crisis y la tendencia a controlar lo que debe fluir.'
    ),
    "casa_8_libra": (
        'Casa 8 en Libra\n'
        '\n'
        'Quienes tienen la Casa 8 en Libra se enfrentan a la transformacion y los recursos compartidos con la gracia de quien busca el equilibrio incluso en medio de la tormenta. '
        'Libra es el signo de la armonia y las relaciones, y la Casa 8 es el territorio de los conflictos, las crisis y lo que se disuelve: '
        'esta posicion convierte cada crisis en una oportunidad para reequilibrar la balanza de las relaciones humanas. '
        'Los recursos compartidos son para ellos un area donde la justicia y la equidad son fundamentales, '
        'y cualquier desequilibrio en las finanzas conjuntas les genera un malestar que va mas alla de lo economico: '
        'es una herida en su sentido de lo justo. Las herencias, los acuerdos prenupciales y las inversiones conjuntas '
        'son territorios donde su busqueda de equilibrio se pone a prueba de manera constante.\n'
        '\n'
        'La imagen que proyectan en la Casa 8 es la de personas diplomaticas y justas que saben negociar los acuerdos financieros '
        'y las dinamicas de poder con una elegancia que desarma. '
        'Los demas perciben en ellas una capacidad de encontrar soluciones que satisfagan a todas las partes, '
        'de mediar en conflictos de herencia o de separacion con un tacto que otros no poseen. '
        'Sin embargo, detras de esta fachada de equilibrio hay un miedo profundo al conflicto que puede llevarlas a aceptar condiciones injustas '
        'con tal de no romper la armonia, sacrificando sus propios intereses en pos de la paz.\n'
        '\n'
        'El conflicto central de esta posicion es la dificultad para enfrentar la fealdad de la transformacion. '
        'Quienes tienen la Casa 8 en Libra quieren que la crisis sea elegante, que la separacion sea civilizada, '
        'que la muerte tenga un sentido estetico y que el sexo sea hermoso. '
        'Pero la Casa 8 no es elegante: es visceral, es caotica, es fea a veces. '
        'Su aversion a lo desagradable puede llevarlas a posponer las conversaciones dificiles sobre dinero, '
        'a evitar los conflictos necesarios en las finanzas compartidas y a mantener relaciones economicas que ya no funcionan '
        'por no enfrentar el desequilibrio. En la intimidad, su tendencia a complacer y a priorizar la experiencia del otro '
        'puede llevarlas a desconectarse de sus propios deseos, generando una insatisfaccion que silencian para no romper la armonia. '
        'Su mayor desafio es aprender que la verdadera justicia incluye la capacidad de enfrentar el conflicto, '
        'y que la armonia autentica solo es posible cuando todas las partes han expresado sus necesidades sin miedo.\n'
        '\n'
        'En su mejor expresion, los nativos con esta posicion tienen un talento extraordinario para mediar en conflictos de recursos compartidos. '
        'Su capacidad de ver todos los lados de una disputa financiera y de encontrar soluciones donde todos ganen las convierte '
        'en negociadoras y arbitros excepcionales en herencias, divorcios y acuerdos economicos. '
        'En la intimidad, su sensibilidad estetica y su deseo de complacer crean encuentros sexuales donde la belleza y la conexion se entrelazan. '
        'La sombra a trabajar es la evasion del conflicto y la tendencia a sacrificar sus propias necesidades en pos de una armonia superficial.\n'
        '\n'
        'Sombra: la evasion del conflicto y la tendencia a sacrificar las propias necesidades economicas por mantener la paz.'
    ),
    "casa_8_escorpio": (
        'Casa 8 en Escorpio\n'
        '\n'
        'Quienes tienen la Casa 8 en Escorpio habitan el territorio de la transformacion, la sexualidad y los recursos compartidos '
        'como peces en el agua: esta es su casa natural, el lugar donde su poder se manifiesta con mas intensidad. '
        'Escorpio rige la Casa 8, y esta posicion otorga una conexion innata con los misterios de la vida y la muerte, '
        'con la regeneracion y con las corrientes ocultas del poder y el deseo. '
        'Para ellos, los recursos compartidos no son solo dinero: son una expresion de poder, de control y de conexion profunda con otros. '
        'La intimidad sexual es el terreno donde su capacidad de fusion y transformacion alcanza su maxima expresion, '
        'y donde la entrega total es tanto su mayor don como su mayor desafio. '
        'Las herencias, las inversiones conjuntas y los acuerdos economicos estan imbuidos de una intensidad '
        'que otros no comprenden pero que para ellas es simplemente la textura natural de la vida.\n'
        '\n'
        'La imagen que proyectan en la Casa 8 es la de personas magneticas, poderosas y ligeramente peligrosas. '
        'Los demas perciben en ellas una profundidad que intimida, una capacidad de ver a traves de las mascaras '
        'y de saber cosas que no se han dicho. Su presencia en asuntos financieros compartidos inspira una mezcla de confianza y aprension, '
        'porque se intuye que no revelan todas sus cartas. '
        'Sin embargo, detras de esta fachada de poder hay una vulnerabilidad que protegen con celo: '
        'el miedo a la traicion es tan profundo en ellas que la confianza genuina es quizas su lucha mas ardua.\n'
        '\n'
        'El conflicto central de esta posicion es la lucha entre el control y la entrega. '
        'Quienes tienen la Casa 8 en Escorpio saben que la transformacion requiere rendicion, '
        'pero su instinto es controlar cada variable, tener siempre un plan B, no mostrar todas sus cartas. '
        'En el ambito de los recursos compartidos, esta tendencia al control puede manifestarse como secretismo financiero, '
        'como una reticencia a compartir informacion economica completa incluso con la pareja mas intima. '
        'Su desconfianza hacia las intenciones ajenas en asuntos de dinero las lleva a veces a aislar sus recursos '
        'o a mantener cuentas separadas con un celo que puede generar conflictos en las relaciones. '
        'En la intimidad, su intensidad sexual es legendaria, pero la sombra del control y la posesividad '
        'puede convertir el encuentro amoroso en un campo de batalla donde se dirimen cuestiones de poder '
        'que nada tienen que ver con el placer o la conexion genuina.\n'
        '\n'
        'En su mejor expresion, los nativos con esta posicion tienen una capacidad de transformacion y regeneracion '
        'que es verdaderamente extraordinaria. Pueden tocar fondo y renacer, pueden mirar a los ojos de la muerte '
        'sin parpadear y pueden guiar a otros a traves de sus propias crisis con una sabiduria que parece venir de otra vida. '
        'Su conexion con los recursos compartidos, cuando esta sanada, las convierte en gestoras de patrimonios conjuntos '
        'de una lealtad y una vision estrategica inigualables. '
        'En la intimidad, su capacidad de entrega total y su busqueda de la fusion profunda crea encuentros sexuales '
        'que trascienden lo puramente fisico para tocar dimensiones espirituales. '
        'La sombra a trabajar es la desconfianza y el control, '
        'que las mantiene atrapadas en un escudo de poder que las protege pero tambien las aísla.\n'
        '\n'
        'Sombra: la desconfianza profunda y la tendencia al control que aísla y obstaculiza la entrega genuina.'
    ),
    "casa_8_sagitario": (
        'Casa 8 en Sagitario\n'
        '\n'
        'Quienes tienen la Casa 8 en Sagitario se enfrentan a la transformacion y los recursos compartidos con el optimismo y la busqueda de significado '
        'que caracteriza al arquero celestial. Para ellos, la crisis no es una catastrofe sino una aventura, '
        'una expedicion al corazon de la oscuridad de la que emergeran con una sabiduria mayor. '
        'Los recursos compartidos los abordan con una generosidad expansiva que a veces roza la ingenuidad: '
        'confian en que el dinero llegara, en que los acuerdos se resolveran, en que el universo proveera. '
        'La intimidad sexual la viven como una exploracion, un viaje hacia el otro donde el deseo se mezcla con la curiosidad filosofica '
        'y donde el sentido del humor y la aventura son tan importantes como la conexion fisica. '
        'Las herencias y los bienes conjuntos son vistos como recursos para expandir horizontes, '
        'no como anclas que atan al pasado o a la seguridad material.\n'
        '\n'
        'La imagen que proyectan en la Casa 8 es la de personas que enfrentan las crisis con una fe inquebrantable '
        'y una capacidad de encontrarle sentido hasta a las experiencias mas dolorosas. '
        'Los demas buscan su compania en momentos de crisis porque su optimismo y su perspectiva amplia ayudan a poner las cosas en contexto. '
        'Sin embargo, detras de esta fachada de fe optimista hay una tendencia a evadir la profundidad del dolor, '
        'a saltar rapidamente hacia el significado sin haber procesado realmente la experiencia de la perdida.\n'
        '\n'
        'El conflicto central de esta posicion es la tension entre la busqueda de significado y la evasion del dolor profundo. '
        'Quienes tienen la Casa 8 en Sagitario quieren entender la crisis, encontrarle un proposito, '
        'convertirla en una historia de crecimiento que contar. '
        'Pero a veces esta necesidad de encontrar sentido les impide simplemente estar con el dolor, '
        'sin tener que justificarlo ni trascenderlo. '
        'En el ambito de los recursos compartidos, su optimismo puede llevarlas a asumir riesgos financieros conjuntos sin el analisis suficiente, '
        'confiando en que todo saldra bien por la fuerza de su fe. '
        'En la intimidad, su deseo de aventura y exploracion puede chocar con la necesidad de profundidad y compromiso sostenido '
        'que la sexualidad compartida requiere para alcanzar su maximo potencial de conexion. '
        'Su mayor desafio es aprender que la verdadera sabiduria de la Casa 8 no esta en trascender el dolor '
        'sino en atravesarlo sin saltarse pasos.\n'
        '\n'
        'En su mejor expresion, los nativos con esta posicion tienen una capacidad de encontrar luz en la oscuridad '
        'que inspira a todos los que los rodean en momentos de crisis. '
        'Su fe en el proceso de la vida es contagiosa, y su capacidad de ayudar a otros a encontrar significado '
        'en sus propias perdidas y transformaciones es un don sanador. '
        'En la gestion de recursos compartidos, su generosidad y su vision amplia las convierte '
        'en socias que invierten en proyectos con sentido, no solo en ganancias. '
        'En la intimidad, su entusiasmo y su amor por la exploracion crean una sexualidad aventurera y llena de descubrimiento. '
        'La sombra a trabajar es la evasion del dolor a traves del optimismo forzado, '
        'que les impide procesar las crisis con la profundidad que la Casa 8 exige.\n'
        '\n'
        'Sombra: la evasion del dolor mediante el optimismo filosofico, y la dificultad para estar con la crisis sin buscarle sentido inmediato.'
    ),
    "casa_8_capricornio": (
        'Casa 8 en Capricornio\n'
        '\n'
        'Quienes tienen la Casa 8 en Capricornio se enfrentan a la transformacion, la sexualidad y los recursos compartidos '
        'con la seriedad, la disciplina y la vision estrategica que caracterizan a la cabra de montana. '
        'Para ellos, la crisis no es una sorpresa sino una realidad que hay que gestionar con responsabilidad y planificacion. '
        'Los recursos compartidos son un area donde su sentido del deber se manifiesta con toda su fuerza: '
        'toman las herencias, los impuestos y los acuerdos financieros con una seriedad que otros pueden percibir como fria o calculadora, '
        'pero que para ellos es simplemente la forma adulta de manejar la realidad material. '
        'La intimidad sexual la abordan con control y con un sentido de responsabilidad que '
        'puede dificultar la entrega espontanea, pero tambien con una profundidad y lealtad que se gana con el tiempo.\n'
        '\n'
        'La imagen que proyectan en la Casa 8 es la de personas serias y confiables que gestionan los recursos conjuntos '
        'con una responsabilidad que inspira respeto. Los demas confian en ellas para administrar herencias, '
        'para gestionar patrimonios compartidos y para tomar decisiones financieras en momentos de crisis '
        'porque su criterio es solido y su juicio, mesurado. '
        'Sin embargo, detras de esta fachada de autoridad financiera hay un miedo a la escasez '
        'que las impulsa a controlar los recursos con una rigidez que puede sofocar la generosidad y la fluidez.\n'
        '\n'
        'El conflicto central de esta posicion es la rigidez en el corazon de la transformacion. '
        'Quienes tienen la Casa 8 en Capricornio quieren controlar el proceso de cambio, planificarlo, '
        'gestionarlo con la misma eficiencia con que gestionan una empresa. '
        'Pero la Casa 8 no se deja planificar: las crisis llegan cuando menos se esperan, '
        'los procesos de muerte y renacimiento siguen sus propios ritmos, '
        'y el intento de controlarlo todo genera una tension que puede volverse insoportable. '
        'En el ambito de los recursos compartidos, esta rigidez se manifiesta como una dificultad para delegar, '
        'para confiar en que otros pueden gestionar el dinero conjunto con la misma responsabilidad. '
        'Su tendencia a asumir todo el peso de las responsabilidades financieras puede agotarlas, '
        'y su sentido del deber las lleva a veces a sostener acuerdos economicos que ya no les benefician '
        'porque abandonar les parece una irresponsabilidad. '
        'En la intimidad, el control emocional y la dificultad para soltar la armadura '
        'pueden impedirles la entrega total que la sexualidad transformadora requiere.\n'
        '\n'
        'En su mejor expresion, los nativos con esta posicion son administradores excepcionales de los recursos compartidos. '
        'Su capacidad de planificar a largo plazo, de gestionar herencias y patrimonios con una vision estrategica, '
        'y de tomar decisiones dificiles con frialdad cuando es necesario, las convierte en guardianas de la riqueza colectiva. '
        'Su lealtad en las finanzas compartidas es absoluta, y su palabra es su garantia. '
        'En la intimidad, su compromiso y su profundidad, cuando logran bajar la armadura, '
        'crean encuentros de una solidez y una entrega que trascienden lo superficial. '
        'La sombra a trabajar es la rigidez emocional y financiera que impide la fluidez '
        'y la entrega que la Casa 8 requiere para su plena expresion.\n'
        '\n'
        'Sombra: la rigidez emocional y financiera, y la dificultad para soltar el control en los procesos de crisis.'
    ),
    "casa_8_acuario": (
        'Casa 8 en Acuario\n'
        '\n'
        'Quienes tienen la Casa 8 en Acuario se relacionan con la transformacion, la sexualidad y los recursos compartidos '
        'desde la originalidad, el desapego y una vision que trasciende lo individual. '
        'Acuario es el signo de la innovacion y lo colectivo, y la Casa 8 es el territorio de lo intimo y lo oculto: '
        'esta combinacion crea una tension entre la necesidad de libertad y la entrega profunda '
        'que define toda su experiencia en estas areas. '
        'Los recursos compartidos los abordan desde una perspectiva poco convencional: '
        'pueden estar a favor de modelos economicos alternativos, de la gestion colectiva de bienes o de la transparencia radical en las finanzas conjuntas. '
        'Para ellos, las herencias y las inversiones no son solo asuntos personales sino cuestiones que tienen implicaciones sociales y humanitarias.\n'
        '\n'
        'La imagen que proyectan en la Casa 8 es la de personas desprendidas e innovadoras que no se aferran a lo material '
        'y que abordan las crisis con una frialdad racional que puede resultar desconcertante. '
        'Los demas perciben en ellas una capacidad de distanciarse de las tormentas emocionales '
        'que a otros consumen, una perspectiva casi cientifica sobre los procesos de transformacion. '
        'Sin embargo, detras de esta fachada de desapego hay una dificultad para conectar con la profundidad emocional '
        'que la Casa 8 exige, una tendencia a intelectualizar la crisis en lugar de vivirla.\n'
        '\n'
        'El conflicto central de esta posicion es la tension entre la libertad individual y la entrega intima. '
        'Quienes tienen la Casa 8 en Acuario valoran su independencia por encima de casi todo, '
        'y la Casa 8 les exige niveles de fusion y entrega que desafian esa autonomia. '
        'En el ambito de los recursos compartidos, esta tension se manifiesta como una dificultad para comprometerse '
        'en acuerdos financieros a largo plazo con otros, o como una tendencia a mantener cuentas separadas '
        'incluso en relaciones donde la fusion economica seria lo esperable. '
        'Su deseo de transparencia radical en las finanzas choca con su necesidad de privacidad, '
        'y pueden defender la gestion colectiva de recursos mientras mantienen sus propios asuntos financieros en reserva. '
        'En la intimidad, su enfoque experimental y su apertura a formas no convencionales de sexualidad '
        'choca con la dificultad para la conexion emocional profunda que la entrega sexual plena requiere. '
        'Su mayor desafio es aprender que la verdadera libertad incluye la capacidad de entregarse sin perderse.\n'
        '\n'
        'En su mejor expresion, los nativos con esta posicion son innovadores en el terreno de los recursos compartidos. '
        'Su vision humanitaria y su capacidad de pensar mas alla de las estructuras tradicionales '
        'las convierte en promotoras de modelos economicos alternativos, de herencias solidarias '
        'y de formas de gestion colectiva que benefician a comunidades enteras. '
        'En la intimidad, su apertura mental y su ausencia de prejuicios crea espacios para la exploracion sexual '
        'libre de las limitaciones que otras posiciones imponen. '
        'Su capacidad de distanciamiento las convierte en excelentes apoyos en crisis ajenas, '
        'porque no se dejan arrastrar por el drama y pueden ofrecer una perspectiva clara. '
        'La sombra a trabajar es la desconexion emocional que impide la entrega profunda '
        'y la tendencia a refugiarse en la racionalidad para evitar la vulnerabilidad de la Casa 8.\n'
        '\n'
        'Sombra: la desconexion emocional y la tendencia a intelectualizar la crisis para evitar la entrega profunda.'
    ),
    "casa_8_piscis": (
        'Casa 8 en Piscis\n'
        '\n'
        'Quienes tienen la Casa 8 en Piscis se relacionan con la transformacion, la sexualidad y los recursos compartidos '
        'desde un lugar de disolucion, compasion y conexion espiritual. Piscis es el signo de la fusion con el todo, '
        'y la Casa 8 es el territorio donde los limites entre el yo y el otro se disuelven: '
        'esta combinacion crea una experiencia de la intimidad y los recursos compartidos que trasciende lo puramente material '
        'para tocar dimensiones casi misticas. '
        'Para ellos, los recursos compartidos no tienen sentido si no se ponen al servicio de algo mayor que uno mismo, '
        'y la generosidad con el dinero y los bienes es tan natural como respirar. '
        'La intimidad sexual es el terreno donde la fusion con el otro alcanza su maxima expresion, '
        'donde el sexo se convierte en experiencia espiritual y donde la entrega total es tanto su don mas preciado como su mayor riesgo.\n'
        '\n'
        'La imagen que proyectan en la Casa 8 es la de personas compasivas y espirituales que trascienden las preocupaciones materiales '
        'y que abordan las crisis con una fe que desconcierta a quienes las rodean. '
        'Los demas perciben en ellas una conexion con algo mas grande, una capacidad de estar presentes en el dolor ajeno '
        'sin intentar controlarlo ni solucionarlo, simplemente acompanando. '
        'Sin embargo, detras de esta fachada de entrega espiritual hay una tendencia a la evasion: '
        'la espiritualidad bien puede ser un refugio para no enfrentar la realidad concreta de las finanzas compartidas '
        'o para evitar tomar decisiones dificiles en el terreno economico.\n'
        '\n'
        'El conflicto central de esta posicion es la tendencia a la disolucion de los limites. '
        'Quienes tienen la Casa 8 en Piscis pueden tener dificultades para distinguir entre generosidad y autosacrificio, '
        'entre compartir y perderse en el otro, entre la compasion y la codependencia. '
        'En el ambito de los recursos compartidos, su generosidad sin limites puede llevarlas a asumir deudas ajenas, '
        'a firmar avales sin evaluar los riesgos o a sostener economicamente a otros mas alla de lo razonable. '
        'Su falta de limites en las finanzas conjuntas las hace vulnerables a la manipulacion economica, '
        'y su aversion a los conflictos las lleva a veces a aceptar acuerdos financieros desfavorables '
        'con tal de no romper la conexion con el otro. '
        'En la intimidad, su capacidad de fusion es tan poderosa que pueden perderse en la experiencia sexual, '
        'confundiendo la entrega con la anulacion de si mismas. '
        'Su mayor desafio es aprender a compartir sin disolverse, a entregarse sin perderse, '
        'a ser compasivas sin sacrificar su propia integridad.\n'
        '\n'
        'En su mejor expresion, los nativos con esta posicion tienen una capacidad de compasion y conexion espiritual '
        'que transforma cualquier crisis en una oportunidad de trascendencia. '
        'Su generosidad con los recursos compartidos es un ejemplo vivo de que el dinero puede ser un canal para el amor '
        'y no solo un instrumento de acumulacion. '
        'En la intimidad, su capacidad de fusion y su conexion con lo trascendente crea encuentros sexuales '
        'donde el placer fisico y la experiencia espiritual se entrelazan de maneras que pocos pueden comprender. '
        'Su fe en el proceso de la vida es un ancla para quienes las rodean en momentos de crisis. '
        'La sombra a trabajar es la tendencia a perderse en el otro y la evasion de la realidad material '
        'mediante la espiritualidad o la fantasia.\n'
        '\n'
        'Sombra: la disolucion de los limites en las finanzas compartidas y la evasion de la realidad material '
        'mediante la espiritualidad o la fantasia.'
    ),
}

file_path = "/home/pipe/Documents/proyectos/cartas_natales/datos/casas_signos.json"

with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

# Replace entries
for key, value in entries.items():
    data[key] = value

# Write back
with open(file_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# Print char counts
print("Character counts for Casa 8 entries:")
total = 0
for sign in SIGNS:
    key = f"casa_8_{sign}"
    count = len(entries[key])
    print(f"  {key}: {count} chars")
    total += count
print(f"\nTotal: {total} chars across {len(SIGNS)} entries")
print(f"Average: {total // len(SIGNS)} chars per entry")

# Check minimum
min_count = min(len(entries[key]) for key in entries)
max_count = max(len(entries[key]) for key in entries)
print(f"\nMin: {min_count} chars, Max: {max_count} chars")
if min_count >= 1800:
    print("✅ All entries meet the 1800-character minimum!")
else:
    print(f"❌ Some entries are below 1800 characters (min is {min_count})")
