#!/usr/bin/env python3
import json

filepath = "/home/pipe/Documents/proyectos/cartas_natales/datos/casas_signos.json"

with open(filepath, 'r', encoding='utf-8') as f:
    data = json.load(f)

entries = {
    "casa_1_aries": (
        "Casa 1 en Aries\n"
        "\n"
        "Quienes tienen la Casa 1 en Aries proyectan una identidad marcada por la impulsividad, "
        "el coraje y una energía pionera que los distingue en cualquier entorno. Su forma de "
        "presentarse al mundo es directa y sin rodeos; no hay en ellos interés por ocultar sus "
        "intenciones ni por suavizar el impacto que generan. La vida es un escenario donde actúan "
        "con espontaneidad, y su presencia suele sentirse antes de que crucen la puerta. Hay una "
        "cualidad de iniciadores en estas personas, de aquellas que no esperan a que las cosas "
        "sucedan sino que salen a buscarlas con una determinación que puede resultar intimidante "
        "para los más cautelosos.\n"
        "\n"
        "La imagen que proyectan es de seguridad y audacia. Los demás las perciben como individuos "
        "que saben lo que quieren y que no temen ir a por ello con toda su energía. Su lenguaje "
        "corporal es expansivo, su mirada directa y su forma de moverse transmite una urgencia "
        "vital que resulta contagiosa. Sin embargo, esta fachada de confianza absoluta oculta a "
        "menudo unas dudas internas que la acción impulsiva busca acallar antes de que emerjan a "
        "la conciencia.\n"
        "\n"
        "El conflicto principal radica en aprender a equilibrar la autoafirmación con la "
        "consideración por los demás. Su tendencia a imponer su voluntad puede generar roces "
        "innecesarios, y su impaciencia las lleva a actuar antes de pensar, a veces con "
        "consecuencias que luego requieren mucho más tiempo del que habrían necesitado para "
        "reflexionar. La dificultad para esperar es quizás su mayor desafío: quieren resultados "
        "inmediatos, y la frustración cuando las cosas no ocurren a su ritmo puede desencadenar "
        "reacciones desproporcionadas. El desarrollo personal implica cultivar la paciencia, la "
        "escucha activa y la conciencia del impacto que generan en quienes las rodean.\n"
        "\n"
        "En su expresión más evolucionada, son líderes natos que inspiran con su autenticidad y "
        "su valentía. Su capacidad de tomar la iniciativa y de enfrentar los desafíos de frente es "
        "un don que, bien canalizado, las convierte en personas capaces de abrir caminos para sí "
        "mismas y para otros. La sombra a trabajar es el egoísmo y la confrontación innecesaria, "
        "que cuando se transforma da paso a la cualidad de defender con pasión lo que es justo."
    ),
    "casa_1_tauro": (
        "Casa 1 en Tauro\n"
        "\n"
        "Quienes tienen la Casa 1 en Tauro proyectan una identidad de solidez y estabilidad que "
        "transmite una confianza profunda a quienes los rodean. Su presencia es serena, pausada, "
        "como la de quien sabe exactamente quién es y no necesita demostrar nada a nadie. Hay en "
        "ellos una cualidad de roca, de permanencia, que los convierte en anclas emocionales en "
        "momentos de crisis. Su autoestima está conectada con su capacidad de construir y mantener "
        "aquello que valoran, y eso incluye tanto los bienes materiales como las relaciones y los "
        "principios que rigen su vida.\n"
        "\n"
        "La imagen que proyectan es de calma y autoridad silenciosa. Los demás perciben en ellas "
        "una solidez que inspira confianza, una sensación de que nada puede desestabilizarlas "
        "fácilmente. Su forma de moverse es medida, sus gestos son contenidos y su mirada "
        "transmite una seguridad que pocos signos pueden igualar. Sin embargo, detrás de esta "
        "fachada de imperturbabilidad hay una resistencia al cambio que puede volverse rigidez, "
        "un aferrarse a lo conocido incluso cuando lo conocido ya no les sirve.\n"
        "\n"
        "El conflicto central es la dificultad para soltar y adaptarse. Su necesidad de seguridad "
        "puede convertirse en una cárcel de comodidad que les impide arriesgarse a crecer. El "
        "amor por lo estable las lleva a permanecer en situaciones que ya no las nutren, ya sea "
        "en relaciones, trabajos o patrones de pensamiento. Aprender a soltar sin sentir que "
        "pierden su identidad es una de las tareas más importantes de su desarrollo, y requiere "
        "una conciencia de que la verdadera estabilidad no es estática sino dinámica.\n"
        "\n"
        "En su mejor expresión, estas personas son la encarnación de la lealtad y la persistencia. "
        "Construyen su vida sobre cimientos sólidos y no abandonan fácilmente lo que han comenzado. "
        "Su capacidad de esperar el momento adecuado y de trabajar de manera constante hacia sus "
        "metas es una cualidad que pocos poseen en igual medida. La sombra a trabajar es la "
        "posesividad y la terquedad que limita su crecimiento, que transformada da lugar a una "
        "determinación inquebrantable al servicio de lo que realmente importa."
    ),
    "casa_1_geminis": (
        "Casa 1 en Géminis\n"
        "\n"
        "Quienes tienen la Casa 1 en Géminis proyectan una identidad versátil, curiosa y "
        "eminentemente comunicativa. Su presencia es ligera, cambiante, como el mercurio que "
        "rige esta posición. Tienden a adaptarse rápidamente a cualquier entorno y a conectar "
        "con personas de todo tipo con una facilidad que asombra a quienes los rodean. Su mente "
        "es su herramienta principal, y la usan constantemente para procesar, analizar y "
        "compartir información. No hay conversación trivial para ellos porque hasta el intercambio "
        "más simple puede contener una chispa de conocimiento.\n"
        "\n"
        "La imagen que proyectan es de inteligencia vivaz y encanto social. Los demás las ven "
        "como personas ingeniosas, divertidas y siempre al día. Su lenguaje corporal es expresivo, "
        "sus manos acompañan sus palabras y su mirada cambia constantemente mientras navegan "
        "entre ideas. Sin embargo, detrás de esta agilidad mental hay una inquietud profunda: "
        "el miedo a perderse algo, a no estar al tanto, a quedar excluidas de la conversación. "
        "Su identidad se construye en gran parte a través del intercambio con otros.\n"
        "\n"
        "El conflicto central es la dispersión y la superficialidad. Su tendencia a saltar de un "
        "interés a otro puede impedirles profundizar en nada, y su facilidad para la comunicación "
        "puede convertirse en una estrategia de evasión de la intimidad emocional genuina. La "
        "mente nunca se calla, y ese ruido constante puede ser una barrera para conectar con su "
        "propio mundo interior. El desarrollo personal implica aprender a enfocar su energía, a "
        "comprometerse con la profundidad que requieren las relaciones y los proyectos "
        "significativos, y a descubrir que el silencio también contiene información valiosa.\n"
        "\n"
        "En su mejor expresión, son personas de una versatilidad y una inteligencia social "
        "envidiables. Su capacidad de ver múltiples perspectivas y de comunicar ideas complejas "
        "de manera accesible las convierte en excelentes mediadores, escritores o educadores. "
        "La sombra a trabajar es la inconsistencia y la tendencia a intelectualizar las emociones "
        "para evitar sentirlas, que cuando se integra da lugar a una mente brillante al servicio "
        "tanto del corazón como del intelecto."
    ),
    "casa_1_cancer": (
        "Casa 1 en Cáncer\n"
        "\n"
        "Quienes tienen la Casa 1 en Cáncer proyectan una identidad protectora, emotiva y "
        "profundamente conectada con su mundo interior. Su presencia es receptiva y cuidadosa, "
        "como la de quien lleva su hogar a cuestas y busca crear un espacio seguro dondequiera "
        "que vaya. La mirada revela una sensibilidad que los hace especialmente perceptivos a "
        "las necesidades emocionales de quienes los rodean, y su forma de relacionarse está "
        "impregnada de una cualidad maternal o paternal que invita a la confianza. Hay una "
        "suavidad en su presencia que contrasta con la fortaleza de su protección.\n"
        "\n"
        "La imagen que proyectan es de ternura y accesibilidad emocional. Los demás intuyen que "
        "pueden acercarse sin temor, que serán recibidos con calidez y comprensión. Su rostro "
        "refleja sus estados de ánimo con una transparencia que los hace vulnerables, y su forma "
        "de moverse por el mundo está guiada por la intuición más que por la lógica. Sin embargo, "
        "detrás de esta apertura hay una coraza invisible que se activa cuando perciben una "
        "amenaza. Su identidad está tan ligada a cuidar de otros que a menudo descuidan su "
        "propio bienestar.\n"
        "\n"
        "El conflicto central es la dificultad para establecer límites emocionales. Su tendencia "
        "a absorber el estado anímico del entorno puede dejarlas agotadas y confundidas acerca "
        "de lo que realmente sienten. La porosidad emocional es su don y su maldición: sienten "
        "todo con una intensidad que pocos comprenden, pero esa misma sensibilidad las expone "
        "a la fatiga emocional crónica. El desarrollo personal implica aprender a protegerse sin "
        "aislarse, a distinguir entre sus emociones y las de los demás, y a nutrirse a sí mismas "
        "tanto como nutren a otros.\n"
        "\n"
        "En su mejor expresión, estas personas tienen una capacidad de empatía y cuidado que es "
        "verdaderamente excepcional. Son quienes sostienen a su círculo con una lealtad "
        "incondicional y una sensibilidad que pocos pueden igualar. Su intuición emocional es un "
        "don que, bien gestionado, las convierte en consejeras y apoyos invaluables. La sombra a "
        "trabajar es la dependencia emocional y la tendencia al victimismo, que cuando se "
        "transmuta da paso a una fortaleza interior tan profunda como silenciosa."
    ),
    "casa_1_leo": (
        "Casa 1 en Leo\n"
        "\n"
        "Quienes tienen la Casa 1 en Leo proyectan una identidad radiante, segura y dramática "
        "que ilumina cualquier espacio que habitan. Su presencia es difícil de ignorar; hay en "
        "ellos una cualidad solar que atrae la atención y una calidez que invita a acercarse. "
        "Se presentan al mundo con orgullo y generosidad, como si la vida fuera un escenario "
        "donde brillar es tanto un derecho como una responsabilidad. Su creatividad y su "
        "entusiasmo son contagiosos, y quienes los rodean suelen sentirse elevados por su "
        "energía vital.\n"
        "\n"
        "La imagen que proyectan es de realeza natural y carisma magnético. Los demás las ven "
        "como personas seguras de sí mismas, generosas y apasionadas. Su forma de caminar, de "
        "hablar, de gesticular, todo en ellas comunica una certeza interior que otras personas "
        "encuentran inspiradora. Sin embargo, detrás de este brillo exterior hay una dependencia "
        "de la validación externa que puede volverse una necesidad insaciable. El miedo a no ser "
        "suficientemente especiales, a quedar en la sombra, las impulsa a buscar constantemente "
        "la mirada y el aplauso de los demás.\n"
        "\n"
        "El conflicto central es la tensión entre su genuina generosidad y su necesidad de "
        "reconocimiento. Su orgullo puede impedirles recibir retroalimentación honesta, y su "
        "dramatismo puede desgastar a quienes las rodean cuando la atención no está puesta en "
        "ellas. El desarrollo personal pasa por descubrir que su valor es intrínseco y no "
        "depende del aplauso ajeno, que pueden brillar incluso cuando nadie las observa, y que "
        "la verdadera realeza no necesita ser constantemente confirmada.\n"
        "\n"
        "En su mejor expresión, son líderes carismáticos que inspiran con su generosidad y su "
        "pasión. Tienen el don de infundir vitalidad y entusiasmo en cualquier proyecto, y su "
        "capacidad de celebrar los logros ajenos es tan genuina como su deseo de brillar. La "
        "sombra a trabajar es el egocentrismo y la necesidad excesiva de atención, que cuando "
        "se transforma se convierte en un liderazgo que verdaderamente ilumina a quienes las "
        "rodean."
    ),
    "casa_1_virgo": (
        "Casa 1 en Virgo\n"
        "\n"
        "Quienes tienen la Casa 1 en Virgo proyectan una identidad analítica, modesta y "
        "servicial que a menudo pasa desapercibida en una primera impresión pero deja una "
        "huella profunda en quienes saben observar con atención. Su presencia es discreta pero "
        "sólida, y su forma de moverse por el mundo está marcada por la atención al detalle y "
        "el deseo genuino de ser útiles. Hay en ellos una cualidad de artesano, de quien pule "
        "cada aspecto de su vida con una dedicación que otros rara vez comprenden. Su identidad "
        "no se construye con grandezas sino con la suma de pequeñas perfecciones cotidianas.\n"
        "\n"
        "La imagen que proyectan es de eficiencia y confiabilidad. Los demás recurren a ellas "
        "cuando necesitan orden, claridad o una solución práctica a un problema complejo. Su "
        "lenguaje es preciso, su apariencia es pulcra y su forma de relacionarse está medida. "
        "Sin embargo, detrás de esta fachada de competencia hay una autocrítica implacable que "
        "nunca se calla. Su capacidad para ver los defectos, tanto en sí mismas como en su "
        "entorno, puede convertirse en una fuente constante de ansiedad e insatisfacción.\n"
        "\n"
        "El conflicto central es el perfeccionismo paralizante. La voz interna que señala todo "
        "lo que está mal, todo lo que podría mejorarse, todo lo que no alcanza el estándar "
        "ideal, es implacable y agotadora. Esta exigencia las lleva a esforzarse más que nadie, "
        "pero también a disfrutar menos de sus logros porque siempre hay algo que corregir. El "
        "desarrollo personal implica aprender a aceptar la imperfección como parte de la "
        "experiencia humana, a valorar lo que ya han logrado y a entender que el error no es "
        "una falla moral sino una oportunidad de aprendizaje.\n"
        "\n"
        "En su mejor expresión, son personas meticulosas, eficientes y dedicadas. Su capacidad "
        "de análisis y su compromiso con la excelencia las convierte en profesionales "
        "excepcionales en cualquier campo que requiera precisión. Su humildad y su disposición "
        "a servir son cualidades que las hacen querer y respetar. La sombra a trabajar es la "
        "tendencia a la preocupación excesiva y al juicio crítico, que transformada da lugar a "
        "un servicio genuino que eleva tanto a quien da como a quien recibe."
    ),
    "casa_1_libra": (
        "Casa 1 en Libra\n"
        "\n"
        "Quienes tienen la Casa 1 en Libra proyectan una identidad armoniosa, diplomática y "
        "estéticamente consciente que los convierte en personas naturalmente agradables y "
        "socialmente hábiles. Su presencia es equilibrada y serena, como la de quien ha "
        "comprendido que la belleza y la armonía no son superficiales sino esenciales para "
        "una vida plena. Hay en ellos una cualidad de buscar el equilibrio y la justicia en "
        "todas sus interacciones, y un deseo genuino de crear relaciones donde todos se sientan "
        "escuchados y valorados. Su encanto natural las hace queridas en círculos sociales.\n"
        "\n"
        "La imagen que proyectan es de gracia y sofisticación. Los demás las perciben como "
        "personas justas, objetivas y estéticamente refinadas. Su forma de vestir, de hablar "
        "y de moverse revela un sentido innato de la proporción y la elegancia. Sin embargo, "
        "detrás de esta fachada de equilibrio hay un miedo profundo al conflicto que puede "
        "llevarlas a sacrificar su propia verdad en nombre de la paz. La indecisión es su "
        "fantasma constante: ver todos los lados de cada situación puede paralizarlas.\n"
        "\n"
        "El conflicto central es la tendencia a anteponer la armonía externa a su propia "
        "integridad. Su miedo al conflicto puede llevarlas a evitar confrontaciones necesarias "
        "y a comprometerse en exceso, acumulando resentimientos que tarde o temprano emergen "
        "de maneras poco saludables. La necesidad de agradar puede opacar su auténtica voz. El "
        "desarrollo personal implica aprender a defender su propia posición, a tolerar el "
        "conflicto como parte de relaciones auténticas y a entender que la verdadera armonía "
        "incluye la capacidad de integrar las diferencias.\n"
        "\n"
        "En su mejor expresión, tienen un talento extraordinario para la diplomacia y la "
        "mediación. Su capacidad de ver todos los lados de una situación y de encontrar puntos "
        "de encuentro las convierte en constructoras de puentes. Su sentido estético y su amor "
        "por la belleza enriquecen cualquier entorno. La sombra a trabajar es la dependencia de "
        "las relaciones y la dificultad para estar solas, que transformada da lugar a una "
        "capacidad de crear armonía que nace desde la plenitud interior."
    ),
    "casa_1_escorpio": (
        "Casa 1 en Escorpio\n"
        "\n"
        "Quienes tienen la Casa 1 en Escorpio proyectan una identidad intensa, magnética y "
        "enigmática que resulta imposible de ignorar. Su presencia es poderosa y puede resultar "
        "intimidante para quienes no están preparados para su profundidad. Hay en ellos una "
        "mirada que parece ver más allá de las apariencias, una cualidad investigadora que los "
        "lleva a indagar en lo oculto y en lo tabú. No pasan desapercibidos porque su energía "
        "es demasiado densa, demasiado real para diluirse en la superficialidad de las "
        "interacciones cotidianas.\n"
        "\n"
        "La imagen que proyectan es de misterio y poder. Los demás intuyen que hay capas y más "
        "capas debajo de la superficie, que lo que muestras es solo una fracción de lo que "
        "contienen. Su lenguaje corporal es contenido pero elocuente, su mirada es penetrante "
        "y su silencio comunica tanto como sus palabras. Sin embargo, detrás de esta fachada "
        "de control hay una intensidad emocional que amenaza con desbordarse constantemente. "
        "El miedo a la traición y a la vulnerabilidad las lleva a protegerse tras muros que "
        "otros pueden sentir como frialdad o distancia.\n"
        "\n"
        "El conflicto central es la lucha entre el control y la entrega. Su necesidad de "
        "mantener el dominio sobre sus emociones y su entorno puede convertirse en manipulación "
        "o deseo de control cuando no se gestiona conscientemente. La desconfianza es su "
        "mecanismo de defensa principal, y aunque les ha servido para protegerse, también les "
        "impide experimentar la conexión genuina que anhelan. El desarrollo personal implica "
        "aprender a confiar, a soltar el control y a permitir que otros vean su vulnerabilidad "
        "sin temor a ser destruidas.\n"
        "\n"
        "En su mejor expresión, tienen una capacidad de transformación y regeneración que es "
        "verdaderamente extraordinaria. Son quienes pueden atravesar las crisis más profundas "
        "y emerger fortalecidas. Su poder de penetración psicológica las convierte en excelentes "
        "terapeutas, investigadores o agentes de cambio. La sombra a trabajar es la desconfianza "
        "y el secretismo, que cuando se transforma da lugar a una capacidad de ver la verdad y "
        "de acompañar a otros en sus procesos de sanación más profundos."
    ),
    "casa_1_sagitario": (
        "Casa 1 en Sagitario\n"
        "\n"
        "Quienes tienen la Casa 1 en Sagitario proyectan una identidad optimista, aventurera y "
        "expansiva que contagia a quienes los rodean con su amor por la libertad y la "
        "exploración. Su presencia es abierta y entusiasta, como la de quien siempre está "
        "listo para la próxima aventura. Hay en ellos una cualidad de flecha que apunta siempre "
        "al horizonte, una insaciable sed de conocimiento y experiencia que los impulsa a "
        "viajar, estudiar y buscar el significado más profundo de la vida. No hay conversación "
        "trivial que los sostenga por mucho tiempo porque su mente siempre busca ir más allá.\n"
        "\n"
        "La imagen que proyectan es de entusiasmo y sabiduría en movimiento. Los demás las ven "
        "como personas inspiradoras, generosas y llenas de fe en la vida. Su sonrisa es amplia, "
        "su lenguaje es apasionado y su forma de moverse transmite una energía que invita a "
        "seguirlas. Sin embargo, detrás de este optimismo radiante hay un miedo al compromiso "
        "que puede manifestarse como una huida constante hacia adelante. La incomodidad con la "
        "rutina y las responsabilidades que atan es uno de sus desafíos más profundos.\n"
        "\n"
        "El conflicto central es la dificultad para comprometerse sin sentirse atrapadas. Su "
        "amor por la libertad puede convertirse en una excusa para no profundizar en relaciones "
        "o proyectos que requieren dedicación sostenida. La impaciencia las lleva a querer "
        "resultados inmediatos, y la monotonía las sofoca. El desarrollo personal implica "
        "aprender que la verdadera libertad incluye la capacidad de comprometerse sin perder "
        "la autonomía, que la exploración más profunda es la que se hace hacia adentro y que "
        "la estabilidad puede ser tan aventurera como el movimiento constante.\n"
        "\n"
        "En su mejor expresión, son personas inspiradoras, generosas y visionarias. Su optimismo "
        "genuino y su fe en las posibilidades de la vida las convierte en fuentes de motivación "
        "para quienes las rodean. Su búsqueda de significado las lleva a explorar la filosofía, "
        "la espiritualidad o la educación superior. La sombra a trabajar es la impaciencia y la "
        "falta de tacto en su honestidad, que transformada da lugar a una sabiduría que "
        "verdaderamente guía e ilumina."
    ),
    "casa_1_capricornio": (
        "Casa 1 en Capricornio\n"
        "\n"
        "Quienes tienen la Casa 1 en Capricornio proyectan una identidad seria, responsable y "
        "ambiciosa que transmite autoridad y madurez incluso desde una edad temprana. Su "
        "presencia impone respeto; hay en ellos una cualidad de disciplina y autocontrol que "
        "los hace parecer mayores de lo que son, y una conciencia de la responsabilidad que "
        "otros tardan años en desarrollar. Su forma de moverse por el mundo es estratégica y "
        "medida, como quien sabe que cada paso cuenta y que el tiempo es un recurso que no "
        "debe desperdiciarse.\n"
        "\n"
        "La imagen que proyectan es de solvencia y autoridad natural. Los demás las perciben "
        "como personas confiables, serias y competentes. Su lenguaje es mesurado, su apariencia "
        "es formal y su comportamiento está guiado por un código interno de honor y deber. Sin "
        "embargo, detrás de esta fachada de fortaleza hay una tendencia a la rigidez emocional "
        "que las aísla. La seriedad puede convertirse en frialdad, y la ambición puede llevarlas "
        "a sacrificar su bienestar y sus relaciones en pos del éxito.\n"
        "\n"
        "El conflicto central es la dificultad para mostrar vulnerabilidad y para permitirse "
        "el descanso. Su sentido de responsabilidad es tan fuerte que pueden sentirse culpables "
        "cuando no están produciendo o avanzando hacia sus metas. El miedo al fracaso las "
        "impulsa a trabajar incansablemente, pero también las priva de la alegría del presente. "
        "El desarrollo personal implica aprender a equilibrar la responsabilidad con el disfrute, "
        "a mostrar vulnerabilidad sin sentir que fracasan, y a entender que su valor no depende "
        "exclusivamente de sus logros.\n"
        "\n"
        "En su mejor expresión, construyen su vida con una integridad y una perseverancia que "
        "inspiran respeto. Son personas de palabra, que cumplen sus compromisos incluso cuando "
        "nadie está mirando. Su capacidad de lograr metas a largo plazo es excepcional. La "
        "sombra a trabajar es el pesimismo y el aislamiento emocional, que cuando se transforma "
        "da lugar a una fortaleza serena que combina la ambición con la calidez humana."
    ),
    "casa_1_acuario": (
        "Casa 1 en Acuario\n"
        "\n"
        "Quienes tienen la Casa 1 en Acuario proyectan una identidad original, independiente y "
        "marcadamente progresista que los distingue de cualquier multitud. Su presencia es única "
        "y distintiva; no siguen modas ni convenciones, sino que crean su propio estilo con una "
        "autenticidad que puede resultar desconcertante para quienes están acostumbrados a lo "
        "predecible. Hay en ellos una cualidad de visionarios, de personas que miran hacia el "
        "futuro y que se sienten más cómodas con ideas innovadoras que con tradiciones "
        "establecidas. Su individualidad es su sello más preciado.\n"
        "\n"
        "La imagen que proyectan es de originalidad e inteligencia poco convencional. Los demás "
        "las perciben como personas interesantes, brillantes pero quizás un poco distantes. Su "
        "forma de vestir, de expresarse y de relacionarse revela una mente que opera con sus "
        "propias reglas. Sin embargo, detrás de esta fachada de independencia hay una "
        "desconexión emocional que dificulta la intimidad. Su racionalidad y su necesidad de "
        "libertad pueden alejarlas de la cercanía emocional que también necesitan, aunque no "
        "siempre lo admitan.\n"
        "\n"
        "El conflicto central es la tensión entre su necesidad de pertenencia grupal y su "
        "necesidad de individualidad radical. Quieren cambiar el mundo pero desde los márgenes, "
        "manteniendo su libertad a toda costa. La dificultad para la intimidad personal es su "
        "mayor desafío: pueden conectar con ideas y causas colectivas pero luchar para conectar "
        "con una sola persona desde el corazón. El desarrollo personal implica aprender a "
        "integrar su mente innovadora con su vida emocional, a permitir la vulnerabilidad en "
        "las relaciones cercanas y a entender que la verdadera libertad incluye la capacidad "
        "de comprometerse.\n"
        "\n"
        "En su mejor expresión, son agentes de cambio y visionarios que contribuyen al progreso "
        "colectivo. Su originalidad y su capacidad de pensar fuera de lo establecido las "
        "convierte en inventoras, innovadoras y líderes humanitarias. La sombra a trabajar es "
        "la rebelión sin causa y la impredictibilidad emocional, que transformada da lugar a "
        "una libertad auténtica que construye tanto como cuestiona."
    ),
    "casa_1_piscis": (
        "Casa 1 en Piscis\n"
        "\n"
        "Quienes tienen la Casa 1 en Piscis proyectan una identidad soñadora, compasiva y "
        "espiritualmente sintonizada que los conecta con dimensiones de la experiencia que "
        "otros apenas intuyen. Su presencia es suave y receptiva, como la de quien está "
        "conectado con corrientes invisibles que fluyen bajo la superficie de la realidad. "
        "Hay en ellos una cualidad de disolución de los límites, una sensibilidad que los "
        "hace especialmente receptivos a las corrientes emocionales y artísticas de la vida. "
        "Su mirada parece mirar a través de las cosas, como si estuvieran viendo algo que "
        "los demás no pueden ver.\n"
        "\n"
        "La imagen que proyectan es de misterio suave y compasión infinita. Los demás intuyen "
        "que hay en ellas una profundidad que no se revela fácilmente, una conexión con algo "
        "más grande que las trasciende. Su forma de moverse es fluida, casi etérea, y su "
        "presencia tiene una cualidad calmante que invita a la confianza. Sin embargo, detrás "
        "de esta suavidad hay una dificultad fundamental para establecer límites que las deja "
        "expuestas a ser inundadas por las energías y emociones de otros.\n"
        "\n"
        "El conflicto central es la tendencia al escapismo y la dificultad para sostenerse "
        "en la realidad material. Su porosidad emocional las hace vulnerables a la fatiga "
        "por empatía, y su sensibilidad puede llevarlas a refugiarse en la fantasía, las "
        "adicciones o la desconexión como forma de protección. La confusión entre dónde "
        "terminan ellas y dónde empiezan los demás es constante, y esta falta de límites "
        "puede generar dependencia emocional y una tendencia a perderse en otros. El "
        "desarrollo personal implica aprender a estar en el mundo sin perderse en él, a "
        "discernir entre la compasión genuina y el sacrificio innecesario.\n"
        "\n"
        "En su mejor expresión, tienen una compasión y una creatividad que tocan el alma "
        "de quienes los rodean. Su conexión con lo trascendente las convierte en artistas, "
        "músicos, terapeutas o guías espirituales de una sensibilidad única. Su capacidad "
        "de perdón y de comprensión es verdaderamente excepcional. La sombra a trabajar es "
        "el victimismo y la evasión de la realidad material, que cuando se transforma da "
        "lugar a una compasión poderosa que sana sin perderse en el dolor ajeno."
    ),
}

# Update
for key, value in entries.items():
    data[key] = value

# Write back
with open(filepath, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write('\n')

# Print char counts
all_ok = True
for key in sorted(entries.keys()):
    n = len(entries[key])
    ok = n >= 1800
    status = "OK" if ok else "SHORT!"
    print(f"{key}: {n} chars [{status}]")
    if not ok:
        all_ok = False

print()
if all_ok:
    print("All entries meet the 1800 char minimum.")
else:
    print("Some entries are too short! Adjust them.")
