import json
import re

FILEPATH = "/home/pipe/Documents/proyectos/cartas_natales/datos/planetas_casas.json"

entries = {
    "juno_en_casa_1": (
        "Juno en la Primera casa imprime en la identidad misma la necesidad de asociarse. "
        "Para quien tiene este emplazamiento, el compromiso no es un añadido a la vida sino la vida misma, "
        "una fuerza que configura quién es desde el primer encuentro. No concibe una relación donde no pueda "
        "mostrarse tal cual es, con toda su potencia y toda su vulnerabilidad. El matrimonio o la alianza "
        "significativa se convierte en el espejo donde su yo se reconoce y se afirma, como si la pareja fuera "
        "el testigo necesario de su existencia. Proyecta la imagen de una compañera que no pasa desapercibida, "
        "de esas que al entrar a un lugar ya se sabe que están acompañadas aunque vengan solas. Quienes la "
        "rodean perciben que lleva la relación con orgullo, que no esconde su compromiso ni lo minimiza, que "
        "defiende a su pareja con una lealtad que raya en lo instintivo. Sin embargo, bajo esa fachada de "
        "seguridad habita una lucha silenciosa: el miedo a que la unión la devore, a que el nosotros termine "
        "borrando las fronteras del yo. Necesita estar con el otro pero también necesita seguir sintiéndose "
        "ella misma, y esa tensión la mantiene en un estado de alerta permanente. Le cuesta distinguir entre "
        "entregarse y perderse, entre compartir el poder y cederlo por completo. Cuando encuentra el equilibrio, "
        "es la compañera más leal y directa. En el matrimonio pone toda la fuerza de su personalidad al "
        "servicio de la alianza: no hay problema que no enfrente junto al otro, no hay crisis que la haga "
        "huir. Su presencia es tan intensa que la pareja siempre sabe que cuenta con ella. La igualdad la "
        "ejerce con naturalidad porque no concibe una relación donde uno mande y el otro obedezca. Pero la "
        "sombra es difícil de eludir: la tendencia a imponer su voluntad disfrazada de iniciativa, la "
        "necesidad de tener la razón en cada desacuerdo. Cuando la traición llega, su reacción es inmediata "
        "y devastadora, capaz de cortar el vínculo con una frialdad que sorprende incluso a quienes la "
        "conocen bien. La lucha por el poder se convierte en el eje de la relación, y cada conflicto es una "
        "batalla donde nadie quiere perder. Para sanar, debe aprender que la verdadera fortaleza en el amor "
        "no está en dominar, sino en la capacidad de encontrarse a sí misma sin destruir al otro en el intento."
    ),
    "juno_en_casa_2": (
        "Juno en la Segunda casa hace del compromiso una cuestión de valores y de recursos compartidos. "
        "Para quien tiene este emplazamiento, el amor verdadero se construye sobre bases tangibles: la "
        "seguridad económica, la estabilidad material, el esfuerzo conjunto por edificar un patrimonio que "
        "sostenga la vida en común. No entiende las relaciones como vuelos románticos sin aterrizaje, sino "
        "como empresas que requieren inversión, paciencia y administración cuidadosa. El matrimonio es un "
        "proyecto de largo plazo donde cada uno aporta lo que tiene y juntos multiplican el resultado. "
        "Proyecta la imagen de una compañera sensata y confiable, de esas que recuerdan los aniversarios "
        "pero también revisan el presupuesto mensual. La gente la percibe como alguien que valora la lealtad "
        "por encima de todo, que no abandona a los suyos ni en los peores momentos. Pero dentro de ella "
        "habita un miedo profundo a la carencia, a que el amor no sea suficiente cuando el dinero falta. "
        "Su conflicto íntimo es la confusión entre el valor de la relación y el valor de lo que la relación "
        "proporciona. Necesita sentirse segura para entregarse, y esa seguridad a veces la mide en términos "
        "demasiado concretos. La posesividad se cuela en sus gestos más tiernos, y confunde la estabilidad "
        "con el control de los recursos. Cuando logra separar el amor de la posesión, es la compañera más "
        "generosa y constante. En el matrimonio, construye un hogar que es refugio y fortaleza, donde las "
        "necesidades básicas están cubiertas y el otro puede descansar. Sabe perdonar las ofensas si el "
        "vínculo profundo sigue intacto, porque para ella lo que importa es lo que perdura. Pero la sombra "
        "es terca y silenciosa: cuando la confianza se rompe, no olvida jamás. El resentimiento se acumula "
        "como una deuda impaga, y cada discusión saca a relucir agravios viejos que nunca se saldaron. "
        "Su terquedad la mantiene en relaciones que ya no la nutren solo porque ha invertido demasiado "
        "como para soltar. La traición la golpea en el centro de su seguridad, y entonces se vuelve fría, "
        "calculadora, incapaz de recordar que alguna vez amó sin condiciones. La lección que debe aprender "
        "es que la verdadera seguridad no se construye con bienes acumulados, sino con la certeza de ser "
        "valiosa por sí misma, más allá de lo que posee o de lo que el otro le puede dar."
    ),
    "juno_en_casa_3": (
        "Juno en la Tercera casa convierte el compromiso en un diálogo que nunca se agota. Para quien "
        "tiene este emplazamiento, la relación de pareja es ante todo un intercambio de ideas, palabras "
        "y miradas que comunican más que cualquier promesa. El amor verdadero se demuestra en la conversación "
        "que fluye sin esfuerzo, en los debates que encienden la pasión, en los silencios cómplices que "
        "no necesitan explicación. No concibe una unión donde no se pueda hablar de todo, donde la mente "
        "no encuentre estímulo en la mente del otro. Proyecta la imagen de una compañera curiosa y "
        "versátil, de esas que siempre tienen una historia que contar y una pregunta que hacer. Quienes la "
        "rodean la perciben como alguien que mantiene viva la relación con ocurrencias, con mensajes "
        "inesperados, con lecturas compartidas que alimentan el vínculo. Sin embargo, bajo esa agilidad "
        "mental se esconde una inquietud que no la deja reposar. Teme al aburrimiento como otros temen "
        "a la soledad, y ese miedo la empuja a buscar estímulos fuera cuando la conversación se aquieta. "
        "Su conflicto más íntimo es la dificultad para quedarse quieta en un solo corazón: necesita "
        "novedad, sorpresa, pero también anhela la profundidad que solo da el tiempo compartido. A veces "
        "habla de más para no sentir, o intelectualiza las emociones para no enfrentar el vértigo de la "
        "intimidad verdadera. Cuando canaliza su energía hacia la luz, es la compañera que nunca deja "
        "que la relación se oxide. Su habilidad para comunicar lo que siente es tan genuina que la pareja "
        "siempre sabe dónde está parada. En el matrimonio, es la que propone viajes, cursos, proyectos "
        "que los dos emprenden juntos, la que mantiene la chispa del interés mutuo. Sabe perdonar porque "
        "entiende que las palabras hieren pero también sanan. Pero la sombra es escurridiza: cuando el "
        "diálogo se convierte en monólogo, cuando la crítica reemplaza a la curiosidad, la relación se "
        "desgasta sin que ella lo note. Puede usar la palabra como arma y la ironía como escudo. La "
        "infidelidad emocional, los coqueteos intelectuales, la conexión secreta con otro que entiende "
        "lo que la pareja ya no entiende, son riesgos que la acechan. Su miedo a perderse algo la lleva "
        "a sabotear la paz que tanto dice querer. Para sanar, debe entender que el verdadero compromiso "
        "no es una jaula para su mente, sino el espacio seguro donde dejar de buscar afuera lo que ya "
        "tiene adentro."
    ),
    "juno_en_casa_4": (
        "Juno en la Cuarta casa hace del compromiso un refugio donde las almas se reconocen sin necesidad "
        "de explicaciones. Para quien tiene este emplazamiento, el amor verdadero es el hogar, ese lugar "
        "emocional donde se puede bajar las defensas y ser quien realmente se es. El matrimonio o la "
        "alianza significativa representa la raíz, el origen de una nueva familia, la continuación de "
        "un linaje afectivo que trasciende al individuo. Proyecta la imagen de una compañera que cuida, "
        "que nutre, que recuerda cómo le gusta el café al otro y qué música lo tranquiliza cuando está "
        "tenso. La gente la percibe como la memoria afectiva de la relación, la que guarda las fotos, "
        "los recuerdos, las tradiciones que sostienen el vínculo. Pero bajo esa entrega se agita un mar "
        "de inseguridades. Teme al abandono con una intensidad que a veces la paraliza, y ese miedo la "
        "lleva a aferrarse a la pareja como si de ello dependiera su supervivencia. Su conflicto más "
        "profundo es la danza entre el deseo de fusionarse y el pánico a perderse en el otro. Necesita "
        "pruebas constantes de amor porque su confianza se renueva cada día: cada silencio, cada demora, "
        "cada distracción del otro la hace temer lo peor. Cuando sana sus heridas, se transforma en la "
        "compañera más leal y abrigadora. Construye un hogar donde todos quieren volver, un espacio de "
        "contención donde las heridas se curan con su presencia. En el matrimonio, es el ancla que "
        "sostiene cuando todo lo demás se mueve. Sabe escuchar sin juzgar, sostener sin invadir, y "
        "perdona con generosidad para preservar el vínculo que tanto le costó construir. Pero la sombra "
        "es pegajosa y a veces asfixiante: su necesidad de seguridad se convierte en dependencia, y los "
        "celos la vuelven suspicaz. Su memoria emocional no olvida ni perdona del todo, y puede usar "
        "el victimismo como herramienta para retener al otro. Cuando se siente herida, castiga con "
        "silencio o con gestos de sacrificio que hacen sentir culpable a la pareja por querer su "
        "espacio. La traición la destroza porque siente que el suelo mismo se abre bajo sus pies, y "
        "entonces se repliega en sí misma con una tristeza que parece no tener fin. Para sanar, debe "
        "aprender que el verdadero hogar no está en el otro, sino en la capacidad de cobijarse a sí "
        "misma. Solo quien puede estar en paz con su propia compañía puede ofrecer al otro un refugio "
        "que no sea una prisión."
    ),
    "juno_en_casa_5": (
        "Juno en la Quinta casa convierte el compromiso en una obra de arte que se celebra cada día. "
        "Para quien tiene este emplazamiento, el amor verdadero es un juego apasionado donde el placer, "
        "la creatividad y la alegría son los pilares de la unión. No concibe una relación que no incluya "
        "risas, aventuras, gestos grandiosos y la capacidad de maravillarse juntos. El matrimonio es un "
        "escenario donde el amor se representa con toda la intensidad del corazón abierto. Proyecta la "
        "imagen de una compañera magnética y generosa, de esas que iluminan la habitación cuando entran "
        "y que celebran cada logro de la pareja como si fuera propio. Quienes la rodean ven en ella a "
        "alguien que ama sin miedo al ridículo, que propone citas improvisadas y que mantiene viva la "
        "llama del romance con una dedicación casi artística. Sin embargo, bajo ese brillo se esconde "
        "una vulnerabilidad que ella misma niega. Necesita ser el centro del universo afectivo de su "
        "pareja, y cuando la atención se desvía, el drama estalla. Su conflicto más íntimo es el miedo "
        "a no ser suficiente: cada gesto de indiferencia lo interpreta como una herida al orgullo, y "
        "su necesidad de admiración puede volverse insaciable. Quiere ser la reina, pero también quiere "
        "ser la única, y esa exigencia a veces agota al otro. Cuando logra equilibrar su corazón, es la "
        "compañera más cálida y entregada del zodíaco. Ama con una lealtad inquebrantable y una "
        "generosidad que no mide lo que da. El matrimonio se convierte en una fiesta continua donde "
        "ella es la anfitriona y la invitada al mismo tiempo. Sabe perdonar si el otro se acerca con "
        "humildad, porque su corazón es grande y no le gusta guardar rencor. Pero la sombra es tan "
        "brillante que ciega: el ego convierte la relación en un escenario donde ella es la única "
        "estrella. La necesidad de admiración constante cansa a la pareja, que siente que compite "
        "con un personaje más que con una persona real. Los celos y el orgullo malherido la llevan a "
        "reacciones desproporcionadas. Cuando la traición llega, su dolor es teatral y genuino al mismo "
        "tiempo, y la humillación de no haber sido suficiente la marca de forma indeleble. Para sanar, "
        "debe entender que el verdadero amor no exige ser el centro del universo del otro, sino "
        "compartir el escenario con la misma generosidad con la que el sol comparte su luz sin pedir "
        "nada a cambio."
    ),
    "juno_en_casa_6": (
        "Juno en la Sexta casa convierte el compromiso en un servicio cotidiano que se demuestra en "
        "los pequeños gestos. Para quien tiene este emplazamiento, el amor verdadero no se declama en "
        "grandes discursos sino que se construye en la rutina diaria: el desayuno preparado, la "
        "medicación recordada a tiempo, el espacio ordenado donde el otro puede descansar. El "
        "matrimonio es un organismo vivo que requiere cuidado constante, atención a los detalles y "
        "la voluntad de mejorar cada día como equipo. Proyecta la imagen de una compañera eficiente "
        "y dedicada, de esas que siempre están atentas a lo que el otro necesita antes de que lo pida. "
        "Quienes la rodean la perciben como una mujer de palabra, confiable, que nunca falla cuando "
        "se la necesita. Pero dentro de ella habita un juez implacable que no le da tregua. Se exige "
        "tanto como exige a su pareja, y el perfeccionismo envenena la relación sin que ella lo "
        "note. Su conflicto más hondo es la guerra entre aceptar al otro como es y la necesidad de "
        "mejorarlo, de corregir todo lo que considera imperfecto. Analiza cada gesto, cada silencio, "
        "cada hábito del otro buscando fallas donde solo hay humanidad. La ansiedad la consume cuando "
        "las cosas no salen como planeó, y entonces la crítica se convierte en su lenguaje del amor. "
        "Cuando calla al crítico interno, se convierte en la compañera más leal y servicial. Su amor "
        "se expresa en actos concretos que transforman lo mundano en sagrado. En el matrimonio, "
        "organiza el hogar con esmero para que el otro viva en armonía. Sabe perdonar porque analiza "
        "las motivaciones y entiende que todos tienen días malos. Pero la sombra es fría y paralizante: "
        "la crítica constante erosiona la autoestima de la pareja, que siente que nunca está a la "
        "altura. Puede servir hasta anularse, confundiendo el amor con el sacrificio y la entrega "
        "con la pérdida de sí misma. La tendencia a preocuparse la lleva a somatizar los conflictos "
        "en forma de enfermedades que son el lenguaje del cuerpo cuando la palabra no alcanza. La "
        "traición la destruye no tanto por el engaño como por la imperfección que revela en la "
        "historia que construyó con tanto esmero. Para sanar, debe aprender que el amor no se "
        "merece con obras, se recibe como un don, y que la perfección no es requisito para ser "
        "amada ni para amar."
    ),
    "juno_en_casa_7": (
        "Juno en la Séptima casa encuentra su expresión más natural y poderosa, pues esta es la casa "
        "del matrimonio y las asociaciones. Para quien tiene este emplazamiento, el compromiso no es "
        "una opción sino una necesidad del alma: la identidad se completa en el encuentro con el otro, "
        "y la vida cobra sentido cuando se comparte con una pareja que es a la vez espejo y compañero "
        "de camino. No concibe la existencia sin una alianza significativa, sin ese tú que la ayuda a "
        "definir quién es ella misma. Proyecta la imagen de una compañera que nació para la sociedad, "
        "para el diálogo, para construir puentes donde otros ven muros. La gente la percibe como "
        "alguien que sabe ceder sin humillarse, que busca el equilibrio incluso en medio de la "
        "tormenta. Sin embargo, bajo esa fachada de armonía se agita una duda que la atormenta: "
        "el miedo a tomar la decisión equivocada, a entregarse a quien no la merece, a quedarse "
        "atrapada en una relación que la empequeñezca. Su conflicto más íntimo es la balanza que "
        "nunca termina de equilibrarse entre el deseo de fundirse y el terror a desaparecer en el "
        "otro. Necesita la aprobación de la pareja para sentirse completa, y esa dependencia la "
        "vuelve vulnerable a relaciones donde da más de lo que recibe. A veces se queda en vínculos "
        "insatisfactorios por horror a romper la paz que tanto trabajo le costó construir. Cuando "
        "habita su poder, es la compañera más justa y refinada. En el matrimonio, es la jueza que "
        "sabe escuchar ambos lados, la que construye consensos y encuentra soluciones donde otros "
        "solo ven diferencias. Sabe perdonar porque entiende la complejidad de la naturaleza humana "
        "y porque valora más la armonía que tener la razón. Pero la sombra es peligrosa precisamente "
        "porque se disfraza de virtud: la búsqueda obsesiva del equilibrio la vuelve complaciente, y "
        "su incapacidad para confrontar la lleva a decir que sí cuando todo su ser quiere decir que "
        "no. Los resentimientos se acumulan silenciosamente hasta que estallan en el peor momento. "
        "La coquetería cruza la línea de la lealtad por la necesidad de sentirse deseada, de saber "
        "que todavía puede elegir. Cuando la traición llega, es doblemente dolorosa porque siente "
        "que el universo entero rompió el pacto de armonía que ella había tejido con tanto cuidado. "
        "Para sanar, debe recordar que la verdadera armonía no nace de la apariencia de paz, sino "
        "de la autenticidad de dos seres que eligen enfrentar juntos la verdad, por incómoda que sea."
    ),
    "juno_en_casa_8": (
        "Juno en la Octava casa convierte el compromiso en un viaje al fondo del alma donde el amor "
        "y el poder se entrelazan de forma indisoluble. Para quien tiene este emplazamiento, la "
        "relación de pareja no puede conformarse con la superficie: necesita penetrar hasta los "
        "lugares más oscuros del otro, conocer sus secretos, sus miedos, sus deseos inconfesables, "
        "y ser conocida de la misma manera. El matrimonio es un pacto de transformación mutua, una "
        "muerte simbólica que ambos atraviesan juntos para renacer en algo nuevo. Proyecta la imagen "
        "de una compañera magnética e intensa, de mirada que atraviesa cualquier máscara y no se "
        "conforma con respuestas evasivas. Quienes la rodean sienten que hay algo peligroso en ella, "
        "un poder oculto que la vuelve fascinante y aterradora al mismo tiempo. Exige lealtad "
        "absoluta y ofrece lo mismo, sin términos medios. Pero su interior está lleno de fantasmas. "
        "Lleva cicatrices de traiciones pasadas que no terminan de cerrar, y el miedo a ser herida "
        "la mantiene siempre alerta, siempre probando al otro sin que este lo sepa. Su conflicto "
        "más atormentado es la paradoja de desear fusionarse con el otro mientras el terror a la "
        "vulnerabilidad la obliga a controlarlo todo. Quiere rendirse al amor pero no sabe cómo "
        "bajar la guardia. La intimidad la aterra tanto como la atrae, y esa tensión la consume. "
        "Cuando canaliza su intensidad hacia la luz, es la compañera más leal y transformadora que "
        "pueda encontrarse. Su amor no conoce términos medios: es para siempre o no es. En el "
        "matrimonio, es la guardiana de los secretos del otro, la que sostiene la mano en las "
        "peores crisis, la que no huye cuando la tormenta arrecia. Sabe perdonar lo imperdonable "
        "si hay un proceso genuino de transformación. Pero la sombra es destructiva como un incendio "
        "subterráneo: los celos la consumen y el control se vuelve una cárcel para ambos. Cuando "
        "la traicionan, su venganza es calculada y devastadora, y la intensidad del amor se "
        "convierte en obsesión que no da tregua. El poder lo quiere todo para ella, y compartirlo "
        "le resulta casi una humillación. Para sanar, debe entender que la verdadera lealtad no "
        "se exige, se inspira, y que entregar el control no es morir, sino empezar finalmente a "
        "vivir sin la pesadumbre de tener que vigilarlo todo."
    ),
    "juno_en_casa_9": (
        "Juno en la Novena casa hace del compromiso una aventura del espíritu que no conoce fronteras. "
        "Para quien tiene este emplazamiento, el amor verdadero es un viaje compartido, una exploración "
        "constante de horizontes nuevos que solo tiene sentido si se hace acompañada. No concibe una "
        "relación que no la desafíe intelectualmente, que no la empuje a crecer, que no le prometa "
        "descubrimientos que transformen su manera de ver el mundo. El matrimonio es la expedición "
        "más importante de su vida. Proyecta la imagen de una compañera entusiasta y optimista, de "
        "esas que contagian ganas de vivir y que convencen al otro de emprender viajes imposibles. "
        "Quienes la rodean la ven como una mujer libre que nunca pide permiso para ser feliz, que "
        "encuentra en la pareja a su cómplice de aventuras. Pero dentro de ella arde un miedo "
        "profundo al encierro. Entra en pánico cuando el compromiso huele a rutina, cuando los "
        "días se vuelven predecibles, cuando la relación se instala en la comodidad que mata la "
        "aventura. Su conflicto íntimo es la tensión entre echar raíces y volar sin ataduras, entre "
        "la promesa de permanencia y la necesidad de libertad. Cada vez que la relación se vuelve "
        "demasiado cómoda, siente que traiciona su esencia más profunda. Si la pareja no crece al "
        "mismo ritmo, la frustración se instala como un veneno lento. Cuando logra armonizar su "
        "necesidad de libertad con el compromiso, es una compañera inspiradora que eleva al otro "
        "a nuevas alturas. El matrimonio se convierte en una universidad de la vida donde ambos "
        "aprenden y se expanden mutuamente. Sabe perdonar con una generosidad casi filosófica "
        "porque cree en la capacidad de redención del ser humano. Pero la sombra es el fantasma "
        "del compromiso inconcluso: el miedo a perderse algo mejor la mantiene siempre mirando "
        "el horizonte en lugar de lo que tiene delante. Su honestidad, que ella llama virtud, se "
        "convierte en excusa para herir sin filtro. La impaciencia la domina cuando la relación "
        "exige trabajo emocional en lugar de aventura. Idealiza a la pareja hasta que la realidad "
        "la estrella contra el suelo, y entonces la decepción es tan grande como lo fue la "
        "idealización. La infidelidad la acecha no por falta de amor, sino por la emoción de lo "
        "nuevo, de lo desconocido. Cuando la pareja le pone límites, su primera reacción es huir. "
        "Para sanar, debe entender que el verdadero horizonte no está en la distancia sino en la "
        "profundidad que se alcanza cuando se deja de buscar afuera y se empieza a construir "
        "adentro. La libertad más grande no es poder irse, sino poder quedarse sin sentirse atrapada."
    ),
    "juno_en_casa_10": (
        "Juno en la Décima casa convierte el compromiso en una empresa que el mundo entero debe "
        "reconocer. Para quien tiene este emplazamiento, la relación de pareja no es un asunto "
        "privado sino una declaración pública de intenciones. El matrimonio o la alianza "
        "significativa es un pilar de su reputación, un logro que se exhibe con orgullo y que "
        "demanda respeto. Necesita que el mundo sepa que ha sido elegida, que su compromiso es "
        "serio y que su pareja está a la altura de sus aspiraciones. Proyecta la imagen de una "
        "compañera exitosa y ambiciosa, de esas que forman con su pareja un equipo que inspira "
        "admiración. Quienes la rodean perciben que su relación es un reflejo de su posición en "
        "la vida, y que no aceptaría un vínculo que no sumara a su prestigio. Pero bajo esa "
        "fachada de logro se esconde una presión inmensa. Su conflicto más íntimo es la confusión "
        "entre el amor genuino y la necesidad de aprobación social. Se pregunta si está con su "
        "pareja porque la ama o porque la relación se ve bien ante los demás. El miedo al fracaso "
        "la persigue: cada problema en la pareja lo vive como una mancha en su reputación, como "
        "una confirmación de que no es suficiente. Le cuesta mostrar vulnerabilidad porque ha "
        "aprendido que la fortaleza es lo único que el mundo respeta. Cuando logra conectar con "
        "su corazón verdadero, es la compañera más leal y confiable. Su amor se demuestra "
        "construyendo futuro, ofreciendo seguridad, y honrando las promesas incluso cuando ya "
        "nadie las recuerda. En el matrimonio, es la socia perfecta que camina junto al otro "
        "hacia la cima que ambos eligieron. Sabe perdonar si el otro demuestra con acciones que "
        "merece otra oportunidad, porque para ella los hechos valen más que las palabras. Pero "
        "la sombra puede ser fría y calculadora: la ambición la lleva a priorizar el trabajo "
        "sobre la relación, y la pareja siente que compite con la carrera por un lugar en su "
        "vida. La disciplina que la sostiene también la aísla, y a veces el otro comparte la "
        "cama con una extraña. Cuando la traicionan, no hay drama ni escándalo, sino un silencio "
        "gélido que nunca se cierra del todo. Guarda rencor con la misma paciencia con la que "
        "construyó el amor, y espera el momento de equilibrar la balanza. Su sentido de "
        "responsabilidad la lleva a asumir el control de todo, incluida la relación, y entonces "
        "la pareja se convierte en un subordinado más. Para sanar, debe recordar que el amor no "
        "es una empresa ni un proyecto de ascenso social. La verdadera fortaleza no está en "
        "mantener las apariencias, sino en mostrarse vulnerable cuando el corazón lo necesita, "
        "incluso si el mundo entero está mirando."
    ),
    "juno_en_casa_11": (
        "Juno en la Undécima casa hace del compromiso una alianza que trasciende a la pareja misma "
        "para abrazar al mundo. Para quien tiene este emplazamiento, el amor verdadero no se encierra "
        "en cuatro paredes sino que se expande hacia la comunidad, los amigos, las causas compartidas "
        "que dan sentido a la vida. No concibe una relación que no esté conectada con algo más grande "
        "que ambos, un ideal, un proyecto colectivo o una visión del futuro que los une. El matrimonio "
        "es una sociedad al servicio de algo mayor. Proyecta la imagen de una compañera original e "
        "independiente, de esas que no se dejan atrapar por los celos ni por las convenciones. Quienes "
        "la rodean la ven como alguien que valora la amistad tanto como el romance, que integra a su "
        "pareja en su círculo social sin perder su individualidad. Sin embargo, dentro de ella habita "
        "una frialdad que desconcierta. Teme a la intimidad emocional tanto como la desea, y se "
        "refugia en la razón para no sentir. Su conflicto más íntimo es la dificultad para conectar "
        "con sus propios sentimientos y expresarlos. Analiza la relación en lugar de sentirla, se "
        "protege de la vulnerabilidad detrás de un muro de ideas y proyectos. Cuando la pareja exige "
        "cercanía emocional, ella se retira a la seguridad de la abstracción, dejando al otro con la "
        "sensación de que no logra alcanzarla del todo. Cuando logra integrar mente y corazón, es la "
        "compañera más innovadora y leal a su manera. Su amor no conoce celos posesivos ni "
        "dependencias asfixiantes. Construye una relación basada en la confianza y el respeto mutuo, "
        "donde ambos tienen espacio para crecer por separado y juntos. En el matrimonio, es la "
        "visionaria que proyecta el futuro en pareja, que sueña con un mundo mejor y lo construye "
        "desde su relación. Sabe perdonar porque entiende la complejidad humana y no se apega a las "
        "formas. Pero la sombra puede ser gélida y distante: su necesidad de libertad mal entendida "
        "la lleva a huir del compromiso emocional cuando este se vuelve demasiado intenso. La "
        "relación corre el riesgo de convertirse en un acuerdo de amistad que evita las profundidades "
        "del amor apasionado. Su imprevisibilidad cansa al compañero, que nunca sabe si encontrará "
        "cercanía o distancia. La frialdad emocional se convierte en un muro infranqueable que "
        "ninguna conversación logra derribar. Su reacción ante la traición es sorprendentemente "
        "racional, pero el dolor queda enterrado tan hondo que después es imposible procesarlo. "
        "Para sanar, debe aprender que la verdadera libertad no es ausencia de ataduras, sino la "
        "capacidad de elegir aquellas que la hacen crecer sin dejar de ser ella misma."
    ),
    "juno_en_casa_12": (
        "Juno en la Duodécima casa disuelve los límites del compromiso hasta hacer del amor una "
        "experiencia mística donde el yo y el otro se confunden. Para quien tiene este "
        "emplazamiento, la relación de pareja no es un contrato ni una sociedad sino un destino "
        "espiritual, un encuentro de almas que trasciende la lógica y las explicaciones "
        "racionales. No busca una pareja, busca un alma gemela con quien fusionarse en un plano "
        "que va más allá de lo tangible. El matrimonio es una comunión secreta que el mundo no "
        "necesita entender. Proyecta la imagen de una compañera soñadora y compasiva, de esas "
        "que aman sin condiciones y que parecen entender al otro mejor que él mismo. Quienes la "
        "rodean perciben una sensibilidad excepcional, una capacidad casi mágica para sanar con "
        "su sola presencia. En la relación, teje los hilos invisibles que unen a la pareja en un "
        "plano que solo ellos conocen. Pero el océano también guarda monstruos en sus "
        "profundidades. Su conflicto más trágico es la imposibilidad de poner límites, de "
        "distinguir dónde termina ella y dónde empieza el otro. Absorbe las emociones de la "
        "pareja como una esponja y las confunde con las propias. Idealiza el amor y proyecta "
        "sobre el compañero cualidades que no existen, y cuando la realidad se impone, la "
        "desilusión es devastadora. Se entrega a relaciones que prometen salvación pero terminan "
        "hundiéndola más. Cuando logra mantenerse en la superficie, es la compañera más "
        "compasiva y espiritualmente generosa que pueda encontrarse. Su amor no conoce juicio, "
        "y en el matrimonio es el bálsamo que todo lo cura sin pedir nada a cambio. Perdona lo "
        "imperdonable porque su corazón no está hecho para guardar rencor. La intimidad con ella "
        "es una experiencia casi mística que trasciende lo físico. Pero la sombra es la más "
        "peligrosa de todas precisamente porque no se ve venir. Se pierde en el otro hasta "
        "desaparecer, acepta abusos disfrazados de amor romántico y confunde el sufrimiento con "
        "la profundidad del vínculo. La mentira más peligrosa no siempre viene del otro: ella "
        "también se miente, inventando una historia perfecta donde no caben las imperfecciones "
        "de la realidad. La infidelidad es un riesgo constante no por desamor sino por su "
        "incapacidad para decir que no, para establecer el límite que la protegería. Cuando la "
        "traición finalmente la descubre, se hunde en un mar de culpa y de dolor del que parece "
        "imposible salir. Para sanar, debe aprender a poner límites sin sentir que traiciona la "
        "esencia del amor. El verdadero amor no exige la disolución del yo, sino la celebración "
        "de dos almas completas que eligen compartirse sin perderse. Solo desde la propia "
        "totalidad se puede amar al otro sin morir en el intento."
    ),
}

with open(FILEPATH, "r", encoding="utf-8") as f:
    content = f.read()

for key, new_text in entries.items():
    pattern = re.escape(f'"{key}"') + r'\s*:\s*"[^"]*"'
    replacement = json.dumps(key, ensure_ascii=False) + ": " + json.dumps(new_text, ensure_ascii=False)
    content = re.sub(pattern, replacement, content)

with open(FILEPATH, "w", encoding="utf-8") as f:
    f.write(content)

print("Done. Character counts:")
for key, text in entries.items():
    print(f"  {key}: {len(text)} chars")
