import json
import os

filepath = os.path.join(os.path.dirname(__file__), "casas_signos.json")

with open(filepath, "r", encoding="utf-8") as f:
    data = json.load(f)

entries = {
    "casa_9_aries": (
        "Casa 9 en Aries\n\n"
        "Quienes tienen la Casa 9 en Aries se lanzan a la busqueda de significado con la misma energia impulsiva con la que un explorador emprende una expedicion sin mapa. La filosofia para ellos no es un ejercicio de contemplacion sino una aventura intelectual que requiere coraje, accion y la disposicion a quemar las naves de las creencias heredadas. No se conforman con respuestas prestadas ni con sistemas de pensamiento que otros han construido: necesitan descubrir su propia verdad, incluso si eso significa cuestionar todo lo que la autoridad o la tradicion les ha ensenado. Sus viajes son expediciones donde el destino importa menos que la experiencia de lanzarse a lo desconocido, y la educacion superior es un campo de batalla donde defienden sus ideas con la pasion de quien sabe que la busqueda de la verdad es el proposito mas elevado de la existencia.\n\n"
        "La imagen que proyectan es la de personas audaces, independientes y apasionadas por sus convicciones. Los demas las ven como pioneras intelectuales que no temen desafiar el pensamiento establecido y que defienden sus creencias con una conviccion que puede resultar inspiradora o intimidante. Sin embargo, detras de esta fachada de seguridad filosofica hay una impaciencia que las lleva a veces a adoptar posiciones extremas sin la reflexion suficiente, movidas por el entusiasmo del momento mas que por una comprension profunda y matizada de los temas que abordan.\n\n"
        "El conflicto central de esta posicion es la tension entre la afirmacion de las propias creencias y la tolerancia hacia las creencias ajenas. Su tendencia a defender su verdad con tal intensidad puede cerrarles a perspectivas que contradicen sus convicciones, y su impaciencia con los procesos educativos formales puede impedirles la profundidad que requiere una verdadera formacion filosofica. Necesitan aprender que la sabiduria no solo se encuentra en la afirmacion valiente de las propias ideas sino tambien en la humildad de reconocer que siempre hay mas que descubrir, y que el verdadero buscador espiritual no teme la contradiccion sino que la abraza como parte del camino.\n\n"
        "En su expresion mas evolucionada, quienes tienen esta posicion son pioneros del pensamiento que abren caminos filosoficos donde antes solo habia dogmas. Su coraje intelectual inspira a otros a cuestionar sus propias creencias y a emprender su propia busqueda de significado, y su capacidad de actuar segun sus convicciones las convierte en lideres de movimientos espirituales o educativos. La sombra a trabajar es el dogmatismo de signo contrario: la tendencia a rebelarse contra toda autoridad simplemente por el placer de la rebelion, perdiendo de vista que la verdadera libertad filosofica incluye la capacidad de aprender incluso de aquellos a quienes se desafia."
    ),
    "casa_9_tauro": (
        "Casa 9 en Tauro\n\n"
        "Quienes tienen la Casa 9 en Tauro buscan el significado de la vida a traves de la experiencia sensorial directa y la conexion con la naturaleza, como quien sabe que la sabiduria no solo habita en los libros sino tambien en la tierra que se pisa y en el vino que se comparte. Su filosofia es practica, concreta, enraizada en el cuerpo y en los sentidos: no les interesan las abstracciones que no pueden tocarse ni los sistemas de pensamiento que niegan el valor de lo material. La educacion superior para ellos debe tener aplicacion practica, y los viajes son vividos como experiencias sensoriales donde el paisaje, la gastronomia y las texturas del lugar son tan importantes como el encuentro cultural. Su busqueda de sentido pasa por construir una cosmovision que integre lo espiritual con lo material, lo trascendente con lo tangible.\n\n"
        "La imagen que proyectan es la de personas serenas y estables en sus convicciones, que no se dejan arrastrar por modas intelectuales ni por entusiasmos pasajeros. Los demas las perciben como rocas de sabiduria practica, como quienes tienen los pies en la tierra incluso cuando hablan de temas elevados. Sin embargo, detras de esta solidez hay una resistencia al cambio de paradigma que puede convertirse en rigidez dogmatica: una vez que han adoptado un sistema de creencias, les cuesta modificarlo incluso cuando la evidencia o la experiencia les muestra sus limitaciones.\n\n"
        "El conflicto central de esta posicion es la tension entre la busqueda de la verdad y la comodidad de las certezas establecidas. Su necesidad de seguridad se extiende al plano filosofico: prefieren respuestas firmes a preguntas abiertas, y pueden aferrarse a tradiciones religiosas o filosoficas que les proporcionan un marco estable pero que limitan su crecimiento espiritual. El desarrollo personal implica aprender que la verdadera sabiduria no es un tesoro que se posee sino un horizonte que se camina, y que la seguridad filosofica mas profunda viene de la confianza en la capacidad de adaptarse a nuevas comprensiones, no de la rigidez de las creencias inmutables.\n\n"
        "En su expresion mas positiva, los nativos de esta posicion construyen sistemas de pensamiento que integran la sabiduria ancestral con la experiencia practica de una manera que otros encuentran profundamente util y reconfortante. Su capacidad de ensenar a traves del ejemplo y de transmitir conocimiento a traves de los sentidos las convierte en educadores excepcionales en campos que requieren paciencia y dedicacion. La sombra a trabajar es la rigidez filosofica y la tendencia a reducir la busqueda de significado a formulas demasiado simples que no hacen justicia a la complejidad de la existencia."
    ),
    "casa_9_geminis": (
        "Casa 9 en Geminis\n\n"
        "Quienes tienen la Casa 9 en Geminis abordan la filosofia, la educacion superior y los viajes con la curiosidad insaciable de quien nunca encuentra suficientes respuestas porque siempre hay una pregunta mas que hacer. Su mente es un puente entre mundos: saltan de un sistema de creencias a otro con una agilidad que desconcierta a quienes necesitan coherencia dogmatica, y su biblioteca interior contiene fragmentos de todas las tradiciones que han encontrado en su camino. La educacion superior no es una meta sino un proceso interminable, y los viajes son la excusa perfecta para coleccionar perspectivas, idiomas y formas de entender la vida que luego integran en una cosmovision tan variada como ellos mismos.\n\n"
        "La imagen que proyectan es la de personas intelectualmente estimulantes y versatiles que pueden conversar con igual soltura de teologia, fisica cuantica y literatura de viajes. Los demas disfrutan de su compania porque nunca se aburren a su lado, pero tambien pueden percibirlas como superficiales o inconsistentes en sus creencias. Detras de esta agilidad mental hay una cierta ansiedad: el miedo a comprometerse con una unica verdad porque eso significaria renunciar a todas las otras perspectivas que tambien les fascinan.\n\n"
        "El conflicto central de esta posicion es la dispersion filosofica y la dificultad para construir un sistema de creencias coherente. Su tendencia a acumular conocimientos sin integrarlos puede llevarlas a ser expertas en muchas tradiciones pero sin una base solida desde la cual actuar. La educacion formal puede resultarles limitante porque prefieren la exploracion autodidacta y los formatos de aprendizaje no convencionales. Necesitan aprender que la verdadera sabiduria no consiste en saber muchas cosas sino en saber como se relacionan entre si, y que el compromiso con una tradicion no excluye el respeto y la curiosidad por las demas.\n\n"
        "En su expresion mas evolucionada, estas personas son poliglotas culturales que construyen puentes entre tradiciones filosoficas diferentes. Su capacidad de traducir ideas complejas a lenguajes accesibles y de encontrar puntos de contacto entre sistemas de pensamiento aparentemente contradictorios las convierte en mediadoras interculturales excepcionales. La sombra a trabajar es la superficialidad intelectual: la tendencia a saber un poco de todo pero a no profundizar en nada lo suficiente como para que el conocimiento transforme realmente su vida."
    ),
    "casa_9_cancer": (
        "Casa 9 en Cancer\n\n"
        "Quienes tienen la Casa 9 en Cancer buscan el significado de la vida a traves de la conexion emocional con sus raices culturales y espirituales, como quien sabe que la sabiduria mas profunda se transmite a traves de las historias familiares y las tradiciones heredadas. Su filosofia esta impregnada de memoria afectiva: las creencias que adoptan estan profundamente conectadas con su historia personal y con el legado emocional de su linaje. Los viajes largos son peregrinaciones del corazon, donde cada destino esta cargado de significado emocional y cada encuentro es una oportunidad para expandir su comprension de lo que significa pertenecer a algo mas grande que uno mismo.\n\n"
        "La imagen que proyectan es la de personas que ensenan desde el corazon, cuya sabiduria parece brotar de una fuente antigua y personal que no necesita validacion academica. Los demas sienten que su conocimiento esta vivo, que no es teorico sino vivido y sentido en cada fibra de su ser. Sin embargo, detras de esta conexion profunda con lo ancestral hay una tendencia a idealizar las tradiciones del pasado y a resistirse a las nuevas perspectivas que cuestionan las creencias heredadas de la familia o la cultura de origen.\n\n"
        "El conflicto central de esta posicion es la dificultad para separar las creencias heredadas de las convicciones genuinamente propias. Su lealtad emocional a la familia y a la tradicion puede impedirles explorar sistemas de pensamiento que contradicen lo que les fue ensenado, y su sensibilidad las hace vulnerables a la culpa cuando cuestionan las creencias de sus ancestros. Necesitan aprender que honrar la tradicion no significa repetirla sin cuestionamiento, y que la verdadera herencia espiritual no es un conjunto de respuestas fijas sino una forma de buscar la verdad que cada generacion debe redescubrir a su manera.\n\n"
        "En su expresion mas positiva, los nativos de esta posicion son guardianes de la sabiduria ancestral que saben transmitir las tradiciones de una manera viva y emocionalmente significativa. Su capacidad de crear rituales y experiencias educativas que tocan el alma de quienes las reciben las convierte en maestras espirituales y educadoras excepcionales. La sombra a trabajar es el apego excesivo a las tradiciones del pasado y la resistencia a expandir su cosmovision mas alla de los limites de su herencia cultural y familiar."
    ),
    "casa_9_leo": (
        "Casa 9 en Leo\n\n"
        "Quienes tienen la Casa 9 en Leo abordan la busqueda de significado con la generosidad dramatica de quien sabe que la verdad merece ser contada desde un escenario iluminado. Su filosofia no es un asunto privado sino una actuacion publica donde comparten sus descubrimientos con la certeza de quien ha encontrado algo extraordinario. La educacion superior es un campo donde brillan, donde su entusiasmo por el conocimiento se vuelve contagioso, y los viajes son aventuras epicas que merecen ser narradas con todos los detalles que las convierten en leyendas. Su busqueda de sentido esta impulsada por la necesidad de encontrar una verdad tan grande, tan hermosa y tan digna de ser compartida que justifique su existencia.\n\n"
        "La imagen que proyectan es la de lideres filosoficos carismaticos cuya presencia transforma cualquier salon de clases en un teatro de ideas. Los demas se sienten atraidos por su pasion y por su capacidad de hacer que incluso los conceptos mas abstractos parezcan emocionantes y personalmente relevantes. Sin embargo, detras de este carisma intelectual hay una dependencia del reconocimiento que puede desviar su busqueda de la verdad: corren el riesgo de defender ciertas ideas no porque las consideren verdaderas sino porque generan la admiracion que necesitan.\n\n"
        "El conflicto central de esta posicion es la tension entre la busqueda genuina de la verdad y la necesidad de ser reconocido como sabio o iluminado. Su orgullo puede impedirles admitir que se equivocan o que hay perspectivas que no han considerado, y su tendencia al dramatismo puede llevarles a simplificar ideas complejas para hacerlas mas impactantes. Necesitan aprender que la verdadera autoridad espiritual no necesita ser validada por el aplauso ajeno, y que la humildad intelectual es una virtud mas valiosa que la capacidad de impresionar a una audiencia.\n\n"
        "En su expresion mas evolucionada, quienes tienen esta posicion son educadores inspiradores que encienden en otros el amor por la sabiduria. Su generosidad intelectual y su capacidad de celebrar los logros de sus estudiantes las convierte en mentoras excepcionales que dejan una huella profunda en quienes tienen la fortuna de aprender de ellas. La sombra a trabajar es el egocentrismo filosofico y la tendencia a convertir la busqueda de la verdad en una busqueda de protagonismo donde la sabiduria queda subordinada al deseo de brillar."
    ),
    "casa_9_virgo": (
        "Casa 9 en Virgo\n\n"
        "Quienes tienen la Casa 9 en Virgo buscan el significado de la vida con la misma precision analitica con la que un cientifico diseca un fenomeno para comprender sus mecanismos mas intimos. Su filosofia es rigurosa, meticulosa y profundamente comprometida con la honestidad intelectual: no les interesan las respuestas faciles ni las creencias que no resisten un examen critico detallado. La educacion superior es un camino de perfeccionamiento donde cada concepto debe ser comprendido en su totalidad antes de pasar al siguiente, y los viajes son oportunidades de estudio donde cada detalle del lugar visitado merece ser observado, catalogado y comprendido en su contexto.\n\n"
        "La imagen que proyectan es la de personas cultas y precisas cuyo conocimiento esta respaldado por un estudio riguroso y una atencion al detalle que inspira respeto. Los demas confian en su criterio porque saben que no hablan de lo que no han investigado a fondo, y su humildad intelectual las hace especialmente creibles. Sin embargo, detras de esta fachada de precision hay una autocrítica implacable que puede paralizar su expansion: ningun conocimiento les parece suficiente, ningun viaje esta lo suficientemente planificado, ninguna comprension es lo bastante completa.\n\n"
        "El conflicto central de esta posicion es la tension entre el perfeccionismo intelectual y la necesidad de lanzarse a la experiencia sin tenerlo todo controlado. Su tendencia a analizar en exceso puede impedirles la entrega a la experiencia directa que requieren los viajes y las busquedas espirituales autenticas. La educacion formal puede resultarles un campo fertil, pero tambien pueden quedar atrapadas en la acumulacion de titulos y certificaciones sin integrar realmente el conocimiento en su vida. Necesitan aprender que la sabiduria no es un destino que se alcanza cuando se ha acumulado suficiente informacion sino un camino que se recorre con el corazon abierto a la experiencia directa.\n\n"
        "En su expresion mas positiva, los nativos de esta posicion son academicos e investigadores excepcionales cuyo compromiso con la precision y la honestidad intelectual eleva el nivel de cualquier campo que aborden. Su capacidad de ensenar con claridad y de descomponer ideas complejas en componentes comprensibles las convierte en educadoras de primer nivel. La sombra a trabajar es el escepticismo que limita su capacidad de entrega a experiencias espirituales o filosoficas que no pueden ser medidas ni analizadas completamente."
    ),
    "casa_9_libra": (
        "Casa 9 en Libra\n\n"
        "Quienes tienen la Casa 9 en Libra buscan el significado de la vida a traves del equilibrio entre perspectivas opuestas, convencidas de que la verdad no habita en los extremos sino en el punto de encuentro entre las diferencias. Su filosofia es inherentemente dialogica: no pueden aceptar un sistema de creencias sin antes haber escuchado y considerado seriamente los argumentos de sus criticos y defensores por igual. La educacion superior es un espacio de intercambio donde las ideas se refinan a traves del contraste y la discusion respetuosa, y los viajes son una busqueda de armonia entre culturas, una oportunidad para descubrir que la belleza de la diversidad humana revela facetas de la verdad que ninguna tradicion por si sola podria contener.\n\n"
        "La imagen que proyectan es la de personas diplomaticas y cultivadas cuya busqueda de la verdad esta guiada por un profundo respeto por todas las perspectivas. Los demas las buscan como mediadoras en conflictos ideologicos y como consejeras en asuntos eticos porque confian en su capacidad de ver todos los angulos de una cuestion. Sin embargo, detras de esta ecuaminidad intelectual hay una indecision que puede impedirles tomar una posicion clara incluso cuando la situacion lo requiere, y su deseo de armonia puede llevarlas a evitar las verdades incomodas que podrian perturbar la paz.\n\n"
        "El conflicto central de esta posicion es la tension entre la busqueda del equilibrio y la necesidad de comprometerse con una verdad que a veces exige tomar partido. Su tendencia a ver todos los lados de un asunto puede paralizar su capacidad de accion y de Juicio, y su aversion al conflicto filosofico puede llevarlas a adoptar posiciones tibias que no hacen justicia a la complejidad de los problemas. Necesitan aprender que la verdadera sabiduria no consiste en mantenerse en un eterno equilibrio entre todas las opciones sino en tener el coraje de actuar segun las propias convicciones incluso cuando eso implica renunciar a la comodidad de la Neutralidad.\n\n"
        "En su expresion mas evolucionada, las personas con esta posicion son constructoras de puentes filosoficos que integran las mejores contribuciones de diferentes tradiciones en una cosmovision coherente y armoniosa. Su capacidad de ensenar a traves del dialogo y de crear espacios educativos donde todas las voces son escuchadas las convierte en educadoras excepcionales. La sombra a trabajar es la indecision filosofica y la tendencia a sacrificar la profundidad de las convicciones personales en el altar de una armonia superficial."
    ),
    "casa_9_escorpio": (
        "Casa 9 en Escorpio\n\n"
        "Quienes tienen la Casa 9 en Escorpio se sumergen en la busqueda de significado con la intensidad de quien sabe que las verdades que realmente importan estan enterradas bajo capas de ilusion y autoengano. Su filosofia no es un pasatiempo intelectual sino una cuestion de vida o muerte, una indagacion en los misterios mas oscuros de la existencia que requiere valor para mirar al abismo sin parpadear. La educacion superior es un viaje hacia lo oculto, una investigacion de los secretos que las religiones y filosofias convencionales prefieren no abordar, y los viajes son transformaciones iniciaticas donde cada destino las confronta con sus propias sombras y las obliga a renacer desde las cenizas de sus antiguas certezas.\n\n"
        "La imagen que proyectan es la de personas magneticas y profundas cuya presencia en cualquier entorno intelectual se siente con intensidad. Los demas intuyen que detras de sus palabras hay una sabiduria forjada en el fuego de experiencias transformadoras, y esta percepcion les otorga una autoridad que no necesita ser reclamada. Sin embargo, detras de esta profundidad hay una tendencia al secretismo y al control de la informacion que puede manifestarse como manipulacion intelectual o como resistencia a compartir sus descubrimientos mas valiosos.\n\n"
        "El conflicto central de esta posicion es la tension entre la busqueda de la verdad y el poder que el conocimiento otorga. Su intensidad las lleva a investigar hasta los rincones mas oscuros de cualquier sistema de creencias, pero tambien pueden usar lo que descubren para ejercer poder sobre quienes no tienen acceso a esa informacion. La desconfianza en las instituciones educativas y religiosas establecidas puede volverse un obstaculo para su formacion, y su tendencia al maximalismo emocional puede llevarlas a abrazar sistemas de creencias radicales con una devocion que raya en el fanatismo. Necesitan aprender que el verdadero poder del conocimiento no esta en poseerlo en secreto sino en compartirlo con integridad.\n\n"
        "En su expresion mas positiva, los nativos de esta posicion son investigadores de lo oculto y lo tabu que traen a la luz verdades que otros prefieren ignorar. Su capacidad de regeneracion filosofica las permite desmantelar sus propias creencias cuando ya no les sirven y construir otras nuevas desde cero con una honestidad radical que inspira a quienes las rodean. La sombra a trabajar es la tendencia al dogmatismo fanatico y el uso del conocimiento como herramienta de poder y control sobre los demas."
    ),
    "casa_9_sagitario": (
        "Casa 9 en Sagitario\n\n"
        "Quienes tienen la Casa 9 en Sagitario son los buscadores por excelencia del zodiaco, aquellos para quienes la vida es una peregrinacion constante hacia horizontes que siempre se desplazan un poco mas alla. Su filosofia es inherentemente optimista y expansiva: creen que el universo tiene un significado y que ellas estan aqui para descubrirlo, viajando, estudiando y explorando cada rincon de la experiencia humana. La educacion superior es su habitat natural, el espacio donde su mente inquieta encuentra el alimento que necesita, y los viajes largos son el eje de su existencia, la forma que tienen de conectar con la diversidad del mundo y de descubrir que la verdad tiene tantas caras como culturas existen. Su busqueda de sentido es incansable porque saben que nunca llegaran a un destino final, y es precisamente esa imposibilidad lo que hace que el viaje valga la pena.\n\n"
        "La imagen que proyectan es la de personas afortunadas, entusiastas y generosas que parecen haber encontrado la clave de la felicidad en la busqueda misma. Los demas se sienten inspirados por su optimismo y por su capacidad de ver el lado positivo incluso en las situaciones mas desafiantes. Sin embargo, detras de este entusiasmo contagioso hay una impaciencia que las lleva a veces a saltar de una filosofia a otra sin dar tiempo a que ninguna eche raices en su vida, y una tendencia a la evasion que utiliza el movimiento constante como excusa para no enfrentar las preguntas que requieren quedarse quieto y mirar hacia adentro.\n\n"
        "El conflicto central de esta posicion es la tension entre la expansion y la profundidad. Su apetito por la experiencia y el conocimiento puede convertirse en una dispersion que les impide la integracion necesaria para que el viaje se traduzca en sabiduria real. La educacion formal puede parecerles demasiado lenta y restrictiva, y su aversion a las estructuras academicas puede impedirles completar los procesos formativos que requieren disciplina sostenida. Necesitan aprender que la verdadera maestria no consiste en haber visitado muchos lugares o estudiado muchas tradiciones sino en haber permitido que al menos una experiencia de conocimiento transforme profundamente la forma de estar en el mundo.\n\n"
        "En su expresion mas evolucionada, los nativos de esta posicion son filosofos, exploradores y educadores que inspiran a otros con su amor por la sabiduria y su fe en el potencial humano. Su optimismo genuino y su generosidad intelectual crean a su alrededor un campo de posibilidades donde otros se sienten animados a emprender sus propias busquedas de significado. La sombra a trabajar es la evasion a traves del movimiento perpetuo y la tendencia a confundir la acumulacion de experiencias con la sabiduria genuina que solo se alcanza cuando se permite que la experiencia transforme realmente la propia vida."
    ),
    "casa_9_capricornio": (
        "Casa 9 en Capricornio\n\n"
        "Quienes tienen la Casa 9 en Capricornio buscan el significado de la vida con la seriedad y la disciplina de quien sabe que la sabiduria no se alcanza por inspiracion divina sino a traves del esfuerzo sostenido y la dedicacion a largo plazo. Su filosofia es estructurada, tradicional y pragmatica: valoran los sistemas de pensamiento que han resistido la prueba del tiempo y que ofrecen marcos claros para entender la existencia y guiar la accion. La educacion superior es un camino de ascenso donde cada titulo y cada logro academico representa un escalon en la construccion de su autoridad intelectual, y los viajes son empresas planificadas con meticulosidad donde cada destino tiene un proposito definido y cada experiencia debe contribuir a un plan mayor de desarrollo personal o profesional.\n\n"
        "La imagen que proyectan es la de personas cultas, serias y respetables cuyo conocimiento esta respaldado por anos de estudio disciplinado. Los demas reconocen en ellas la autoridad que viene de la dedicacion y la experiencia acumulada, y a menudo ocupan posiciones de liderazgo en instituciones educativas o religiosas. Sin embargo, detras de esta solidez academica hay un pesimismo que las lleva a veces a minusvalorar el valor de las experiencias que no estan respaldadas por credenciales formales, y una rigidez que puede cerrarles a las perspectivas innovadoras que desafian los marcos establecidos.\n\n"
        "El conflicto central de esta posicion es la tension entre el respeto por la tradicion y la necesidad de una busqueda de significado que sea genuinamente propia. Su tendencia a seguir los caminos establecidos puede impedirles la exploracion personal que requiere cualquier busqueda espiritual autentica, y su ambicion academica puede convertirse en una sustitucion de la verdadera sabiduria: acumulan titulos y reconocimientos sin permitir que el conocimiento toque realmente su corazon. La educacion superior puede ser un espacio donde prosperan, pero tambien donde quedan atrapadas en la jerarquia academica, confundiendo el estatus intelectual con la comprension profunda de la existencia. Necesitan aprender que la verdadera autoridad espiritual no se delega desde las instituciones sino que se conquista en la soledad de la propia busqueda interior.\n\n"
        "En su expresion mas positiva, los nativos de esta posicion construyen sistemas filosoficos y educativos que perduran a traves del tiempo, integrando la sabiduria de las tradiciones con las necesidades del mundo contemporaneo. Su disciplina y su compromiso con la excelencia las convierte en academicas, juezas o lideres religiosas de una integridad y una solidez que inspiran respeto. La sombra a trabajar es la rigidez dogmatica y la tendencia a confundir la acumulacion de credenciales academicas con el desarrollo de una sabiduria genuina y vivida."
    ),
    "casa_9_acuario": (
        "Casa 9 en Acuario\n\n"
        "Quienes tienen la Casa 9 en Acuario buscan el significado de la vida fuera de los senderos trillados de la tradicion, guiados por una vision humanitaria que busca la verdad que pueda liberar a la humanidad de sus cadenas ideologicas. Su filosofia es original, progresista y a menudo radical en su rechazo de los dogmas establecidos: no aceptan una idea como verdadera simplemente porque ha sido creida durante siglos, sino que someten cada creencia al escrutinio de una mente que valora la innovacion y la libertad de pensamiento por encima de todo. La educacion superior es un laboratorio de ideas donde experimentan con nuevos paradigmas, y los viajes son expediciones hacia formas alternativas de organizacion social y espiritual que amplian su comprension de lo que la humanidad puede llegar a ser.\n\n"
        "La imagen que proyectan es la de visionarios intelectuales cuyo pensamiento esta adelantado a su tiempo. Los demas pueden percibirlas como geniales pero erraticas, como personas cuyas ideas son tan originales que resultan dificiles de comprender o aceptar para las mentalidades convencionales. Sin embargo, detras de esta originalidad hay una cierta frialdad emocional que puede hacer que su busqueda filosofica resulte desconectada de las necesidades humanas concretas, y una tendencia a la rebelion gratuita que las lleva a veces a rechazar ideas valiosas simplemente porque son ampliamente aceptadas.\n\n"
        "El conflicto central de esta posicion es la tension entre la originalidad intelectual y la conexion con la sabiduria colectiva. Su necesidad de ser diferentes puede llevarlas a adoptar posiciones contrarias a la tradicion no por conviccion genuina sino por el placer de la transgresion, y su racionalidad puede convertirse en una barrera para las experiencias espirituales que requieren entrega y fe. La educacion superior tradicional puede resultarles demasiado restrictiva, pero tambien pueden tener dificultades para encontrar maestros que esten a la altura de su capacidad critica. Necesitan aprender que la verdadera originalidad no consiste en rechazar todo lo establecido sino en integrar las contribuciones del pasado con las intuiciones del futuro en una sintesis que honre ambas.\n\n"
        "En su expresion mas evolucionada, los nativos de esta posicion son innovadores filosoficos cuyas ideas contribuyen al avance de la conciencia colectiva. Su capacidad de pensar mas alla de los condicionamientos culturales y de visualizar futuros alternativos para la humanidad las convierte en lideres de movimientos espirituales y educativos progresistas. La sombra a trabajar es la desconexion entre sus ideales elevados y su encarnacion practica, y la tendencia a la rebelion que las lleva a veces a descartar la sabiduria acumulada por generaciones anteriores simplemente porque es tradicional."
    ),
    "casa_9_piscis": (
        "Casa 9 en Piscis\n\n"
        "Quienes tienen la Casa 9 en Piscis buscan el significado de la vida en las aguas profundas del inconsciente colectivo, donde las fronteras entre las tradiciones se disuelven y emerge una verdad que no puede ser atrapada en palabras ni en conceptos. Su filosofia es mistica, poetica y universalista: no se sienten limitadas por ningun sistema de creencias en particular porque intuyen que todas las religiones y filosofias son intentos imperfectos de senalar hacia una realidad que trasciende el lenguaje. La educacion superior para ellas no es solo un proceso intelectual sino una iniciacion espiritual, y los viajes son peregrinaciones donde cada destino es un espejo que refleja aspectos de su propio mundo interior que necesitan ser reconocidos e integrados.\n\n"
        "La imagen que proyectan es la de personas espirituales, compasivas y enigmaticas cuya sabiduria parece venir de una fuente que trasciende el estudio convencional. Los demas sienten que hay en ellas una profundidad que no se deja atrapar facilmente, una conexion con dimensiones de la experiencia que la mayoria no percibe. Sin embargo, detras de esta profundidad espiritual hay una confusion que puede dificultar la formulacion clara de sus ideas y la integracion practica de sus visiones en la vida cotidiana. Su sensibilidad las hace receptivas a las mas variadas influencias filosoficas, pero tambien las expone a sistemas de creencias que pueden no ser saludables para su desarrollo.\n\n"
        "El conflicto central de esta posicion es la tension entre la entrega a la experiencia mistica y la necesidad de mantener un anclaje en la realidad concreta. Su tendencia a disolver los limites entre sistemas de creencias puede llevarlas a un sincretismo confuso donde todo vale y nada tiene verdadera profundidad, y su sensibilidad espiritual puede convertirse en escapismo cuando utilizan la busqueda trascendente para evadir las responsabilidades materiales de la vida. La educacion formal puede resultarles insuficiente porque intuyen que la verdadera sabiduria no se transmite a traves de curriculos academicos sino a traves de la experiencia directa y la conexion con lo divino. Necesitan aprender que la verdadera espiritualidad no es una huida del mundo sino una forma mas plena de estar en el.\n\n"
        "En su expresion mas positiva, los nativos de esta posicion son canales de sabiduria universal que integran las ensenanzas de todas las tradiciones en una comprension compasiva y unificada de la existencia. Su capacidad de conectar con lo trascendente y de transmitir esa conexion a traves del arte, la musica o la guia espiritual las convierte en faros de inspiracion para quienes buscan un significado mas alla de lo material. La sombra a trabajar es la evasion espiritual y la tendencia a confundir la sensibilidad psiquica con la sabiduria genuina, asi como la dificultad para traducir sus visiones elevadas en acciones concretas que mejoren su vida y la de quienes las rodean."
    ),
}

# Update entries
for key, value in entries.items():
    data[key] = value

with open(filepath, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("=== Character counts for Casa 9 entries ===")
for key in entries:
    length = len(data[key])
    status = "OK" if length >= 1800 else f"SHORT (missing {1800 - length})"
    print(f"{key}: {length} chars - {status}")
